// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"github.com/fachebot/omni-grid-bot/internal/ent/migrate"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"github.com/fachebot/omni-grid-bot/internal/ent/grid"
	"github.com/fachebot/omni-grid-bot/internal/ent/matchedtrade"
	"github.com/fachebot/omni-grid-bot/internal/ent/order"
	"github.com/fachebot/omni-grid-bot/internal/ent/strategy"
	"github.com/fachebot/omni-grid-bot/internal/ent/syncprogress"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// Grid is the client for interacting with the Grid builders.
	Grid *GridClient
	// MatchedTrade is the client for interacting with the MatchedTrade builders.
	MatchedTrade *MatchedTradeClient
	// Order is the client for interacting with the Order builders.
	Order *OrderClient
	// Strategy is the client for interacting with the Strategy builders.
	Strategy *StrategyClient
	// SyncProgress is the client for interacting with the SyncProgress builders.
	SyncProgress *SyncProgressClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.Grid = NewGridClient(c.config)
	c.MatchedTrade = NewMatchedTradeClient(c.config)
	c.Order = NewOrderClient(c.config)
	c.Strategy = NewStrategyClient(c.config)
	c.SyncProgress = NewSyncProgressClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:          ctx,
		config:       cfg,
		Grid:         NewGridClient(cfg),
		MatchedTrade: NewMatchedTradeClient(cfg),
		Order:        NewOrderClient(cfg),
		Strategy:     NewStrategyClient(cfg),
		SyncProgress: NewSyncProgressClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:          ctx,
		config:       cfg,
		Grid:         NewGridClient(cfg),
		MatchedTrade: NewMatchedTradeClient(cfg),
		Order:        NewOrderClient(cfg),
		Strategy:     NewStrategyClient(cfg),
		SyncProgress: NewSyncProgressClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		Grid.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.Grid.Use(hooks...)
	c.MatchedTrade.Use(hooks...)
	c.Order.Use(hooks...)
	c.Strategy.Use(hooks...)
	c.SyncProgress.Use(hooks...)
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	c.Grid.Intercept(interceptors...)
	c.MatchedTrade.Intercept(interceptors...)
	c.Order.Intercept(interceptors...)
	c.Strategy.Intercept(interceptors...)
	c.SyncProgress.Intercept(interceptors...)
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *GridMutation:
		return c.Grid.mutate(ctx, m)
	case *MatchedTradeMutation:
		return c.MatchedTrade.mutate(ctx, m)
	case *OrderMutation:
		return c.Order.mutate(ctx, m)
	case *StrategyMutation:
		return c.Strategy.mutate(ctx, m)
	case *SyncProgressMutation:
		return c.SyncProgress.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// GridClient is a client for the Grid schema.
type GridClient struct {
	config
}

// NewGridClient returns a client for the Grid from the given config.
func NewGridClient(c config) *GridClient {
	return &GridClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `grid.Hooks(f(g(h())))`.
func (c *GridClient) Use(hooks ...Hook) {
	c.hooks.Grid = append(c.hooks.Grid, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `grid.Intercept(f(g(h())))`.
func (c *GridClient) Intercept(interceptors ...Interceptor) {
	c.inters.Grid = append(c.inters.Grid, interceptors...)
}

// Create returns a builder for creating a Grid entity.
func (c *GridClient) Create() *GridCreate {
	mutation := newGridMutation(c.config, OpCreate)
	return &GridCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Grid entities.
func (c *GridClient) CreateBulk(builders ...*GridCreate) *GridCreateBulk {
	return &GridCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *GridClient) MapCreateBulk(slice any, setFunc func(*GridCreate, int)) *GridCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &GridCreateBulk{err: fmt.Errorf("calling to GridClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*GridCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &GridCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Grid.
func (c *GridClient) Update() *GridUpdate {
	mutation := newGridMutation(c.config, OpUpdate)
	return &GridUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *GridClient) UpdateOne(_m *Grid) *GridUpdateOne {
	mutation := newGridMutation(c.config, OpUpdateOne, withGrid(_m))
	return &GridUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *GridClient) UpdateOneID(id int) *GridUpdateOne {
	mutation := newGridMutation(c.config, OpUpdateOne, withGridID(id))
	return &GridUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Grid.
func (c *GridClient) Delete() *GridDelete {
	mutation := newGridMutation(c.config, OpDelete)
	return &GridDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *GridClient) DeleteOne(_m *Grid) *GridDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *GridClient) DeleteOneID(id int) *GridDeleteOne {
	builder := c.Delete().Where(grid.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &GridDeleteOne{builder}
}

// Query returns a query builder for Grid.
func (c *GridClient) Query() *GridQuery {
	return &GridQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeGrid},
		inters: c.Interceptors(),
	}
}

// Get returns a Grid entity by its id.
func (c *GridClient) Get(ctx context.Context, id int) (*Grid, error) {
	return c.Query().Where(grid.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *GridClient) GetX(ctx context.Context, id int) *Grid {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *GridClient) Hooks() []Hook {
	return c.hooks.Grid
}

// Interceptors returns the client interceptors.
func (c *GridClient) Interceptors() []Interceptor {
	return c.inters.Grid
}

func (c *GridClient) mutate(ctx context.Context, m *GridMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&GridCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&GridUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&GridUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&GridDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Grid mutation op: %q", m.Op())
	}
}

// MatchedTradeClient is a client for the MatchedTrade schema.
type MatchedTradeClient struct {
	config
}

// NewMatchedTradeClient returns a client for the MatchedTrade from the given config.
func NewMatchedTradeClient(c config) *MatchedTradeClient {
	return &MatchedTradeClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `matchedtrade.Hooks(f(g(h())))`.
func (c *MatchedTradeClient) Use(hooks ...Hook) {
	c.hooks.MatchedTrade = append(c.hooks.MatchedTrade, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `matchedtrade.Intercept(f(g(h())))`.
func (c *MatchedTradeClient) Intercept(interceptors ...Interceptor) {
	c.inters.MatchedTrade = append(c.inters.MatchedTrade, interceptors...)
}

// Create returns a builder for creating a MatchedTrade entity.
func (c *MatchedTradeClient) Create() *MatchedTradeCreate {
	mutation := newMatchedTradeMutation(c.config, OpCreate)
	return &MatchedTradeCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of MatchedTrade entities.
func (c *MatchedTradeClient) CreateBulk(builders ...*MatchedTradeCreate) *MatchedTradeCreateBulk {
	return &MatchedTradeCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *MatchedTradeClient) MapCreateBulk(slice any, setFunc func(*MatchedTradeCreate, int)) *MatchedTradeCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &MatchedTradeCreateBulk{err: fmt.Errorf("calling to MatchedTradeClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*MatchedTradeCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &MatchedTradeCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for MatchedTrade.
func (c *MatchedTradeClient) Update() *MatchedTradeUpdate {
	mutation := newMatchedTradeMutation(c.config, OpUpdate)
	return &MatchedTradeUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *MatchedTradeClient) UpdateOne(_m *MatchedTrade) *MatchedTradeUpdateOne {
	mutation := newMatchedTradeMutation(c.config, OpUpdateOne, withMatchedTrade(_m))
	return &MatchedTradeUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *MatchedTradeClient) UpdateOneID(id int) *MatchedTradeUpdateOne {
	mutation := newMatchedTradeMutation(c.config, OpUpdateOne, withMatchedTradeID(id))
	return &MatchedTradeUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for MatchedTrade.
func (c *MatchedTradeClient) Delete() *MatchedTradeDelete {
	mutation := newMatchedTradeMutation(c.config, OpDelete)
	return &MatchedTradeDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *MatchedTradeClient) DeleteOne(_m *MatchedTrade) *MatchedTradeDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *MatchedTradeClient) DeleteOneID(id int) *MatchedTradeDeleteOne {
	builder := c.Delete().Where(matchedtrade.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &MatchedTradeDeleteOne{builder}
}

// Query returns a query builder for MatchedTrade.
func (c *MatchedTradeClient) Query() *MatchedTradeQuery {
	return &MatchedTradeQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeMatchedTrade},
		inters: c.Interceptors(),
	}
}

// Get returns a MatchedTrade entity by its id.
func (c *MatchedTradeClient) Get(ctx context.Context, id int) (*MatchedTrade, error) {
	return c.Query().Where(matchedtrade.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *MatchedTradeClient) GetX(ctx context.Context, id int) *MatchedTrade {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *MatchedTradeClient) Hooks() []Hook {
	return c.hooks.MatchedTrade
}

// Interceptors returns the client interceptors.
func (c *MatchedTradeClient) Interceptors() []Interceptor {
	return c.inters.MatchedTrade
}

func (c *MatchedTradeClient) mutate(ctx context.Context, m *MatchedTradeMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&MatchedTradeCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&MatchedTradeUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&MatchedTradeUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&MatchedTradeDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown MatchedTrade mutation op: %q", m.Op())
	}
}

// OrderClient is a client for the Order schema.
type OrderClient struct {
	config
}

// NewOrderClient returns a client for the Order from the given config.
func NewOrderClient(c config) *OrderClient {
	return &OrderClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `order.Hooks(f(g(h())))`.
func (c *OrderClient) Use(hooks ...Hook) {
	c.hooks.Order = append(c.hooks.Order, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `order.Intercept(f(g(h())))`.
func (c *OrderClient) Intercept(interceptors ...Interceptor) {
	c.inters.Order = append(c.inters.Order, interceptors...)
}

// Create returns a builder for creating a Order entity.
func (c *OrderClient) Create() *OrderCreate {
	mutation := newOrderMutation(c.config, OpCreate)
	return &OrderCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Order entities.
func (c *OrderClient) CreateBulk(builders ...*OrderCreate) *OrderCreateBulk {
	return &OrderCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *OrderClient) MapCreateBulk(slice any, setFunc func(*OrderCreate, int)) *OrderCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &OrderCreateBulk{err: fmt.Errorf("calling to OrderClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*OrderCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &OrderCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Order.
func (c *OrderClient) Update() *OrderUpdate {
	mutation := newOrderMutation(c.config, OpUpdate)
	return &OrderUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *OrderClient) UpdateOne(_m *Order) *OrderUpdateOne {
	mutation := newOrderMutation(c.config, OpUpdateOne, withOrder(_m))
	return &OrderUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *OrderClient) UpdateOneID(id int) *OrderUpdateOne {
	mutation := newOrderMutation(c.config, OpUpdateOne, withOrderID(id))
	return &OrderUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Order.
func (c *OrderClient) Delete() *OrderDelete {
	mutation := newOrderMutation(c.config, OpDelete)
	return &OrderDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *OrderClient) DeleteOne(_m *Order) *OrderDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *OrderClient) DeleteOneID(id int) *OrderDeleteOne {
	builder := c.Delete().Where(order.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &OrderDeleteOne{builder}
}

// Query returns a query builder for Order.
func (c *OrderClient) Query() *OrderQuery {
	return &OrderQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeOrder},
		inters: c.Interceptors(),
	}
}

// Get returns a Order entity by its id.
func (c *OrderClient) Get(ctx context.Context, id int) (*Order, error) {
	return c.Query().Where(order.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *OrderClient) GetX(ctx context.Context, id int) *Order {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *OrderClient) Hooks() []Hook {
	return c.hooks.Order
}

// Interceptors returns the client interceptors.
func (c *OrderClient) Interceptors() []Interceptor {
	return c.inters.Order
}

func (c *OrderClient) mutate(ctx context.Context, m *OrderMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&OrderCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&OrderUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&OrderUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&OrderDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Order mutation op: %q", m.Op())
	}
}

// StrategyClient is a client for the Strategy schema.
type StrategyClient struct {
	config
}

// NewStrategyClient returns a client for the Strategy from the given config.
func NewStrategyClient(c config) *StrategyClient {
	return &StrategyClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `strategy.Hooks(f(g(h())))`.
func (c *StrategyClient) Use(hooks ...Hook) {
	c.hooks.Strategy = append(c.hooks.Strategy, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `strategy.Intercept(f(g(h())))`.
func (c *StrategyClient) Intercept(interceptors ...Interceptor) {
	c.inters.Strategy = append(c.inters.Strategy, interceptors...)
}

// Create returns a builder for creating a Strategy entity.
func (c *StrategyClient) Create() *StrategyCreate {
	mutation := newStrategyMutation(c.config, OpCreate)
	return &StrategyCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Strategy entities.
func (c *StrategyClient) CreateBulk(builders ...*StrategyCreate) *StrategyCreateBulk {
	return &StrategyCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *StrategyClient) MapCreateBulk(slice any, setFunc func(*StrategyCreate, int)) *StrategyCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &StrategyCreateBulk{err: fmt.Errorf("calling to StrategyClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*StrategyCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &StrategyCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Strategy.
func (c *StrategyClient) Update() *StrategyUpdate {
	mutation := newStrategyMutation(c.config, OpUpdate)
	return &StrategyUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *StrategyClient) UpdateOne(_m *Strategy) *StrategyUpdateOne {
	mutation := newStrategyMutation(c.config, OpUpdateOne, withStrategy(_m))
	return &StrategyUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *StrategyClient) UpdateOneID(id int) *StrategyUpdateOne {
	mutation := newStrategyMutation(c.config, OpUpdateOne, withStrategyID(id))
	return &StrategyUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Strategy.
func (c *StrategyClient) Delete() *StrategyDelete {
	mutation := newStrategyMutation(c.config, OpDelete)
	return &StrategyDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *StrategyClient) DeleteOne(_m *Strategy) *StrategyDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *StrategyClient) DeleteOneID(id int) *StrategyDeleteOne {
	builder := c.Delete().Where(strategy.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &StrategyDeleteOne{builder}
}

// Query returns a query builder for Strategy.
func (c *StrategyClient) Query() *StrategyQuery {
	return &StrategyQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeStrategy},
		inters: c.Interceptors(),
	}
}

// Get returns a Strategy entity by its id.
func (c *StrategyClient) Get(ctx context.Context, id int) (*Strategy, error) {
	return c.Query().Where(strategy.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *StrategyClient) GetX(ctx context.Context, id int) *Strategy {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *StrategyClient) Hooks() []Hook {
	return c.hooks.Strategy
}

// Interceptors returns the client interceptors.
func (c *StrategyClient) Interceptors() []Interceptor {
	return c.inters.Strategy
}

func (c *StrategyClient) mutate(ctx context.Context, m *StrategyMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&StrategyCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&StrategyUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&StrategyUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&StrategyDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Strategy mutation op: %q", m.Op())
	}
}

// SyncProgressClient is a client for the SyncProgress schema.
type SyncProgressClient struct {
	config
}

// NewSyncProgressClient returns a client for the SyncProgress from the given config.
func NewSyncProgressClient(c config) *SyncProgressClient {
	return &SyncProgressClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `syncprogress.Hooks(f(g(h())))`.
func (c *SyncProgressClient) Use(hooks ...Hook) {
	c.hooks.SyncProgress = append(c.hooks.SyncProgress, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `syncprogress.Intercept(f(g(h())))`.
func (c *SyncProgressClient) Intercept(interceptors ...Interceptor) {
	c.inters.SyncProgress = append(c.inters.SyncProgress, interceptors...)
}

// Create returns a builder for creating a SyncProgress entity.
func (c *SyncProgressClient) Create() *SyncProgressCreate {
	mutation := newSyncProgressMutation(c.config, OpCreate)
	return &SyncProgressCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of SyncProgress entities.
func (c *SyncProgressClient) CreateBulk(builders ...*SyncProgressCreate) *SyncProgressCreateBulk {
	return &SyncProgressCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *SyncProgressClient) MapCreateBulk(slice any, setFunc func(*SyncProgressCreate, int)) *SyncProgressCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &SyncProgressCreateBulk{err: fmt.Errorf("calling to SyncProgressClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*SyncProgressCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &SyncProgressCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for SyncProgress.
func (c *SyncProgressClient) Update() *SyncProgressUpdate {
	mutation := newSyncProgressMutation(c.config, OpUpdate)
	return &SyncProgressUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *SyncProgressClient) UpdateOne(_m *SyncProgress) *SyncProgressUpdateOne {
	mutation := newSyncProgressMutation(c.config, OpUpdateOne, withSyncProgress(_m))
	return &SyncProgressUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *SyncProgressClient) UpdateOneID(id int) *SyncProgressUpdateOne {
	mutation := newSyncProgressMutation(c.config, OpUpdateOne, withSyncProgressID(id))
	return &SyncProgressUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for SyncProgress.
func (c *SyncProgressClient) Delete() *SyncProgressDelete {
	mutation := newSyncProgressMutation(c.config, OpDelete)
	return &SyncProgressDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *SyncProgressClient) DeleteOne(_m *SyncProgress) *SyncProgressDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *SyncProgressClient) DeleteOneID(id int) *SyncProgressDeleteOne {
	builder := c.Delete().Where(syncprogress.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &SyncProgressDeleteOne{builder}
}

// Query returns a query builder for SyncProgress.
func (c *SyncProgressClient) Query() *SyncProgressQuery {
	return &SyncProgressQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeSyncProgress},
		inters: c.Interceptors(),
	}
}

// Get returns a SyncProgress entity by its id.
func (c *SyncProgressClient) Get(ctx context.Context, id int) (*SyncProgress, error) {
	return c.Query().Where(syncprogress.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *SyncProgressClient) GetX(ctx context.Context, id int) *SyncProgress {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *SyncProgressClient) Hooks() []Hook {
	return c.hooks.SyncProgress
}

// Interceptors returns the client interceptors.
func (c *SyncProgressClient) Interceptors() []Interceptor {
	return c.inters.SyncProgress
}

func (c *SyncProgressClient) mutate(ctx context.Context, m *SyncProgressMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&SyncProgressCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&SyncProgressUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&SyncProgressUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&SyncProgressDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown SyncProgress mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		Grid, MatchedTrade, Order, Strategy, SyncProgress []ent.Hook
	}
	inters struct {
		Grid, MatchedTrade, Order, Strategy, SyncProgress []ent.Interceptor
	}
)
