// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/fachebot/omni-grid-bot/internal/ent/matchedtrade"
	"github.com/shopspring/decimal"
)

// MatchedTrade is the model entity for the MatchedTrade schema.
type MatchedTrade struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreateTime holds the value of the "create_time" field.
	CreateTime time.Time `json:"create_time,omitempty"`
	// UpdateTime holds the value of the "update_time" field.
	UpdateTime time.Time `json:"update_time,omitempty"`
	// StrategyId holds the value of the "strategyId" field.
	StrategyId string `json:"strategyId,omitempty"`
	// Symbol holds the value of the "symbol" field.
	Symbol string `json:"symbol,omitempty"`
	// BuyClientOrderId holds the value of the "buyClientOrderId" field.
	BuyClientOrderId *string `json:"buyClientOrderId,omitempty"`
	// BuyBaseAmount holds the value of the "buyBaseAmount" field.
	BuyBaseAmount *decimal.Decimal `json:"buyBaseAmount,omitempty"`
	// BuyQuoteAmount holds the value of the "buyQuoteAmount" field.
	BuyQuoteAmount *decimal.Decimal `json:"buyQuoteAmount,omitempty"`
	// BuyOrderTimestamp holds the value of the "buyOrderTimestamp" field.
	BuyOrderTimestamp *int64 `json:"buyOrderTimestamp,omitempty"`
	// SellClientOrderId holds the value of the "sellClientOrderId" field.
	SellClientOrderId *string `json:"sellClientOrderId,omitempty"`
	// SellBaseAmount holds the value of the "sellBaseAmount" field.
	SellBaseAmount *decimal.Decimal `json:"sellBaseAmount,omitempty"`
	// SellQuoteAmount holds the value of the "sellQuoteAmount" field.
	SellQuoteAmount *decimal.Decimal `json:"sellQuoteAmount,omitempty"`
	// SellOrderTimestamp holds the value of the "sellOrderTimestamp" field.
	SellOrderTimestamp *int64 `json:"sellOrderTimestamp,omitempty"`
	// Profit holds the value of the "profit" field.
	Profit       *float64 `json:"profit,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*MatchedTrade) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case matchedtrade.FieldBuyBaseAmount, matchedtrade.FieldBuyQuoteAmount, matchedtrade.FieldSellBaseAmount, matchedtrade.FieldSellQuoteAmount:
			values[i] = &sql.NullScanner{S: new(decimal.Decimal)}
		case matchedtrade.FieldProfit:
			values[i] = new(sql.NullFloat64)
		case matchedtrade.FieldID, matchedtrade.FieldBuyOrderTimestamp, matchedtrade.FieldSellOrderTimestamp:
			values[i] = new(sql.NullInt64)
		case matchedtrade.FieldStrategyId, matchedtrade.FieldSymbol, matchedtrade.FieldBuyClientOrderId, matchedtrade.FieldSellClientOrderId:
			values[i] = new(sql.NullString)
		case matchedtrade.FieldCreateTime, matchedtrade.FieldUpdateTime:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the MatchedTrade fields.
func (_m *MatchedTrade) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case matchedtrade.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case matchedtrade.FieldCreateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field create_time", values[i])
			} else if value.Valid {
				_m.CreateTime = value.Time
			}
		case matchedtrade.FieldUpdateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field update_time", values[i])
			} else if value.Valid {
				_m.UpdateTime = value.Time
			}
		case matchedtrade.FieldStrategyId:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field strategyId", values[i])
			} else if value.Valid {
				_m.StrategyId = value.String
			}
		case matchedtrade.FieldSymbol:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field symbol", values[i])
			} else if value.Valid {
				_m.Symbol = value.String
			}
		case matchedtrade.FieldBuyClientOrderId:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field buyClientOrderId", values[i])
			} else if value.Valid {
				_m.BuyClientOrderId = new(string)
				*_m.BuyClientOrderId = value.String
			}
		case matchedtrade.FieldBuyBaseAmount:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field buyBaseAmount", values[i])
			} else if value.Valid {
				_m.BuyBaseAmount = new(decimal.Decimal)
				*_m.BuyBaseAmount = *value.S.(*decimal.Decimal)
			}
		case matchedtrade.FieldBuyQuoteAmount:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field buyQuoteAmount", values[i])
			} else if value.Valid {
				_m.BuyQuoteAmount = new(decimal.Decimal)
				*_m.BuyQuoteAmount = *value.S.(*decimal.Decimal)
			}
		case matchedtrade.FieldBuyOrderTimestamp:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field buyOrderTimestamp", values[i])
			} else if value.Valid {
				_m.BuyOrderTimestamp = new(int64)
				*_m.BuyOrderTimestamp = value.Int64
			}
		case matchedtrade.FieldSellClientOrderId:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field sellClientOrderId", values[i])
			} else if value.Valid {
				_m.SellClientOrderId = new(string)
				*_m.SellClientOrderId = value.String
			}
		case matchedtrade.FieldSellBaseAmount:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field sellBaseAmount", values[i])
			} else if value.Valid {
				_m.SellBaseAmount = new(decimal.Decimal)
				*_m.SellBaseAmount = *value.S.(*decimal.Decimal)
			}
		case matchedtrade.FieldSellQuoteAmount:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field sellQuoteAmount", values[i])
			} else if value.Valid {
				_m.SellQuoteAmount = new(decimal.Decimal)
				*_m.SellQuoteAmount = *value.S.(*decimal.Decimal)
			}
		case matchedtrade.FieldSellOrderTimestamp:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field sellOrderTimestamp", values[i])
			} else if value.Valid {
				_m.SellOrderTimestamp = new(int64)
				*_m.SellOrderTimestamp = value.Int64
			}
		case matchedtrade.FieldProfit:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field profit", values[i])
			} else if value.Valid {
				_m.Profit = new(float64)
				*_m.Profit = value.Float64
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the MatchedTrade.
// This includes values selected through modifiers, order, etc.
func (_m *MatchedTrade) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this MatchedTrade.
// Note that you need to call MatchedTrade.Unwrap() before calling this method if this MatchedTrade
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *MatchedTrade) Update() *MatchedTradeUpdateOne {
	return NewMatchedTradeClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the MatchedTrade entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *MatchedTrade) Unwrap() *MatchedTrade {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: MatchedTrade is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *MatchedTrade) String() string {
	var builder strings.Builder
	builder.WriteString("MatchedTrade(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("create_time=")
	builder.WriteString(_m.CreateTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("update_time=")
	builder.WriteString(_m.UpdateTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("strategyId=")
	builder.WriteString(_m.StrategyId)
	builder.WriteString(", ")
	builder.WriteString("symbol=")
	builder.WriteString(_m.Symbol)
	builder.WriteString(", ")
	if v := _m.BuyClientOrderId; v != nil {
		builder.WriteString("buyClientOrderId=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.BuyBaseAmount; v != nil {
		builder.WriteString("buyBaseAmount=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.BuyQuoteAmount; v != nil {
		builder.WriteString("buyQuoteAmount=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.BuyOrderTimestamp; v != nil {
		builder.WriteString("buyOrderTimestamp=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.SellClientOrderId; v != nil {
		builder.WriteString("sellClientOrderId=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.SellBaseAmount; v != nil {
		builder.WriteString("sellBaseAmount=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.SellQuoteAmount; v != nil {
		builder.WriteString("sellQuoteAmount=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.SellOrderTimestamp; v != nil {
		builder.WriteString("sellOrderTimestamp=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.Profit; v != nil {
		builder.WriteString("profit=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteByte(')')
	return builder.String()
}

// MatchedTrades is a parsable slice of MatchedTrade.
type MatchedTrades []*MatchedTrade
