// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/fachebot/perp-dex-grid-bot/internal/ent/matchedtrades"
	"github.com/fachebot/perp-dex-grid-bot/internal/ent/predicate"
	"github.com/shopspring/decimal"
)

// MatchedTradesUpdate is the builder for updating MatchedTrades entities.
type MatchedTradesUpdate struct {
	config
	hooks    []Hook
	mutation *MatchedTradesMutation
}

// Where appends a list predicates to the MatchedTradesUpdate builder.
func (_u *MatchedTradesUpdate) Where(ps ...predicate.MatchedTrades) *MatchedTradesUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetStrategyId sets the "strategyId" field.
func (_u *MatchedTradesUpdate) SetStrategyId(v string) *MatchedTradesUpdate {
	_u.mutation.SetStrategyId(v)
	return _u
}

// SetNillableStrategyId sets the "strategyId" field if the given value is not nil.
func (_u *MatchedTradesUpdate) SetNillableStrategyId(v *string) *MatchedTradesUpdate {
	if v != nil {
		_u.SetStrategyId(*v)
	}
	return _u
}

// SetPrice sets the "price" field.
func (_u *MatchedTradesUpdate) SetPrice(v decimal.Decimal) *MatchedTradesUpdate {
	_u.mutation.SetPrice(v)
	return _u
}

// SetNillablePrice sets the "price" field if the given value is not nil.
func (_u *MatchedTradesUpdate) SetNillablePrice(v *decimal.Decimal) *MatchedTradesUpdate {
	if v != nil {
		_u.SetPrice(*v)
	}
	return _u
}

// SetBuyClientOrderId sets the "buyClientOrderId" field.
func (_u *MatchedTradesUpdate) SetBuyClientOrderId(v int64) *MatchedTradesUpdate {
	_u.mutation.ResetBuyClientOrderId()
	_u.mutation.SetBuyClientOrderId(v)
	return _u
}

// SetNillableBuyClientOrderId sets the "buyClientOrderId" field if the given value is not nil.
func (_u *MatchedTradesUpdate) SetNillableBuyClientOrderId(v *int64) *MatchedTradesUpdate {
	if v != nil {
		_u.SetBuyClientOrderId(*v)
	}
	return _u
}

// AddBuyClientOrderId adds value to the "buyClientOrderId" field.
func (_u *MatchedTradesUpdate) AddBuyClientOrderId(v int64) *MatchedTradesUpdate {
	_u.mutation.AddBuyClientOrderId(v)
	return _u
}

// ClearBuyClientOrderId clears the value of the "buyClientOrderId" field.
func (_u *MatchedTradesUpdate) ClearBuyClientOrderId() *MatchedTradesUpdate {
	_u.mutation.ClearBuyClientOrderId()
	return _u
}

// SetBuyBaseAmount sets the "buyBaseAmount" field.
func (_u *MatchedTradesUpdate) SetBuyBaseAmount(v decimal.Decimal) *MatchedTradesUpdate {
	_u.mutation.SetBuyBaseAmount(v)
	return _u
}

// SetNillableBuyBaseAmount sets the "buyBaseAmount" field if the given value is not nil.
func (_u *MatchedTradesUpdate) SetNillableBuyBaseAmount(v *decimal.Decimal) *MatchedTradesUpdate {
	if v != nil {
		_u.SetBuyBaseAmount(*v)
	}
	return _u
}

// ClearBuyBaseAmount clears the value of the "buyBaseAmount" field.
func (_u *MatchedTradesUpdate) ClearBuyBaseAmount() *MatchedTradesUpdate {
	_u.mutation.ClearBuyBaseAmount()
	return _u
}

// SetBuyQuoteAmount sets the "buyQuoteAmount" field.
func (_u *MatchedTradesUpdate) SetBuyQuoteAmount(v decimal.Decimal) *MatchedTradesUpdate {
	_u.mutation.SetBuyQuoteAmount(v)
	return _u
}

// SetNillableBuyQuoteAmount sets the "buyQuoteAmount" field if the given value is not nil.
func (_u *MatchedTradesUpdate) SetNillableBuyQuoteAmount(v *decimal.Decimal) *MatchedTradesUpdate {
	if v != nil {
		_u.SetBuyQuoteAmount(*v)
	}
	return _u
}

// ClearBuyQuoteAmount clears the value of the "buyQuoteAmount" field.
func (_u *MatchedTradesUpdate) ClearBuyQuoteAmount() *MatchedTradesUpdate {
	_u.mutation.ClearBuyQuoteAmount()
	return _u
}

// SetBuyOrderTimestamp sets the "buyOrderTimestamp" field.
func (_u *MatchedTradesUpdate) SetBuyOrderTimestamp(v int64) *MatchedTradesUpdate {
	_u.mutation.ResetBuyOrderTimestamp()
	_u.mutation.SetBuyOrderTimestamp(v)
	return _u
}

// SetNillableBuyOrderTimestamp sets the "buyOrderTimestamp" field if the given value is not nil.
func (_u *MatchedTradesUpdate) SetNillableBuyOrderTimestamp(v *int64) *MatchedTradesUpdate {
	if v != nil {
		_u.SetBuyOrderTimestamp(*v)
	}
	return _u
}

// AddBuyOrderTimestamp adds value to the "buyOrderTimestamp" field.
func (_u *MatchedTradesUpdate) AddBuyOrderTimestamp(v int64) *MatchedTradesUpdate {
	_u.mutation.AddBuyOrderTimestamp(v)
	return _u
}

// ClearBuyOrderTimestamp clears the value of the "buyOrderTimestamp" field.
func (_u *MatchedTradesUpdate) ClearBuyOrderTimestamp() *MatchedTradesUpdate {
	_u.mutation.ClearBuyOrderTimestamp()
	return _u
}

// SetSellClientOrderId sets the "sellClientOrderId" field.
func (_u *MatchedTradesUpdate) SetSellClientOrderId(v int64) *MatchedTradesUpdate {
	_u.mutation.ResetSellClientOrderId()
	_u.mutation.SetSellClientOrderId(v)
	return _u
}

// SetNillableSellClientOrderId sets the "sellClientOrderId" field if the given value is not nil.
func (_u *MatchedTradesUpdate) SetNillableSellClientOrderId(v *int64) *MatchedTradesUpdate {
	if v != nil {
		_u.SetSellClientOrderId(*v)
	}
	return _u
}

// AddSellClientOrderId adds value to the "sellClientOrderId" field.
func (_u *MatchedTradesUpdate) AddSellClientOrderId(v int64) *MatchedTradesUpdate {
	_u.mutation.AddSellClientOrderId(v)
	return _u
}

// ClearSellClientOrderId clears the value of the "sellClientOrderId" field.
func (_u *MatchedTradesUpdate) ClearSellClientOrderId() *MatchedTradesUpdate {
	_u.mutation.ClearSellClientOrderId()
	return _u
}

// SetSellBaseAmount sets the "sellBaseAmount" field.
func (_u *MatchedTradesUpdate) SetSellBaseAmount(v decimal.Decimal) *MatchedTradesUpdate {
	_u.mutation.SetSellBaseAmount(v)
	return _u
}

// SetNillableSellBaseAmount sets the "sellBaseAmount" field if the given value is not nil.
func (_u *MatchedTradesUpdate) SetNillableSellBaseAmount(v *decimal.Decimal) *MatchedTradesUpdate {
	if v != nil {
		_u.SetSellBaseAmount(*v)
	}
	return _u
}

// ClearSellBaseAmount clears the value of the "sellBaseAmount" field.
func (_u *MatchedTradesUpdate) ClearSellBaseAmount() *MatchedTradesUpdate {
	_u.mutation.ClearSellBaseAmount()
	return _u
}

// SetSellQuoteAmount sets the "sellQuoteAmount" field.
func (_u *MatchedTradesUpdate) SetSellQuoteAmount(v decimal.Decimal) *MatchedTradesUpdate {
	_u.mutation.SetSellQuoteAmount(v)
	return _u
}

// SetNillableSellQuoteAmount sets the "sellQuoteAmount" field if the given value is not nil.
func (_u *MatchedTradesUpdate) SetNillableSellQuoteAmount(v *decimal.Decimal) *MatchedTradesUpdate {
	if v != nil {
		_u.SetSellQuoteAmount(*v)
	}
	return _u
}

// ClearSellQuoteAmount clears the value of the "sellQuoteAmount" field.
func (_u *MatchedTradesUpdate) ClearSellQuoteAmount() *MatchedTradesUpdate {
	_u.mutation.ClearSellQuoteAmount()
	return _u
}

// SetSellOrderTimestamp sets the "sellOrderTimestamp" field.
func (_u *MatchedTradesUpdate) SetSellOrderTimestamp(v int64) *MatchedTradesUpdate {
	_u.mutation.ResetSellOrderTimestamp()
	_u.mutation.SetSellOrderTimestamp(v)
	return _u
}

// SetNillableSellOrderTimestamp sets the "sellOrderTimestamp" field if the given value is not nil.
func (_u *MatchedTradesUpdate) SetNillableSellOrderTimestamp(v *int64) *MatchedTradesUpdate {
	if v != nil {
		_u.SetSellOrderTimestamp(*v)
	}
	return _u
}

// AddSellOrderTimestamp adds value to the "sellOrderTimestamp" field.
func (_u *MatchedTradesUpdate) AddSellOrderTimestamp(v int64) *MatchedTradesUpdate {
	_u.mutation.AddSellOrderTimestamp(v)
	return _u
}

// ClearSellOrderTimestamp clears the value of the "sellOrderTimestamp" field.
func (_u *MatchedTradesUpdate) ClearSellOrderTimestamp() *MatchedTradesUpdate {
	_u.mutation.ClearSellOrderTimestamp()
	return _u
}

// Mutation returns the MatchedTradesMutation object of the builder.
func (_u *MatchedTradesUpdate) Mutation() *MatchedTradesMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *MatchedTradesUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MatchedTradesUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *MatchedTradesUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MatchedTradesUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MatchedTradesUpdate) check() error {
	if v, ok := _u.mutation.StrategyId(); ok {
		if err := matchedtrades.StrategyIdValidator(v); err != nil {
			return &ValidationError{Name: "strategyId", err: fmt.Errorf(`ent: validator failed for field "MatchedTrades.strategyId": %w`, err)}
		}
	}
	return nil
}

func (_u *MatchedTradesUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(matchedtrades.Table, matchedtrades.Columns, sqlgraph.NewFieldSpec(matchedtrades.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.StrategyId(); ok {
		_spec.SetField(matchedtrades.FieldStrategyId, field.TypeString, value)
	}
	if value, ok := _u.mutation.Price(); ok {
		_spec.SetField(matchedtrades.FieldPrice, field.TypeString, value)
	}
	if value, ok := _u.mutation.BuyClientOrderId(); ok {
		_spec.SetField(matchedtrades.FieldBuyClientOrderId, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedBuyClientOrderId(); ok {
		_spec.AddField(matchedtrades.FieldBuyClientOrderId, field.TypeInt64, value)
	}
	if _u.mutation.BuyClientOrderIdCleared() {
		_spec.ClearField(matchedtrades.FieldBuyClientOrderId, field.TypeInt64)
	}
	if value, ok := _u.mutation.BuyBaseAmount(); ok {
		_spec.SetField(matchedtrades.FieldBuyBaseAmount, field.TypeString, value)
	}
	if _u.mutation.BuyBaseAmountCleared() {
		_spec.ClearField(matchedtrades.FieldBuyBaseAmount, field.TypeString)
	}
	if value, ok := _u.mutation.BuyQuoteAmount(); ok {
		_spec.SetField(matchedtrades.FieldBuyQuoteAmount, field.TypeString, value)
	}
	if _u.mutation.BuyQuoteAmountCleared() {
		_spec.ClearField(matchedtrades.FieldBuyQuoteAmount, field.TypeString)
	}
	if value, ok := _u.mutation.BuyOrderTimestamp(); ok {
		_spec.SetField(matchedtrades.FieldBuyOrderTimestamp, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedBuyOrderTimestamp(); ok {
		_spec.AddField(matchedtrades.FieldBuyOrderTimestamp, field.TypeInt64, value)
	}
	if _u.mutation.BuyOrderTimestampCleared() {
		_spec.ClearField(matchedtrades.FieldBuyOrderTimestamp, field.TypeInt64)
	}
	if value, ok := _u.mutation.SellClientOrderId(); ok {
		_spec.SetField(matchedtrades.FieldSellClientOrderId, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSellClientOrderId(); ok {
		_spec.AddField(matchedtrades.FieldSellClientOrderId, field.TypeInt64, value)
	}
	if _u.mutation.SellClientOrderIdCleared() {
		_spec.ClearField(matchedtrades.FieldSellClientOrderId, field.TypeInt64)
	}
	if value, ok := _u.mutation.SellBaseAmount(); ok {
		_spec.SetField(matchedtrades.FieldSellBaseAmount, field.TypeString, value)
	}
	if _u.mutation.SellBaseAmountCleared() {
		_spec.ClearField(matchedtrades.FieldSellBaseAmount, field.TypeString)
	}
	if value, ok := _u.mutation.SellQuoteAmount(); ok {
		_spec.SetField(matchedtrades.FieldSellQuoteAmount, field.TypeString, value)
	}
	if _u.mutation.SellQuoteAmountCleared() {
		_spec.ClearField(matchedtrades.FieldSellQuoteAmount, field.TypeString)
	}
	if value, ok := _u.mutation.SellOrderTimestamp(); ok {
		_spec.SetField(matchedtrades.FieldSellOrderTimestamp, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSellOrderTimestamp(); ok {
		_spec.AddField(matchedtrades.FieldSellOrderTimestamp, field.TypeInt64, value)
	}
	if _u.mutation.SellOrderTimestampCleared() {
		_spec.ClearField(matchedtrades.FieldSellOrderTimestamp, field.TypeInt64)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{matchedtrades.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// MatchedTradesUpdateOne is the builder for updating a single MatchedTrades entity.
type MatchedTradesUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *MatchedTradesMutation
}

// SetStrategyId sets the "strategyId" field.
func (_u *MatchedTradesUpdateOne) SetStrategyId(v string) *MatchedTradesUpdateOne {
	_u.mutation.SetStrategyId(v)
	return _u
}

// SetNillableStrategyId sets the "strategyId" field if the given value is not nil.
func (_u *MatchedTradesUpdateOne) SetNillableStrategyId(v *string) *MatchedTradesUpdateOne {
	if v != nil {
		_u.SetStrategyId(*v)
	}
	return _u
}

// SetPrice sets the "price" field.
func (_u *MatchedTradesUpdateOne) SetPrice(v decimal.Decimal) *MatchedTradesUpdateOne {
	_u.mutation.SetPrice(v)
	return _u
}

// SetNillablePrice sets the "price" field if the given value is not nil.
func (_u *MatchedTradesUpdateOne) SetNillablePrice(v *decimal.Decimal) *MatchedTradesUpdateOne {
	if v != nil {
		_u.SetPrice(*v)
	}
	return _u
}

// SetBuyClientOrderId sets the "buyClientOrderId" field.
func (_u *MatchedTradesUpdateOne) SetBuyClientOrderId(v int64) *MatchedTradesUpdateOne {
	_u.mutation.ResetBuyClientOrderId()
	_u.mutation.SetBuyClientOrderId(v)
	return _u
}

// SetNillableBuyClientOrderId sets the "buyClientOrderId" field if the given value is not nil.
func (_u *MatchedTradesUpdateOne) SetNillableBuyClientOrderId(v *int64) *MatchedTradesUpdateOne {
	if v != nil {
		_u.SetBuyClientOrderId(*v)
	}
	return _u
}

// AddBuyClientOrderId adds value to the "buyClientOrderId" field.
func (_u *MatchedTradesUpdateOne) AddBuyClientOrderId(v int64) *MatchedTradesUpdateOne {
	_u.mutation.AddBuyClientOrderId(v)
	return _u
}

// ClearBuyClientOrderId clears the value of the "buyClientOrderId" field.
func (_u *MatchedTradesUpdateOne) ClearBuyClientOrderId() *MatchedTradesUpdateOne {
	_u.mutation.ClearBuyClientOrderId()
	return _u
}

// SetBuyBaseAmount sets the "buyBaseAmount" field.
func (_u *MatchedTradesUpdateOne) SetBuyBaseAmount(v decimal.Decimal) *MatchedTradesUpdateOne {
	_u.mutation.SetBuyBaseAmount(v)
	return _u
}

// SetNillableBuyBaseAmount sets the "buyBaseAmount" field if the given value is not nil.
func (_u *MatchedTradesUpdateOne) SetNillableBuyBaseAmount(v *decimal.Decimal) *MatchedTradesUpdateOne {
	if v != nil {
		_u.SetBuyBaseAmount(*v)
	}
	return _u
}

// ClearBuyBaseAmount clears the value of the "buyBaseAmount" field.
func (_u *MatchedTradesUpdateOne) ClearBuyBaseAmount() *MatchedTradesUpdateOne {
	_u.mutation.ClearBuyBaseAmount()
	return _u
}

// SetBuyQuoteAmount sets the "buyQuoteAmount" field.
func (_u *MatchedTradesUpdateOne) SetBuyQuoteAmount(v decimal.Decimal) *MatchedTradesUpdateOne {
	_u.mutation.SetBuyQuoteAmount(v)
	return _u
}

// SetNillableBuyQuoteAmount sets the "buyQuoteAmount" field if the given value is not nil.
func (_u *MatchedTradesUpdateOne) SetNillableBuyQuoteAmount(v *decimal.Decimal) *MatchedTradesUpdateOne {
	if v != nil {
		_u.SetBuyQuoteAmount(*v)
	}
	return _u
}

// ClearBuyQuoteAmount clears the value of the "buyQuoteAmount" field.
func (_u *MatchedTradesUpdateOne) ClearBuyQuoteAmount() *MatchedTradesUpdateOne {
	_u.mutation.ClearBuyQuoteAmount()
	return _u
}

// SetBuyOrderTimestamp sets the "buyOrderTimestamp" field.
func (_u *MatchedTradesUpdateOne) SetBuyOrderTimestamp(v int64) *MatchedTradesUpdateOne {
	_u.mutation.ResetBuyOrderTimestamp()
	_u.mutation.SetBuyOrderTimestamp(v)
	return _u
}

// SetNillableBuyOrderTimestamp sets the "buyOrderTimestamp" field if the given value is not nil.
func (_u *MatchedTradesUpdateOne) SetNillableBuyOrderTimestamp(v *int64) *MatchedTradesUpdateOne {
	if v != nil {
		_u.SetBuyOrderTimestamp(*v)
	}
	return _u
}

// AddBuyOrderTimestamp adds value to the "buyOrderTimestamp" field.
func (_u *MatchedTradesUpdateOne) AddBuyOrderTimestamp(v int64) *MatchedTradesUpdateOne {
	_u.mutation.AddBuyOrderTimestamp(v)
	return _u
}

// ClearBuyOrderTimestamp clears the value of the "buyOrderTimestamp" field.
func (_u *MatchedTradesUpdateOne) ClearBuyOrderTimestamp() *MatchedTradesUpdateOne {
	_u.mutation.ClearBuyOrderTimestamp()
	return _u
}

// SetSellClientOrderId sets the "sellClientOrderId" field.
func (_u *MatchedTradesUpdateOne) SetSellClientOrderId(v int64) *MatchedTradesUpdateOne {
	_u.mutation.ResetSellClientOrderId()
	_u.mutation.SetSellClientOrderId(v)
	return _u
}

// SetNillableSellClientOrderId sets the "sellClientOrderId" field if the given value is not nil.
func (_u *MatchedTradesUpdateOne) SetNillableSellClientOrderId(v *int64) *MatchedTradesUpdateOne {
	if v != nil {
		_u.SetSellClientOrderId(*v)
	}
	return _u
}

// AddSellClientOrderId adds value to the "sellClientOrderId" field.
func (_u *MatchedTradesUpdateOne) AddSellClientOrderId(v int64) *MatchedTradesUpdateOne {
	_u.mutation.AddSellClientOrderId(v)
	return _u
}

// ClearSellClientOrderId clears the value of the "sellClientOrderId" field.
func (_u *MatchedTradesUpdateOne) ClearSellClientOrderId() *MatchedTradesUpdateOne {
	_u.mutation.ClearSellClientOrderId()
	return _u
}

// SetSellBaseAmount sets the "sellBaseAmount" field.
func (_u *MatchedTradesUpdateOne) SetSellBaseAmount(v decimal.Decimal) *MatchedTradesUpdateOne {
	_u.mutation.SetSellBaseAmount(v)
	return _u
}

// SetNillableSellBaseAmount sets the "sellBaseAmount" field if the given value is not nil.
func (_u *MatchedTradesUpdateOne) SetNillableSellBaseAmount(v *decimal.Decimal) *MatchedTradesUpdateOne {
	if v != nil {
		_u.SetSellBaseAmount(*v)
	}
	return _u
}

// ClearSellBaseAmount clears the value of the "sellBaseAmount" field.
func (_u *MatchedTradesUpdateOne) ClearSellBaseAmount() *MatchedTradesUpdateOne {
	_u.mutation.ClearSellBaseAmount()
	return _u
}

// SetSellQuoteAmount sets the "sellQuoteAmount" field.
func (_u *MatchedTradesUpdateOne) SetSellQuoteAmount(v decimal.Decimal) *MatchedTradesUpdateOne {
	_u.mutation.SetSellQuoteAmount(v)
	return _u
}

// SetNillableSellQuoteAmount sets the "sellQuoteAmount" field if the given value is not nil.
func (_u *MatchedTradesUpdateOne) SetNillableSellQuoteAmount(v *decimal.Decimal) *MatchedTradesUpdateOne {
	if v != nil {
		_u.SetSellQuoteAmount(*v)
	}
	return _u
}

// ClearSellQuoteAmount clears the value of the "sellQuoteAmount" field.
func (_u *MatchedTradesUpdateOne) ClearSellQuoteAmount() *MatchedTradesUpdateOne {
	_u.mutation.ClearSellQuoteAmount()
	return _u
}

// SetSellOrderTimestamp sets the "sellOrderTimestamp" field.
func (_u *MatchedTradesUpdateOne) SetSellOrderTimestamp(v int64) *MatchedTradesUpdateOne {
	_u.mutation.ResetSellOrderTimestamp()
	_u.mutation.SetSellOrderTimestamp(v)
	return _u
}

// SetNillableSellOrderTimestamp sets the "sellOrderTimestamp" field if the given value is not nil.
func (_u *MatchedTradesUpdateOne) SetNillableSellOrderTimestamp(v *int64) *MatchedTradesUpdateOne {
	if v != nil {
		_u.SetSellOrderTimestamp(*v)
	}
	return _u
}

// AddSellOrderTimestamp adds value to the "sellOrderTimestamp" field.
func (_u *MatchedTradesUpdateOne) AddSellOrderTimestamp(v int64) *MatchedTradesUpdateOne {
	_u.mutation.AddSellOrderTimestamp(v)
	return _u
}

// ClearSellOrderTimestamp clears the value of the "sellOrderTimestamp" field.
func (_u *MatchedTradesUpdateOne) ClearSellOrderTimestamp() *MatchedTradesUpdateOne {
	_u.mutation.ClearSellOrderTimestamp()
	return _u
}

// Mutation returns the MatchedTradesMutation object of the builder.
func (_u *MatchedTradesUpdateOne) Mutation() *MatchedTradesMutation {
	return _u.mutation
}

// Where appends a list predicates to the MatchedTradesUpdate builder.
func (_u *MatchedTradesUpdateOne) Where(ps ...predicate.MatchedTrades) *MatchedTradesUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *MatchedTradesUpdateOne) Select(field string, fields ...string) *MatchedTradesUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated MatchedTrades entity.
func (_u *MatchedTradesUpdateOne) Save(ctx context.Context) (*MatchedTrades, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MatchedTradesUpdateOne) SaveX(ctx context.Context) *MatchedTrades {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *MatchedTradesUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MatchedTradesUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MatchedTradesUpdateOne) check() error {
	if v, ok := _u.mutation.StrategyId(); ok {
		if err := matchedtrades.StrategyIdValidator(v); err != nil {
			return &ValidationError{Name: "strategyId", err: fmt.Errorf(`ent: validator failed for field "MatchedTrades.strategyId": %w`, err)}
		}
	}
	return nil
}

func (_u *MatchedTradesUpdateOne) sqlSave(ctx context.Context) (_node *MatchedTrades, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(matchedtrades.Table, matchedtrades.Columns, sqlgraph.NewFieldSpec(matchedtrades.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "MatchedTrades.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, matchedtrades.FieldID)
		for _, f := range fields {
			if !matchedtrades.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != matchedtrades.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.StrategyId(); ok {
		_spec.SetField(matchedtrades.FieldStrategyId, field.TypeString, value)
	}
	if value, ok := _u.mutation.Price(); ok {
		_spec.SetField(matchedtrades.FieldPrice, field.TypeString, value)
	}
	if value, ok := _u.mutation.BuyClientOrderId(); ok {
		_spec.SetField(matchedtrades.FieldBuyClientOrderId, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedBuyClientOrderId(); ok {
		_spec.AddField(matchedtrades.FieldBuyClientOrderId, field.TypeInt64, value)
	}
	if _u.mutation.BuyClientOrderIdCleared() {
		_spec.ClearField(matchedtrades.FieldBuyClientOrderId, field.TypeInt64)
	}
	if value, ok := _u.mutation.BuyBaseAmount(); ok {
		_spec.SetField(matchedtrades.FieldBuyBaseAmount, field.TypeString, value)
	}
	if _u.mutation.BuyBaseAmountCleared() {
		_spec.ClearField(matchedtrades.FieldBuyBaseAmount, field.TypeString)
	}
	if value, ok := _u.mutation.BuyQuoteAmount(); ok {
		_spec.SetField(matchedtrades.FieldBuyQuoteAmount, field.TypeString, value)
	}
	if _u.mutation.BuyQuoteAmountCleared() {
		_spec.ClearField(matchedtrades.FieldBuyQuoteAmount, field.TypeString)
	}
	if value, ok := _u.mutation.BuyOrderTimestamp(); ok {
		_spec.SetField(matchedtrades.FieldBuyOrderTimestamp, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedBuyOrderTimestamp(); ok {
		_spec.AddField(matchedtrades.FieldBuyOrderTimestamp, field.TypeInt64, value)
	}
	if _u.mutation.BuyOrderTimestampCleared() {
		_spec.ClearField(matchedtrades.FieldBuyOrderTimestamp, field.TypeInt64)
	}
	if value, ok := _u.mutation.SellClientOrderId(); ok {
		_spec.SetField(matchedtrades.FieldSellClientOrderId, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSellClientOrderId(); ok {
		_spec.AddField(matchedtrades.FieldSellClientOrderId, field.TypeInt64, value)
	}
	if _u.mutation.SellClientOrderIdCleared() {
		_spec.ClearField(matchedtrades.FieldSellClientOrderId, field.TypeInt64)
	}
	if value, ok := _u.mutation.SellBaseAmount(); ok {
		_spec.SetField(matchedtrades.FieldSellBaseAmount, field.TypeString, value)
	}
	if _u.mutation.SellBaseAmountCleared() {
		_spec.ClearField(matchedtrades.FieldSellBaseAmount, field.TypeString)
	}
	if value, ok := _u.mutation.SellQuoteAmount(); ok {
		_spec.SetField(matchedtrades.FieldSellQuoteAmount, field.TypeString, value)
	}
	if _u.mutation.SellQuoteAmountCleared() {
		_spec.ClearField(matchedtrades.FieldSellQuoteAmount, field.TypeString)
	}
	if value, ok := _u.mutation.SellOrderTimestamp(); ok {
		_spec.SetField(matchedtrades.FieldSellOrderTimestamp, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSellOrderTimestamp(); ok {
		_spec.AddField(matchedtrades.FieldSellOrderTimestamp, field.TypeInt64, value)
	}
	if _u.mutation.SellOrderTimestampCleared() {
		_spec.ClearField(matchedtrades.FieldSellOrderTimestamp, field.TypeInt64)
	}
	_node = &MatchedTrades{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{matchedtrades.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
