// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/fachebot/perp-dex-grid-bot/internal/ent/matchedtrades"
	"github.com/shopspring/decimal"
)

// MatchedTradesCreate is the builder for creating a MatchedTrades entity.
type MatchedTradesCreate struct {
	config
	mutation *MatchedTradesMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetStrategyId sets the "strategyId" field.
func (_c *MatchedTradesCreate) SetStrategyId(v string) *MatchedTradesCreate {
	_c.mutation.SetStrategyId(v)
	return _c
}

// SetPrice sets the "price" field.
func (_c *MatchedTradesCreate) SetPrice(v decimal.Decimal) *MatchedTradesCreate {
	_c.mutation.SetPrice(v)
	return _c
}

// SetBuyClientOrderId sets the "buyClientOrderId" field.
func (_c *MatchedTradesCreate) SetBuyClientOrderId(v int64) *MatchedTradesCreate {
	_c.mutation.SetBuyClientOrderId(v)
	return _c
}

// SetNillableBuyClientOrderId sets the "buyClientOrderId" field if the given value is not nil.
func (_c *MatchedTradesCreate) SetNillableBuyClientOrderId(v *int64) *MatchedTradesCreate {
	if v != nil {
		_c.SetBuyClientOrderId(*v)
	}
	return _c
}

// SetBuyBaseAmount sets the "buyBaseAmount" field.
func (_c *MatchedTradesCreate) SetBuyBaseAmount(v decimal.Decimal) *MatchedTradesCreate {
	_c.mutation.SetBuyBaseAmount(v)
	return _c
}

// SetNillableBuyBaseAmount sets the "buyBaseAmount" field if the given value is not nil.
func (_c *MatchedTradesCreate) SetNillableBuyBaseAmount(v *decimal.Decimal) *MatchedTradesCreate {
	if v != nil {
		_c.SetBuyBaseAmount(*v)
	}
	return _c
}

// SetBuyQuoteAmount sets the "buyQuoteAmount" field.
func (_c *MatchedTradesCreate) SetBuyQuoteAmount(v decimal.Decimal) *MatchedTradesCreate {
	_c.mutation.SetBuyQuoteAmount(v)
	return _c
}

// SetNillableBuyQuoteAmount sets the "buyQuoteAmount" field if the given value is not nil.
func (_c *MatchedTradesCreate) SetNillableBuyQuoteAmount(v *decimal.Decimal) *MatchedTradesCreate {
	if v != nil {
		_c.SetBuyQuoteAmount(*v)
	}
	return _c
}

// SetBuyOrderTimestamp sets the "buyOrderTimestamp" field.
func (_c *MatchedTradesCreate) SetBuyOrderTimestamp(v int64) *MatchedTradesCreate {
	_c.mutation.SetBuyOrderTimestamp(v)
	return _c
}

// SetNillableBuyOrderTimestamp sets the "buyOrderTimestamp" field if the given value is not nil.
func (_c *MatchedTradesCreate) SetNillableBuyOrderTimestamp(v *int64) *MatchedTradesCreate {
	if v != nil {
		_c.SetBuyOrderTimestamp(*v)
	}
	return _c
}

// SetSellClientOrderId sets the "sellClientOrderId" field.
func (_c *MatchedTradesCreate) SetSellClientOrderId(v int64) *MatchedTradesCreate {
	_c.mutation.SetSellClientOrderId(v)
	return _c
}

// SetNillableSellClientOrderId sets the "sellClientOrderId" field if the given value is not nil.
func (_c *MatchedTradesCreate) SetNillableSellClientOrderId(v *int64) *MatchedTradesCreate {
	if v != nil {
		_c.SetSellClientOrderId(*v)
	}
	return _c
}

// SetSellBaseAmount sets the "sellBaseAmount" field.
func (_c *MatchedTradesCreate) SetSellBaseAmount(v decimal.Decimal) *MatchedTradesCreate {
	_c.mutation.SetSellBaseAmount(v)
	return _c
}

// SetNillableSellBaseAmount sets the "sellBaseAmount" field if the given value is not nil.
func (_c *MatchedTradesCreate) SetNillableSellBaseAmount(v *decimal.Decimal) *MatchedTradesCreate {
	if v != nil {
		_c.SetSellBaseAmount(*v)
	}
	return _c
}

// SetSellQuoteAmount sets the "sellQuoteAmount" field.
func (_c *MatchedTradesCreate) SetSellQuoteAmount(v decimal.Decimal) *MatchedTradesCreate {
	_c.mutation.SetSellQuoteAmount(v)
	return _c
}

// SetNillableSellQuoteAmount sets the "sellQuoteAmount" field if the given value is not nil.
func (_c *MatchedTradesCreate) SetNillableSellQuoteAmount(v *decimal.Decimal) *MatchedTradesCreate {
	if v != nil {
		_c.SetSellQuoteAmount(*v)
	}
	return _c
}

// SetSellOrderTimestamp sets the "sellOrderTimestamp" field.
func (_c *MatchedTradesCreate) SetSellOrderTimestamp(v int64) *MatchedTradesCreate {
	_c.mutation.SetSellOrderTimestamp(v)
	return _c
}

// SetNillableSellOrderTimestamp sets the "sellOrderTimestamp" field if the given value is not nil.
func (_c *MatchedTradesCreate) SetNillableSellOrderTimestamp(v *int64) *MatchedTradesCreate {
	if v != nil {
		_c.SetSellOrderTimestamp(*v)
	}
	return _c
}

// Mutation returns the MatchedTradesMutation object of the builder.
func (_c *MatchedTradesCreate) Mutation() *MatchedTradesMutation {
	return _c.mutation
}

// Save creates the MatchedTrades in the database.
func (_c *MatchedTradesCreate) Save(ctx context.Context) (*MatchedTrades, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *MatchedTradesCreate) SaveX(ctx context.Context) *MatchedTrades {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MatchedTradesCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MatchedTradesCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *MatchedTradesCreate) check() error {
	if _, ok := _c.mutation.StrategyId(); !ok {
		return &ValidationError{Name: "strategyId", err: errors.New(`ent: missing required field "MatchedTrades.strategyId"`)}
	}
	if v, ok := _c.mutation.StrategyId(); ok {
		if err := matchedtrades.StrategyIdValidator(v); err != nil {
			return &ValidationError{Name: "strategyId", err: fmt.Errorf(`ent: validator failed for field "MatchedTrades.strategyId": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Price(); !ok {
		return &ValidationError{Name: "price", err: errors.New(`ent: missing required field "MatchedTrades.price"`)}
	}
	return nil
}

func (_c *MatchedTradesCreate) sqlSave(ctx context.Context) (*MatchedTrades, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *MatchedTradesCreate) createSpec() (*MatchedTrades, *sqlgraph.CreateSpec) {
	var (
		_node = &MatchedTrades{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(matchedtrades.Table, sqlgraph.NewFieldSpec(matchedtrades.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.StrategyId(); ok {
		_spec.SetField(matchedtrades.FieldStrategyId, field.TypeString, value)
		_node.StrategyId = value
	}
	if value, ok := _c.mutation.Price(); ok {
		_spec.SetField(matchedtrades.FieldPrice, field.TypeString, value)
		_node.Price = value
	}
	if value, ok := _c.mutation.BuyClientOrderId(); ok {
		_spec.SetField(matchedtrades.FieldBuyClientOrderId, field.TypeInt64, value)
		_node.BuyClientOrderId = &value
	}
	if value, ok := _c.mutation.BuyBaseAmount(); ok {
		_spec.SetField(matchedtrades.FieldBuyBaseAmount, field.TypeString, value)
		_node.BuyBaseAmount = &value
	}
	if value, ok := _c.mutation.BuyQuoteAmount(); ok {
		_spec.SetField(matchedtrades.FieldBuyQuoteAmount, field.TypeString, value)
		_node.BuyQuoteAmount = &value
	}
	if value, ok := _c.mutation.BuyOrderTimestamp(); ok {
		_spec.SetField(matchedtrades.FieldBuyOrderTimestamp, field.TypeInt64, value)
		_node.BuyOrderTimestamp = &value
	}
	if value, ok := _c.mutation.SellClientOrderId(); ok {
		_spec.SetField(matchedtrades.FieldSellClientOrderId, field.TypeInt64, value)
		_node.SellClientOrderId = &value
	}
	if value, ok := _c.mutation.SellBaseAmount(); ok {
		_spec.SetField(matchedtrades.FieldSellBaseAmount, field.TypeString, value)
		_node.SellBaseAmount = &value
	}
	if value, ok := _c.mutation.SellQuoteAmount(); ok {
		_spec.SetField(matchedtrades.FieldSellQuoteAmount, field.TypeString, value)
		_node.SellQuoteAmount = &value
	}
	if value, ok := _c.mutation.SellOrderTimestamp(); ok {
		_spec.SetField(matchedtrades.FieldSellOrderTimestamp, field.TypeInt64, value)
		_node.SellOrderTimestamp = &value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.MatchedTrades.Create().
//		SetStrategyId(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.MatchedTradesUpsert) {
//			SetStrategyId(v+v).
//		}).
//		Exec(ctx)
func (_c *MatchedTradesCreate) OnConflict(opts ...sql.ConflictOption) *MatchedTradesUpsertOne {
	_c.conflict = opts
	return &MatchedTradesUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.MatchedTrades.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *MatchedTradesCreate) OnConflictColumns(columns ...string) *MatchedTradesUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &MatchedTradesUpsertOne{
		create: _c,
	}
}

type (
	// MatchedTradesUpsertOne is the builder for "upsert"-ing
	//  one MatchedTrades node.
	MatchedTradesUpsertOne struct {
		create *MatchedTradesCreate
	}

	// MatchedTradesUpsert is the "OnConflict" setter.
	MatchedTradesUpsert struct {
		*sql.UpdateSet
	}
)

// SetStrategyId sets the "strategyId" field.
func (u *MatchedTradesUpsert) SetStrategyId(v string) *MatchedTradesUpsert {
	u.Set(matchedtrades.FieldStrategyId, v)
	return u
}

// UpdateStrategyId sets the "strategyId" field to the value that was provided on create.
func (u *MatchedTradesUpsert) UpdateStrategyId() *MatchedTradesUpsert {
	u.SetExcluded(matchedtrades.FieldStrategyId)
	return u
}

// SetPrice sets the "price" field.
func (u *MatchedTradesUpsert) SetPrice(v decimal.Decimal) *MatchedTradesUpsert {
	u.Set(matchedtrades.FieldPrice, v)
	return u
}

// UpdatePrice sets the "price" field to the value that was provided on create.
func (u *MatchedTradesUpsert) UpdatePrice() *MatchedTradesUpsert {
	u.SetExcluded(matchedtrades.FieldPrice)
	return u
}

// SetBuyClientOrderId sets the "buyClientOrderId" field.
func (u *MatchedTradesUpsert) SetBuyClientOrderId(v int64) *MatchedTradesUpsert {
	u.Set(matchedtrades.FieldBuyClientOrderId, v)
	return u
}

// UpdateBuyClientOrderId sets the "buyClientOrderId" field to the value that was provided on create.
func (u *MatchedTradesUpsert) UpdateBuyClientOrderId() *MatchedTradesUpsert {
	u.SetExcluded(matchedtrades.FieldBuyClientOrderId)
	return u
}

// AddBuyClientOrderId adds v to the "buyClientOrderId" field.
func (u *MatchedTradesUpsert) AddBuyClientOrderId(v int64) *MatchedTradesUpsert {
	u.Add(matchedtrades.FieldBuyClientOrderId, v)
	return u
}

// ClearBuyClientOrderId clears the value of the "buyClientOrderId" field.
func (u *MatchedTradesUpsert) ClearBuyClientOrderId() *MatchedTradesUpsert {
	u.SetNull(matchedtrades.FieldBuyClientOrderId)
	return u
}

// SetBuyBaseAmount sets the "buyBaseAmount" field.
func (u *MatchedTradesUpsert) SetBuyBaseAmount(v decimal.Decimal) *MatchedTradesUpsert {
	u.Set(matchedtrades.FieldBuyBaseAmount, v)
	return u
}

// UpdateBuyBaseAmount sets the "buyBaseAmount" field to the value that was provided on create.
func (u *MatchedTradesUpsert) UpdateBuyBaseAmount() *MatchedTradesUpsert {
	u.SetExcluded(matchedtrades.FieldBuyBaseAmount)
	return u
}

// ClearBuyBaseAmount clears the value of the "buyBaseAmount" field.
func (u *MatchedTradesUpsert) ClearBuyBaseAmount() *MatchedTradesUpsert {
	u.SetNull(matchedtrades.FieldBuyBaseAmount)
	return u
}

// SetBuyQuoteAmount sets the "buyQuoteAmount" field.
func (u *MatchedTradesUpsert) SetBuyQuoteAmount(v decimal.Decimal) *MatchedTradesUpsert {
	u.Set(matchedtrades.FieldBuyQuoteAmount, v)
	return u
}

// UpdateBuyQuoteAmount sets the "buyQuoteAmount" field to the value that was provided on create.
func (u *MatchedTradesUpsert) UpdateBuyQuoteAmount() *MatchedTradesUpsert {
	u.SetExcluded(matchedtrades.FieldBuyQuoteAmount)
	return u
}

// ClearBuyQuoteAmount clears the value of the "buyQuoteAmount" field.
func (u *MatchedTradesUpsert) ClearBuyQuoteAmount() *MatchedTradesUpsert {
	u.SetNull(matchedtrades.FieldBuyQuoteAmount)
	return u
}

// SetBuyOrderTimestamp sets the "buyOrderTimestamp" field.
func (u *MatchedTradesUpsert) SetBuyOrderTimestamp(v int64) *MatchedTradesUpsert {
	u.Set(matchedtrades.FieldBuyOrderTimestamp, v)
	return u
}

// UpdateBuyOrderTimestamp sets the "buyOrderTimestamp" field to the value that was provided on create.
func (u *MatchedTradesUpsert) UpdateBuyOrderTimestamp() *MatchedTradesUpsert {
	u.SetExcluded(matchedtrades.FieldBuyOrderTimestamp)
	return u
}

// AddBuyOrderTimestamp adds v to the "buyOrderTimestamp" field.
func (u *MatchedTradesUpsert) AddBuyOrderTimestamp(v int64) *MatchedTradesUpsert {
	u.Add(matchedtrades.FieldBuyOrderTimestamp, v)
	return u
}

// ClearBuyOrderTimestamp clears the value of the "buyOrderTimestamp" field.
func (u *MatchedTradesUpsert) ClearBuyOrderTimestamp() *MatchedTradesUpsert {
	u.SetNull(matchedtrades.FieldBuyOrderTimestamp)
	return u
}

// SetSellClientOrderId sets the "sellClientOrderId" field.
func (u *MatchedTradesUpsert) SetSellClientOrderId(v int64) *MatchedTradesUpsert {
	u.Set(matchedtrades.FieldSellClientOrderId, v)
	return u
}

// UpdateSellClientOrderId sets the "sellClientOrderId" field to the value that was provided on create.
func (u *MatchedTradesUpsert) UpdateSellClientOrderId() *MatchedTradesUpsert {
	u.SetExcluded(matchedtrades.FieldSellClientOrderId)
	return u
}

// AddSellClientOrderId adds v to the "sellClientOrderId" field.
func (u *MatchedTradesUpsert) AddSellClientOrderId(v int64) *MatchedTradesUpsert {
	u.Add(matchedtrades.FieldSellClientOrderId, v)
	return u
}

// ClearSellClientOrderId clears the value of the "sellClientOrderId" field.
func (u *MatchedTradesUpsert) ClearSellClientOrderId() *MatchedTradesUpsert {
	u.SetNull(matchedtrades.FieldSellClientOrderId)
	return u
}

// SetSellBaseAmount sets the "sellBaseAmount" field.
func (u *MatchedTradesUpsert) SetSellBaseAmount(v decimal.Decimal) *MatchedTradesUpsert {
	u.Set(matchedtrades.FieldSellBaseAmount, v)
	return u
}

// UpdateSellBaseAmount sets the "sellBaseAmount" field to the value that was provided on create.
func (u *MatchedTradesUpsert) UpdateSellBaseAmount() *MatchedTradesUpsert {
	u.SetExcluded(matchedtrades.FieldSellBaseAmount)
	return u
}

// ClearSellBaseAmount clears the value of the "sellBaseAmount" field.
func (u *MatchedTradesUpsert) ClearSellBaseAmount() *MatchedTradesUpsert {
	u.SetNull(matchedtrades.FieldSellBaseAmount)
	return u
}

// SetSellQuoteAmount sets the "sellQuoteAmount" field.
func (u *MatchedTradesUpsert) SetSellQuoteAmount(v decimal.Decimal) *MatchedTradesUpsert {
	u.Set(matchedtrades.FieldSellQuoteAmount, v)
	return u
}

// UpdateSellQuoteAmount sets the "sellQuoteAmount" field to the value that was provided on create.
func (u *MatchedTradesUpsert) UpdateSellQuoteAmount() *MatchedTradesUpsert {
	u.SetExcluded(matchedtrades.FieldSellQuoteAmount)
	return u
}

// ClearSellQuoteAmount clears the value of the "sellQuoteAmount" field.
func (u *MatchedTradesUpsert) ClearSellQuoteAmount() *MatchedTradesUpsert {
	u.SetNull(matchedtrades.FieldSellQuoteAmount)
	return u
}

// SetSellOrderTimestamp sets the "sellOrderTimestamp" field.
func (u *MatchedTradesUpsert) SetSellOrderTimestamp(v int64) *MatchedTradesUpsert {
	u.Set(matchedtrades.FieldSellOrderTimestamp, v)
	return u
}

// UpdateSellOrderTimestamp sets the "sellOrderTimestamp" field to the value that was provided on create.
func (u *MatchedTradesUpsert) UpdateSellOrderTimestamp() *MatchedTradesUpsert {
	u.SetExcluded(matchedtrades.FieldSellOrderTimestamp)
	return u
}

// AddSellOrderTimestamp adds v to the "sellOrderTimestamp" field.
func (u *MatchedTradesUpsert) AddSellOrderTimestamp(v int64) *MatchedTradesUpsert {
	u.Add(matchedtrades.FieldSellOrderTimestamp, v)
	return u
}

// ClearSellOrderTimestamp clears the value of the "sellOrderTimestamp" field.
func (u *MatchedTradesUpsert) ClearSellOrderTimestamp() *MatchedTradesUpsert {
	u.SetNull(matchedtrades.FieldSellOrderTimestamp)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.MatchedTrades.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *MatchedTradesUpsertOne) UpdateNewValues() *MatchedTradesUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.MatchedTrades.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *MatchedTradesUpsertOne) Ignore() *MatchedTradesUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *MatchedTradesUpsertOne) DoNothing() *MatchedTradesUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the MatchedTradesCreate.OnConflict
// documentation for more info.
func (u *MatchedTradesUpsertOne) Update(set func(*MatchedTradesUpsert)) *MatchedTradesUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&MatchedTradesUpsert{UpdateSet: update})
	}))
	return u
}

// SetStrategyId sets the "strategyId" field.
func (u *MatchedTradesUpsertOne) SetStrategyId(v string) *MatchedTradesUpsertOne {
	return u.Update(func(s *MatchedTradesUpsert) {
		s.SetStrategyId(v)
	})
}

// UpdateStrategyId sets the "strategyId" field to the value that was provided on create.
func (u *MatchedTradesUpsertOne) UpdateStrategyId() *MatchedTradesUpsertOne {
	return u.Update(func(s *MatchedTradesUpsert) {
		s.UpdateStrategyId()
	})
}

// SetPrice sets the "price" field.
func (u *MatchedTradesUpsertOne) SetPrice(v decimal.Decimal) *MatchedTradesUpsertOne {
	return u.Update(func(s *MatchedTradesUpsert) {
		s.SetPrice(v)
	})
}

// UpdatePrice sets the "price" field to the value that was provided on create.
func (u *MatchedTradesUpsertOne) UpdatePrice() *MatchedTradesUpsertOne {
	return u.Update(func(s *MatchedTradesUpsert) {
		s.UpdatePrice()
	})
}

// SetBuyClientOrderId sets the "buyClientOrderId" field.
func (u *MatchedTradesUpsertOne) SetBuyClientOrderId(v int64) *MatchedTradesUpsertOne {
	return u.Update(func(s *MatchedTradesUpsert) {
		s.SetBuyClientOrderId(v)
	})
}

// AddBuyClientOrderId adds v to the "buyClientOrderId" field.
func (u *MatchedTradesUpsertOne) AddBuyClientOrderId(v int64) *MatchedTradesUpsertOne {
	return u.Update(func(s *MatchedTradesUpsert) {
		s.AddBuyClientOrderId(v)
	})
}

// UpdateBuyClientOrderId sets the "buyClientOrderId" field to the value that was provided on create.
func (u *MatchedTradesUpsertOne) UpdateBuyClientOrderId() *MatchedTradesUpsertOne {
	return u.Update(func(s *MatchedTradesUpsert) {
		s.UpdateBuyClientOrderId()
	})
}

// ClearBuyClientOrderId clears the value of the "buyClientOrderId" field.
func (u *MatchedTradesUpsertOne) ClearBuyClientOrderId() *MatchedTradesUpsertOne {
	return u.Update(func(s *MatchedTradesUpsert) {
		s.ClearBuyClientOrderId()
	})
}

// SetBuyBaseAmount sets the "buyBaseAmount" field.
func (u *MatchedTradesUpsertOne) SetBuyBaseAmount(v decimal.Decimal) *MatchedTradesUpsertOne {
	return u.Update(func(s *MatchedTradesUpsert) {
		s.SetBuyBaseAmount(v)
	})
}

// UpdateBuyBaseAmount sets the "buyBaseAmount" field to the value that was provided on create.
func (u *MatchedTradesUpsertOne) UpdateBuyBaseAmount() *MatchedTradesUpsertOne {
	return u.Update(func(s *MatchedTradesUpsert) {
		s.UpdateBuyBaseAmount()
	})
}

// ClearBuyBaseAmount clears the value of the "buyBaseAmount" field.
func (u *MatchedTradesUpsertOne) ClearBuyBaseAmount() *MatchedTradesUpsertOne {
	return u.Update(func(s *MatchedTradesUpsert) {
		s.ClearBuyBaseAmount()
	})
}

// SetBuyQuoteAmount sets the "buyQuoteAmount" field.
func (u *MatchedTradesUpsertOne) SetBuyQuoteAmount(v decimal.Decimal) *MatchedTradesUpsertOne {
	return u.Update(func(s *MatchedTradesUpsert) {
		s.SetBuyQuoteAmount(v)
	})
}

// UpdateBuyQuoteAmount sets the "buyQuoteAmount" field to the value that was provided on create.
func (u *MatchedTradesUpsertOne) UpdateBuyQuoteAmount() *MatchedTradesUpsertOne {
	return u.Update(func(s *MatchedTradesUpsert) {
		s.UpdateBuyQuoteAmount()
	})
}

// ClearBuyQuoteAmount clears the value of the "buyQuoteAmount" field.
func (u *MatchedTradesUpsertOne) ClearBuyQuoteAmount() *MatchedTradesUpsertOne {
	return u.Update(func(s *MatchedTradesUpsert) {
		s.ClearBuyQuoteAmount()
	})
}

// SetBuyOrderTimestamp sets the "buyOrderTimestamp" field.
func (u *MatchedTradesUpsertOne) SetBuyOrderTimestamp(v int64) *MatchedTradesUpsertOne {
	return u.Update(func(s *MatchedTradesUpsert) {
		s.SetBuyOrderTimestamp(v)
	})
}

// AddBuyOrderTimestamp adds v to the "buyOrderTimestamp" field.
func (u *MatchedTradesUpsertOne) AddBuyOrderTimestamp(v int64) *MatchedTradesUpsertOne {
	return u.Update(func(s *MatchedTradesUpsert) {
		s.AddBuyOrderTimestamp(v)
	})
}

// UpdateBuyOrderTimestamp sets the "buyOrderTimestamp" field to the value that was provided on create.
func (u *MatchedTradesUpsertOne) UpdateBuyOrderTimestamp() *MatchedTradesUpsertOne {
	return u.Update(func(s *MatchedTradesUpsert) {
		s.UpdateBuyOrderTimestamp()
	})
}

// ClearBuyOrderTimestamp clears the value of the "buyOrderTimestamp" field.
func (u *MatchedTradesUpsertOne) ClearBuyOrderTimestamp() *MatchedTradesUpsertOne {
	return u.Update(func(s *MatchedTradesUpsert) {
		s.ClearBuyOrderTimestamp()
	})
}

// SetSellClientOrderId sets the "sellClientOrderId" field.
func (u *MatchedTradesUpsertOne) SetSellClientOrderId(v int64) *MatchedTradesUpsertOne {
	return u.Update(func(s *MatchedTradesUpsert) {
		s.SetSellClientOrderId(v)
	})
}

// AddSellClientOrderId adds v to the "sellClientOrderId" field.
func (u *MatchedTradesUpsertOne) AddSellClientOrderId(v int64) *MatchedTradesUpsertOne {
	return u.Update(func(s *MatchedTradesUpsert) {
		s.AddSellClientOrderId(v)
	})
}

// UpdateSellClientOrderId sets the "sellClientOrderId" field to the value that was provided on create.
func (u *MatchedTradesUpsertOne) UpdateSellClientOrderId() *MatchedTradesUpsertOne {
	return u.Update(func(s *MatchedTradesUpsert) {
		s.UpdateSellClientOrderId()
	})
}

// ClearSellClientOrderId clears the value of the "sellClientOrderId" field.
func (u *MatchedTradesUpsertOne) ClearSellClientOrderId() *MatchedTradesUpsertOne {
	return u.Update(func(s *MatchedTradesUpsert) {
		s.ClearSellClientOrderId()
	})
}

// SetSellBaseAmount sets the "sellBaseAmount" field.
func (u *MatchedTradesUpsertOne) SetSellBaseAmount(v decimal.Decimal) *MatchedTradesUpsertOne {
	return u.Update(func(s *MatchedTradesUpsert) {
		s.SetSellBaseAmount(v)
	})
}

// UpdateSellBaseAmount sets the "sellBaseAmount" field to the value that was provided on create.
func (u *MatchedTradesUpsertOne) UpdateSellBaseAmount() *MatchedTradesUpsertOne {
	return u.Update(func(s *MatchedTradesUpsert) {
		s.UpdateSellBaseAmount()
	})
}

// ClearSellBaseAmount clears the value of the "sellBaseAmount" field.
func (u *MatchedTradesUpsertOne) ClearSellBaseAmount() *MatchedTradesUpsertOne {
	return u.Update(func(s *MatchedTradesUpsert) {
		s.ClearSellBaseAmount()
	})
}

// SetSellQuoteAmount sets the "sellQuoteAmount" field.
func (u *MatchedTradesUpsertOne) SetSellQuoteAmount(v decimal.Decimal) *MatchedTradesUpsertOne {
	return u.Update(func(s *MatchedTradesUpsert) {
		s.SetSellQuoteAmount(v)
	})
}

// UpdateSellQuoteAmount sets the "sellQuoteAmount" field to the value that was provided on create.
func (u *MatchedTradesUpsertOne) UpdateSellQuoteAmount() *MatchedTradesUpsertOne {
	return u.Update(func(s *MatchedTradesUpsert) {
		s.UpdateSellQuoteAmount()
	})
}

// ClearSellQuoteAmount clears the value of the "sellQuoteAmount" field.
func (u *MatchedTradesUpsertOne) ClearSellQuoteAmount() *MatchedTradesUpsertOne {
	return u.Update(func(s *MatchedTradesUpsert) {
		s.ClearSellQuoteAmount()
	})
}

// SetSellOrderTimestamp sets the "sellOrderTimestamp" field.
func (u *MatchedTradesUpsertOne) SetSellOrderTimestamp(v int64) *MatchedTradesUpsertOne {
	return u.Update(func(s *MatchedTradesUpsert) {
		s.SetSellOrderTimestamp(v)
	})
}

// AddSellOrderTimestamp adds v to the "sellOrderTimestamp" field.
func (u *MatchedTradesUpsertOne) AddSellOrderTimestamp(v int64) *MatchedTradesUpsertOne {
	return u.Update(func(s *MatchedTradesUpsert) {
		s.AddSellOrderTimestamp(v)
	})
}

// UpdateSellOrderTimestamp sets the "sellOrderTimestamp" field to the value that was provided on create.
func (u *MatchedTradesUpsertOne) UpdateSellOrderTimestamp() *MatchedTradesUpsertOne {
	return u.Update(func(s *MatchedTradesUpsert) {
		s.UpdateSellOrderTimestamp()
	})
}

// ClearSellOrderTimestamp clears the value of the "sellOrderTimestamp" field.
func (u *MatchedTradesUpsertOne) ClearSellOrderTimestamp() *MatchedTradesUpsertOne {
	return u.Update(func(s *MatchedTradesUpsert) {
		s.ClearSellOrderTimestamp()
	})
}

// Exec executes the query.
func (u *MatchedTradesUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for MatchedTradesCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *MatchedTradesUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *MatchedTradesUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *MatchedTradesUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// MatchedTradesCreateBulk is the builder for creating many MatchedTrades entities in bulk.
type MatchedTradesCreateBulk struct {
	config
	err      error
	builders []*MatchedTradesCreate
	conflict []sql.ConflictOption
}

// Save creates the MatchedTrades entities in the database.
func (_c *MatchedTradesCreateBulk) Save(ctx context.Context) ([]*MatchedTrades, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*MatchedTrades, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MatchedTradesMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *MatchedTradesCreateBulk) SaveX(ctx context.Context) []*MatchedTrades {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MatchedTradesCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MatchedTradesCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.MatchedTrades.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.MatchedTradesUpsert) {
//			SetStrategyId(v+v).
//		}).
//		Exec(ctx)
func (_c *MatchedTradesCreateBulk) OnConflict(opts ...sql.ConflictOption) *MatchedTradesUpsertBulk {
	_c.conflict = opts
	return &MatchedTradesUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.MatchedTrades.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *MatchedTradesCreateBulk) OnConflictColumns(columns ...string) *MatchedTradesUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &MatchedTradesUpsertBulk{
		create: _c,
	}
}

// MatchedTradesUpsertBulk is the builder for "upsert"-ing
// a bulk of MatchedTrades nodes.
type MatchedTradesUpsertBulk struct {
	create *MatchedTradesCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.MatchedTrades.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *MatchedTradesUpsertBulk) UpdateNewValues() *MatchedTradesUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.MatchedTrades.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *MatchedTradesUpsertBulk) Ignore() *MatchedTradesUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *MatchedTradesUpsertBulk) DoNothing() *MatchedTradesUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the MatchedTradesCreateBulk.OnConflict
// documentation for more info.
func (u *MatchedTradesUpsertBulk) Update(set func(*MatchedTradesUpsert)) *MatchedTradesUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&MatchedTradesUpsert{UpdateSet: update})
	}))
	return u
}

// SetStrategyId sets the "strategyId" field.
func (u *MatchedTradesUpsertBulk) SetStrategyId(v string) *MatchedTradesUpsertBulk {
	return u.Update(func(s *MatchedTradesUpsert) {
		s.SetStrategyId(v)
	})
}

// UpdateStrategyId sets the "strategyId" field to the value that was provided on create.
func (u *MatchedTradesUpsertBulk) UpdateStrategyId() *MatchedTradesUpsertBulk {
	return u.Update(func(s *MatchedTradesUpsert) {
		s.UpdateStrategyId()
	})
}

// SetPrice sets the "price" field.
func (u *MatchedTradesUpsertBulk) SetPrice(v decimal.Decimal) *MatchedTradesUpsertBulk {
	return u.Update(func(s *MatchedTradesUpsert) {
		s.SetPrice(v)
	})
}

// UpdatePrice sets the "price" field to the value that was provided on create.
func (u *MatchedTradesUpsertBulk) UpdatePrice() *MatchedTradesUpsertBulk {
	return u.Update(func(s *MatchedTradesUpsert) {
		s.UpdatePrice()
	})
}

// SetBuyClientOrderId sets the "buyClientOrderId" field.
func (u *MatchedTradesUpsertBulk) SetBuyClientOrderId(v int64) *MatchedTradesUpsertBulk {
	return u.Update(func(s *MatchedTradesUpsert) {
		s.SetBuyClientOrderId(v)
	})
}

// AddBuyClientOrderId adds v to the "buyClientOrderId" field.
func (u *MatchedTradesUpsertBulk) AddBuyClientOrderId(v int64) *MatchedTradesUpsertBulk {
	return u.Update(func(s *MatchedTradesUpsert) {
		s.AddBuyClientOrderId(v)
	})
}

// UpdateBuyClientOrderId sets the "buyClientOrderId" field to the value that was provided on create.
func (u *MatchedTradesUpsertBulk) UpdateBuyClientOrderId() *MatchedTradesUpsertBulk {
	return u.Update(func(s *MatchedTradesUpsert) {
		s.UpdateBuyClientOrderId()
	})
}

// ClearBuyClientOrderId clears the value of the "buyClientOrderId" field.
func (u *MatchedTradesUpsertBulk) ClearBuyClientOrderId() *MatchedTradesUpsertBulk {
	return u.Update(func(s *MatchedTradesUpsert) {
		s.ClearBuyClientOrderId()
	})
}

// SetBuyBaseAmount sets the "buyBaseAmount" field.
func (u *MatchedTradesUpsertBulk) SetBuyBaseAmount(v decimal.Decimal) *MatchedTradesUpsertBulk {
	return u.Update(func(s *MatchedTradesUpsert) {
		s.SetBuyBaseAmount(v)
	})
}

// UpdateBuyBaseAmount sets the "buyBaseAmount" field to the value that was provided on create.
func (u *MatchedTradesUpsertBulk) UpdateBuyBaseAmount() *MatchedTradesUpsertBulk {
	return u.Update(func(s *MatchedTradesUpsert) {
		s.UpdateBuyBaseAmount()
	})
}

// ClearBuyBaseAmount clears the value of the "buyBaseAmount" field.
func (u *MatchedTradesUpsertBulk) ClearBuyBaseAmount() *MatchedTradesUpsertBulk {
	return u.Update(func(s *MatchedTradesUpsert) {
		s.ClearBuyBaseAmount()
	})
}

// SetBuyQuoteAmount sets the "buyQuoteAmount" field.
func (u *MatchedTradesUpsertBulk) SetBuyQuoteAmount(v decimal.Decimal) *MatchedTradesUpsertBulk {
	return u.Update(func(s *MatchedTradesUpsert) {
		s.SetBuyQuoteAmount(v)
	})
}

// UpdateBuyQuoteAmount sets the "buyQuoteAmount" field to the value that was provided on create.
func (u *MatchedTradesUpsertBulk) UpdateBuyQuoteAmount() *MatchedTradesUpsertBulk {
	return u.Update(func(s *MatchedTradesUpsert) {
		s.UpdateBuyQuoteAmount()
	})
}

// ClearBuyQuoteAmount clears the value of the "buyQuoteAmount" field.
func (u *MatchedTradesUpsertBulk) ClearBuyQuoteAmount() *MatchedTradesUpsertBulk {
	return u.Update(func(s *MatchedTradesUpsert) {
		s.ClearBuyQuoteAmount()
	})
}

// SetBuyOrderTimestamp sets the "buyOrderTimestamp" field.
func (u *MatchedTradesUpsertBulk) SetBuyOrderTimestamp(v int64) *MatchedTradesUpsertBulk {
	return u.Update(func(s *MatchedTradesUpsert) {
		s.SetBuyOrderTimestamp(v)
	})
}

// AddBuyOrderTimestamp adds v to the "buyOrderTimestamp" field.
func (u *MatchedTradesUpsertBulk) AddBuyOrderTimestamp(v int64) *MatchedTradesUpsertBulk {
	return u.Update(func(s *MatchedTradesUpsert) {
		s.AddBuyOrderTimestamp(v)
	})
}

// UpdateBuyOrderTimestamp sets the "buyOrderTimestamp" field to the value that was provided on create.
func (u *MatchedTradesUpsertBulk) UpdateBuyOrderTimestamp() *MatchedTradesUpsertBulk {
	return u.Update(func(s *MatchedTradesUpsert) {
		s.UpdateBuyOrderTimestamp()
	})
}

// ClearBuyOrderTimestamp clears the value of the "buyOrderTimestamp" field.
func (u *MatchedTradesUpsertBulk) ClearBuyOrderTimestamp() *MatchedTradesUpsertBulk {
	return u.Update(func(s *MatchedTradesUpsert) {
		s.ClearBuyOrderTimestamp()
	})
}

// SetSellClientOrderId sets the "sellClientOrderId" field.
func (u *MatchedTradesUpsertBulk) SetSellClientOrderId(v int64) *MatchedTradesUpsertBulk {
	return u.Update(func(s *MatchedTradesUpsert) {
		s.SetSellClientOrderId(v)
	})
}

// AddSellClientOrderId adds v to the "sellClientOrderId" field.
func (u *MatchedTradesUpsertBulk) AddSellClientOrderId(v int64) *MatchedTradesUpsertBulk {
	return u.Update(func(s *MatchedTradesUpsert) {
		s.AddSellClientOrderId(v)
	})
}

// UpdateSellClientOrderId sets the "sellClientOrderId" field to the value that was provided on create.
func (u *MatchedTradesUpsertBulk) UpdateSellClientOrderId() *MatchedTradesUpsertBulk {
	return u.Update(func(s *MatchedTradesUpsert) {
		s.UpdateSellClientOrderId()
	})
}

// ClearSellClientOrderId clears the value of the "sellClientOrderId" field.
func (u *MatchedTradesUpsertBulk) ClearSellClientOrderId() *MatchedTradesUpsertBulk {
	return u.Update(func(s *MatchedTradesUpsert) {
		s.ClearSellClientOrderId()
	})
}

// SetSellBaseAmount sets the "sellBaseAmount" field.
func (u *MatchedTradesUpsertBulk) SetSellBaseAmount(v decimal.Decimal) *MatchedTradesUpsertBulk {
	return u.Update(func(s *MatchedTradesUpsert) {
		s.SetSellBaseAmount(v)
	})
}

// UpdateSellBaseAmount sets the "sellBaseAmount" field to the value that was provided on create.
func (u *MatchedTradesUpsertBulk) UpdateSellBaseAmount() *MatchedTradesUpsertBulk {
	return u.Update(func(s *MatchedTradesUpsert) {
		s.UpdateSellBaseAmount()
	})
}

// ClearSellBaseAmount clears the value of the "sellBaseAmount" field.
func (u *MatchedTradesUpsertBulk) ClearSellBaseAmount() *MatchedTradesUpsertBulk {
	return u.Update(func(s *MatchedTradesUpsert) {
		s.ClearSellBaseAmount()
	})
}

// SetSellQuoteAmount sets the "sellQuoteAmount" field.
func (u *MatchedTradesUpsertBulk) SetSellQuoteAmount(v decimal.Decimal) *MatchedTradesUpsertBulk {
	return u.Update(func(s *MatchedTradesUpsert) {
		s.SetSellQuoteAmount(v)
	})
}

// UpdateSellQuoteAmount sets the "sellQuoteAmount" field to the value that was provided on create.
func (u *MatchedTradesUpsertBulk) UpdateSellQuoteAmount() *MatchedTradesUpsertBulk {
	return u.Update(func(s *MatchedTradesUpsert) {
		s.UpdateSellQuoteAmount()
	})
}

// ClearSellQuoteAmount clears the value of the "sellQuoteAmount" field.
func (u *MatchedTradesUpsertBulk) ClearSellQuoteAmount() *MatchedTradesUpsertBulk {
	return u.Update(func(s *MatchedTradesUpsert) {
		s.ClearSellQuoteAmount()
	})
}

// SetSellOrderTimestamp sets the "sellOrderTimestamp" field.
func (u *MatchedTradesUpsertBulk) SetSellOrderTimestamp(v int64) *MatchedTradesUpsertBulk {
	return u.Update(func(s *MatchedTradesUpsert) {
		s.SetSellOrderTimestamp(v)
	})
}

// AddSellOrderTimestamp adds v to the "sellOrderTimestamp" field.
func (u *MatchedTradesUpsertBulk) AddSellOrderTimestamp(v int64) *MatchedTradesUpsertBulk {
	return u.Update(func(s *MatchedTradesUpsert) {
		s.AddSellOrderTimestamp(v)
	})
}

// UpdateSellOrderTimestamp sets the "sellOrderTimestamp" field to the value that was provided on create.
func (u *MatchedTradesUpsertBulk) UpdateSellOrderTimestamp() *MatchedTradesUpsertBulk {
	return u.Update(func(s *MatchedTradesUpsert) {
		s.UpdateSellOrderTimestamp()
	})
}

// ClearSellOrderTimestamp clears the value of the "sellOrderTimestamp" field.
func (u *MatchedTradesUpsertBulk) ClearSellOrderTimestamp() *MatchedTradesUpsertBulk {
	return u.Update(func(s *MatchedTradesUpsert) {
		s.ClearSellOrderTimestamp()
	})
}

// Exec executes the query.
func (u *MatchedTradesUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the MatchedTradesCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for MatchedTradesCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *MatchedTradesUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
