// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/fachebot/omni-grid-bot/internal/ent/matchedtrade"
	"github.com/fachebot/omni-grid-bot/internal/ent/predicate"
)

// MatchedTradeDelete is the builder for deleting a MatchedTrade entity.
type MatchedTradeDelete struct {
	config
	hooks    []Hook
	mutation *MatchedTradeMutation
}

// Where appends a list predicates to the MatchedTradeDelete builder.
func (_d *MatchedTradeDelete) Where(ps ...predicate.MatchedTrade) *MatchedTradeDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *MatchedTradeDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *MatchedTradeDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *MatchedTradeDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(matchedtrade.Table, sqlgraph.NewFieldSpec(matchedtrade.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// MatchedTradeDeleteOne is the builder for deleting a single MatchedTrade entity.
type MatchedTradeDeleteOne struct {
	_d *MatchedTradeDelete
}

// Where appends a list predicates to the MatchedTradeDelete builder.
func (_d *MatchedTradeDeleteOne) Where(ps ...predicate.MatchedTrade) *MatchedTradeDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *MatchedTradeDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{matchedtrade.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *MatchedTradeDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
