// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/fachebot/perp-dex-grid-bot/internal/ent/order"
	"github.com/fachebot/perp-dex-grid-bot/internal/ent/predicate"
	"github.com/shopspring/decimal"
)

// OrderUpdate is the builder for updating Order entities.
type OrderUpdate struct {
	config
	hooks    []Hook
	mutation *OrderMutation
}

// Where appends a list predicates to the OrderUpdate builder.
func (_u *OrderUpdate) Where(ps ...predicate.Order) *OrderUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdateTime sets the "update_time" field.
func (_u *OrderUpdate) SetUpdateTime(v time.Time) *OrderUpdate {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetExchange sets the "exchange" field.
func (_u *OrderUpdate) SetExchange(v string) *OrderUpdate {
	_u.mutation.SetExchange(v)
	return _u
}

// SetNillableExchange sets the "exchange" field if the given value is not nil.
func (_u *OrderUpdate) SetNillableExchange(v *string) *OrderUpdate {
	if v != nil {
		_u.SetExchange(*v)
	}
	return _u
}

// SetAccount sets the "account" field.
func (_u *OrderUpdate) SetAccount(v string) *OrderUpdate {
	_u.mutation.SetAccount(v)
	return _u
}

// SetNillableAccount sets the "account" field if the given value is not nil.
func (_u *OrderUpdate) SetNillableAccount(v *string) *OrderUpdate {
	if v != nil {
		_u.SetAccount(*v)
	}
	return _u
}

// SetSymbol sets the "symbol" field.
func (_u *OrderUpdate) SetSymbol(v string) *OrderUpdate {
	_u.mutation.SetSymbol(v)
	return _u
}

// SetNillableSymbol sets the "symbol" field if the given value is not nil.
func (_u *OrderUpdate) SetNillableSymbol(v *string) *OrderUpdate {
	if v != nil {
		_u.SetSymbol(*v)
	}
	return _u
}

// SetOrderID sets the "order_id" field.
func (_u *OrderUpdate) SetOrderID(v int64) *OrderUpdate {
	_u.mutation.ResetOrderID()
	_u.mutation.SetOrderID(v)
	return _u
}

// SetNillableOrderID sets the "order_id" field if the given value is not nil.
func (_u *OrderUpdate) SetNillableOrderID(v *int64) *OrderUpdate {
	if v != nil {
		_u.SetOrderID(*v)
	}
	return _u
}

// AddOrderID adds value to the "order_id" field.
func (_u *OrderUpdate) AddOrderID(v int64) *OrderUpdate {
	_u.mutation.AddOrderID(v)
	return _u
}

// SetClientOrderID sets the "client_order_id" field.
func (_u *OrderUpdate) SetClientOrderID(v int64) *OrderUpdate {
	_u.mutation.ResetClientOrderID()
	_u.mutation.SetClientOrderID(v)
	return _u
}

// SetNillableClientOrderID sets the "client_order_id" field if the given value is not nil.
func (_u *OrderUpdate) SetNillableClientOrderID(v *int64) *OrderUpdate {
	if v != nil {
		_u.SetClientOrderID(*v)
	}
	return _u
}

// AddClientOrderID adds value to the "client_order_id" field.
func (_u *OrderUpdate) AddClientOrderID(v int64) *OrderUpdate {
	_u.mutation.AddClientOrderID(v)
	return _u
}

// SetSide sets the "side" field.
func (_u *OrderUpdate) SetSide(v string) *OrderUpdate {
	_u.mutation.SetSide(v)
	return _u
}

// SetNillableSide sets the "side" field if the given value is not nil.
func (_u *OrderUpdate) SetNillableSide(v *string) *OrderUpdate {
	if v != nil {
		_u.SetSide(*v)
	}
	return _u
}

// SetPrice sets the "price" field.
func (_u *OrderUpdate) SetPrice(v decimal.Decimal) *OrderUpdate {
	_u.mutation.SetPrice(v)
	return _u
}

// SetNillablePrice sets the "price" field if the given value is not nil.
func (_u *OrderUpdate) SetNillablePrice(v *decimal.Decimal) *OrderUpdate {
	if v != nil {
		_u.SetPrice(*v)
	}
	return _u
}

// SetQuantity sets the "quantity" field.
func (_u *OrderUpdate) SetQuantity(v decimal.Decimal) *OrderUpdate {
	_u.mutation.SetQuantity(v)
	return _u
}

// SetNillableQuantity sets the "quantity" field if the given value is not nil.
func (_u *OrderUpdate) SetNillableQuantity(v *decimal.Decimal) *OrderUpdate {
	if v != nil {
		_u.SetQuantity(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *OrderUpdate) SetStatus(v order.Status) *OrderUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *OrderUpdate) SetNillableStatus(v *order.Status) *OrderUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetTimestamp sets the "timestamp" field.
func (_u *OrderUpdate) SetTimestamp(v int64) *OrderUpdate {
	_u.mutation.ResetTimestamp()
	_u.mutation.SetTimestamp(v)
	return _u
}

// SetNillableTimestamp sets the "timestamp" field if the given value is not nil.
func (_u *OrderUpdate) SetNillableTimestamp(v *int64) *OrderUpdate {
	if v != nil {
		_u.SetTimestamp(*v)
	}
	return _u
}

// AddTimestamp adds value to the "timestamp" field.
func (_u *OrderUpdate) AddTimestamp(v int64) *OrderUpdate {
	_u.mutation.AddTimestamp(v)
	return _u
}

// Mutation returns the OrderMutation object of the builder.
func (_u *OrderUpdate) Mutation() *OrderMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *OrderUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OrderUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *OrderUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OrderUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *OrderUpdate) defaults() {
	if _, ok := _u.mutation.UpdateTime(); !ok {
		v := order.UpdateDefaultUpdateTime()
		_u.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OrderUpdate) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := order.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Order.status": %w`, err)}
		}
	}
	return nil
}

func (_u *OrderUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(order.Table, order.Columns, sqlgraph.NewFieldSpec(order.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(order.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Exchange(); ok {
		_spec.SetField(order.FieldExchange, field.TypeString, value)
	}
	if value, ok := _u.mutation.Account(); ok {
		_spec.SetField(order.FieldAccount, field.TypeString, value)
	}
	if value, ok := _u.mutation.Symbol(); ok {
		_spec.SetField(order.FieldSymbol, field.TypeString, value)
	}
	if value, ok := _u.mutation.OrderID(); ok {
		_spec.SetField(order.FieldOrderID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedOrderID(); ok {
		_spec.AddField(order.FieldOrderID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ClientOrderID(); ok {
		_spec.SetField(order.FieldClientOrderID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedClientOrderID(); ok {
		_spec.AddField(order.FieldClientOrderID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Side(); ok {
		_spec.SetField(order.FieldSide, field.TypeString, value)
	}
	if value, ok := _u.mutation.Price(); ok {
		_spec.SetField(order.FieldPrice, field.TypeString, value)
	}
	if value, ok := _u.mutation.Quantity(); ok {
		_spec.SetField(order.FieldQuantity, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(order.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Timestamp(); ok {
		_spec.SetField(order.FieldTimestamp, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTimestamp(); ok {
		_spec.AddField(order.FieldTimestamp, field.TypeInt64, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{order.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// OrderUpdateOne is the builder for updating a single Order entity.
type OrderUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *OrderMutation
}

// SetUpdateTime sets the "update_time" field.
func (_u *OrderUpdateOne) SetUpdateTime(v time.Time) *OrderUpdateOne {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetExchange sets the "exchange" field.
func (_u *OrderUpdateOne) SetExchange(v string) *OrderUpdateOne {
	_u.mutation.SetExchange(v)
	return _u
}

// SetNillableExchange sets the "exchange" field if the given value is not nil.
func (_u *OrderUpdateOne) SetNillableExchange(v *string) *OrderUpdateOne {
	if v != nil {
		_u.SetExchange(*v)
	}
	return _u
}

// SetAccount sets the "account" field.
func (_u *OrderUpdateOne) SetAccount(v string) *OrderUpdateOne {
	_u.mutation.SetAccount(v)
	return _u
}

// SetNillableAccount sets the "account" field if the given value is not nil.
func (_u *OrderUpdateOne) SetNillableAccount(v *string) *OrderUpdateOne {
	if v != nil {
		_u.SetAccount(*v)
	}
	return _u
}

// SetSymbol sets the "symbol" field.
func (_u *OrderUpdateOne) SetSymbol(v string) *OrderUpdateOne {
	_u.mutation.SetSymbol(v)
	return _u
}

// SetNillableSymbol sets the "symbol" field if the given value is not nil.
func (_u *OrderUpdateOne) SetNillableSymbol(v *string) *OrderUpdateOne {
	if v != nil {
		_u.SetSymbol(*v)
	}
	return _u
}

// SetOrderID sets the "order_id" field.
func (_u *OrderUpdateOne) SetOrderID(v int64) *OrderUpdateOne {
	_u.mutation.ResetOrderID()
	_u.mutation.SetOrderID(v)
	return _u
}

// SetNillableOrderID sets the "order_id" field if the given value is not nil.
func (_u *OrderUpdateOne) SetNillableOrderID(v *int64) *OrderUpdateOne {
	if v != nil {
		_u.SetOrderID(*v)
	}
	return _u
}

// AddOrderID adds value to the "order_id" field.
func (_u *OrderUpdateOne) AddOrderID(v int64) *OrderUpdateOne {
	_u.mutation.AddOrderID(v)
	return _u
}

// SetClientOrderID sets the "client_order_id" field.
func (_u *OrderUpdateOne) SetClientOrderID(v int64) *OrderUpdateOne {
	_u.mutation.ResetClientOrderID()
	_u.mutation.SetClientOrderID(v)
	return _u
}

// SetNillableClientOrderID sets the "client_order_id" field if the given value is not nil.
func (_u *OrderUpdateOne) SetNillableClientOrderID(v *int64) *OrderUpdateOne {
	if v != nil {
		_u.SetClientOrderID(*v)
	}
	return _u
}

// AddClientOrderID adds value to the "client_order_id" field.
func (_u *OrderUpdateOne) AddClientOrderID(v int64) *OrderUpdateOne {
	_u.mutation.AddClientOrderID(v)
	return _u
}

// SetSide sets the "side" field.
func (_u *OrderUpdateOne) SetSide(v string) *OrderUpdateOne {
	_u.mutation.SetSide(v)
	return _u
}

// SetNillableSide sets the "side" field if the given value is not nil.
func (_u *OrderUpdateOne) SetNillableSide(v *string) *OrderUpdateOne {
	if v != nil {
		_u.SetSide(*v)
	}
	return _u
}

// SetPrice sets the "price" field.
func (_u *OrderUpdateOne) SetPrice(v decimal.Decimal) *OrderUpdateOne {
	_u.mutation.SetPrice(v)
	return _u
}

// SetNillablePrice sets the "price" field if the given value is not nil.
func (_u *OrderUpdateOne) SetNillablePrice(v *decimal.Decimal) *OrderUpdateOne {
	if v != nil {
		_u.SetPrice(*v)
	}
	return _u
}

// SetQuantity sets the "quantity" field.
func (_u *OrderUpdateOne) SetQuantity(v decimal.Decimal) *OrderUpdateOne {
	_u.mutation.SetQuantity(v)
	return _u
}

// SetNillableQuantity sets the "quantity" field if the given value is not nil.
func (_u *OrderUpdateOne) SetNillableQuantity(v *decimal.Decimal) *OrderUpdateOne {
	if v != nil {
		_u.SetQuantity(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *OrderUpdateOne) SetStatus(v order.Status) *OrderUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *OrderUpdateOne) SetNillableStatus(v *order.Status) *OrderUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetTimestamp sets the "timestamp" field.
func (_u *OrderUpdateOne) SetTimestamp(v int64) *OrderUpdateOne {
	_u.mutation.ResetTimestamp()
	_u.mutation.SetTimestamp(v)
	return _u
}

// SetNillableTimestamp sets the "timestamp" field if the given value is not nil.
func (_u *OrderUpdateOne) SetNillableTimestamp(v *int64) *OrderUpdateOne {
	if v != nil {
		_u.SetTimestamp(*v)
	}
	return _u
}

// AddTimestamp adds value to the "timestamp" field.
func (_u *OrderUpdateOne) AddTimestamp(v int64) *OrderUpdateOne {
	_u.mutation.AddTimestamp(v)
	return _u
}

// Mutation returns the OrderMutation object of the builder.
func (_u *OrderUpdateOne) Mutation() *OrderMutation {
	return _u.mutation
}

// Where appends a list predicates to the OrderUpdate builder.
func (_u *OrderUpdateOne) Where(ps ...predicate.Order) *OrderUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *OrderUpdateOne) Select(field string, fields ...string) *OrderUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Order entity.
func (_u *OrderUpdateOne) Save(ctx context.Context) (*Order, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OrderUpdateOne) SaveX(ctx context.Context) *Order {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *OrderUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OrderUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *OrderUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdateTime(); !ok {
		v := order.UpdateDefaultUpdateTime()
		_u.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OrderUpdateOne) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := order.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Order.status": %w`, err)}
		}
	}
	return nil
}

func (_u *OrderUpdateOne) sqlSave(ctx context.Context) (_node *Order, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(order.Table, order.Columns, sqlgraph.NewFieldSpec(order.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Order.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, order.FieldID)
		for _, f := range fields {
			if !order.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != order.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(order.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Exchange(); ok {
		_spec.SetField(order.FieldExchange, field.TypeString, value)
	}
	if value, ok := _u.mutation.Account(); ok {
		_spec.SetField(order.FieldAccount, field.TypeString, value)
	}
	if value, ok := _u.mutation.Symbol(); ok {
		_spec.SetField(order.FieldSymbol, field.TypeString, value)
	}
	if value, ok := _u.mutation.OrderID(); ok {
		_spec.SetField(order.FieldOrderID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedOrderID(); ok {
		_spec.AddField(order.FieldOrderID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ClientOrderID(); ok {
		_spec.SetField(order.FieldClientOrderID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedClientOrderID(); ok {
		_spec.AddField(order.FieldClientOrderID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Side(); ok {
		_spec.SetField(order.FieldSide, field.TypeString, value)
	}
	if value, ok := _u.mutation.Price(); ok {
		_spec.SetField(order.FieldPrice, field.TypeString, value)
	}
	if value, ok := _u.mutation.Quantity(); ok {
		_spec.SetField(order.FieldQuantity, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(order.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Timestamp(); ok {
		_spec.SetField(order.FieldTimestamp, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTimestamp(); ok {
		_spec.AddField(order.FieldTimestamp, field.TypeInt64, value)
	}
	_node = &Order{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{order.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
