// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/fachebot/perp-dex-grid-bot/internal/ent/grid"
	"github.com/fachebot/perp-dex-grid-bot/internal/ent/order"
	"github.com/fachebot/perp-dex-grid-bot/internal/ent/schema"
	"github.com/fachebot/perp-dex-grid-bot/internal/ent/strategy"
	"github.com/fachebot/perp-dex-grid-bot/internal/ent/syncprogress"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	gridMixin := schema.Grid{}.Mixin()
	gridMixinFields0 := gridMixin[0].Fields()
	_ = gridMixinFields0
	gridFields := schema.Grid{}.Fields()
	_ = gridFields
	// gridDescCreateTime is the schema descriptor for create_time field.
	gridDescCreateTime := gridMixinFields0[0].Descriptor()
	// grid.DefaultCreateTime holds the default value on creation for the create_time field.
	grid.DefaultCreateTime = gridDescCreateTime.Default.(func() time.Time)
	// gridDescUpdateTime is the schema descriptor for update_time field.
	gridDescUpdateTime := gridMixinFields0[1].Descriptor()
	// grid.DefaultUpdateTime holds the default value on creation for the update_time field.
	grid.DefaultUpdateTime = gridDescUpdateTime.Default.(func() time.Time)
	// grid.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	grid.UpdateDefaultUpdateTime = gridDescUpdateTime.UpdateDefault.(func() time.Time)
	// gridDescStrategyId is the schema descriptor for strategyId field.
	gridDescStrategyId := gridFields[0].Descriptor()
	// grid.StrategyIdValidator is a validator for the "strategyId" field. It is called by the builders before save.
	grid.StrategyIdValidator = gridDescStrategyId.Validators[0].(func(string) error)
	// gridDescExchange is the schema descriptor for exchange field.
	gridDescExchange := gridFields[1].Descriptor()
	// grid.ExchangeValidator is a validator for the "exchange" field. It is called by the builders before save.
	grid.ExchangeValidator = gridDescExchange.Validators[0].(func(string) error)
	// gridDescSymbol is the schema descriptor for symbol field.
	gridDescSymbol := gridFields[2].Descriptor()
	// grid.SymbolValidator is a validator for the "symbol" field. It is called by the builders before save.
	grid.SymbolValidator = gridDescSymbol.Validators[0].(func(string) error)
	orderMixin := schema.Order{}.Mixin()
	orderMixinFields0 := orderMixin[0].Fields()
	_ = orderMixinFields0
	orderFields := schema.Order{}.Fields()
	_ = orderFields
	// orderDescCreateTime is the schema descriptor for create_time field.
	orderDescCreateTime := orderMixinFields0[0].Descriptor()
	// order.DefaultCreateTime holds the default value on creation for the create_time field.
	order.DefaultCreateTime = orderDescCreateTime.Default.(func() time.Time)
	// orderDescUpdateTime is the schema descriptor for update_time field.
	orderDescUpdateTime := orderMixinFields0[1].Descriptor()
	// order.DefaultUpdateTime holds the default value on creation for the update_time field.
	order.DefaultUpdateTime = orderDescUpdateTime.Default.(func() time.Time)
	// order.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	order.UpdateDefaultUpdateTime = orderDescUpdateTime.UpdateDefault.(func() time.Time)
	strategyMixin := schema.Strategy{}.Mixin()
	strategyMixinFields0 := strategyMixin[0].Fields()
	_ = strategyMixinFields0
	strategyFields := schema.Strategy{}.Fields()
	_ = strategyFields
	// strategyDescCreateTime is the schema descriptor for create_time field.
	strategyDescCreateTime := strategyMixinFields0[0].Descriptor()
	// strategy.DefaultCreateTime holds the default value on creation for the create_time field.
	strategy.DefaultCreateTime = strategyDescCreateTime.Default.(func() time.Time)
	// strategyDescUpdateTime is the schema descriptor for update_time field.
	strategyDescUpdateTime := strategyMixinFields0[1].Descriptor()
	// strategy.DefaultUpdateTime holds the default value on creation for the update_time field.
	strategy.DefaultUpdateTime = strategyDescUpdateTime.Default.(func() time.Time)
	// strategy.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	strategy.UpdateDefaultUpdateTime = strategyDescUpdateTime.UpdateDefault.(func() time.Time)
	// strategyDescGUID is the schema descriptor for guid field.
	strategyDescGUID := strategyFields[0].Descriptor()
	// strategy.GUIDValidator is a validator for the "guid" field. It is called by the builders before save.
	strategy.GUIDValidator = strategyDescGUID.Validators[0].(func(string) error)
	// strategyDescExchange is the schema descriptor for exchange field.
	strategyDescExchange := strategyFields[2].Descriptor()
	// strategy.ExchangeValidator is a validator for the "exchange" field. It is called by the builders before save.
	strategy.ExchangeValidator = strategyDescExchange.Validators[0].(func(string) error)
	// strategyDescSymbol is the schema descriptor for symbol field.
	strategyDescSymbol := strategyFields[3].Descriptor()
	// strategy.SymbolValidator is a validator for the "symbol" field. It is called by the builders before save.
	strategy.SymbolValidator = strategyDescSymbol.Validators[0].(func(string) error)
	// strategyDescGridNum is the schema descriptor for gridNum field.
	strategyDescGridNum := strategyFields[10].Descriptor()
	// strategy.DefaultGridNum holds the default value on creation for the gridNum field.
	strategy.DefaultGridNum = strategyDescGridNum.Default.(int)
	// strategy.GridNumValidator is a validator for the "gridNum" field. It is called by the builders before save.
	strategy.GridNumValidator = strategyDescGridNum.Validators[0].(func(int) error)
	// strategyDescLeverage is the schema descriptor for leverage field.
	strategyDescLeverage := strategyFields[11].Descriptor()
	// strategy.DefaultLeverage holds the default value on creation for the leverage field.
	strategy.DefaultLeverage = strategyDescLeverage.Default.(int)
	// strategy.LeverageValidator is a validator for the "leverage" field. It is called by the builders before save.
	strategy.LeverageValidator = strategyDescLeverage.Validators[0].(func(int) error)
	syncprogressMixin := schema.SyncProgress{}.Mixin()
	syncprogressMixinFields0 := syncprogressMixin[0].Fields()
	_ = syncprogressMixinFields0
	syncprogressFields := schema.SyncProgress{}.Fields()
	_ = syncprogressFields
	// syncprogressDescCreateTime is the schema descriptor for create_time field.
	syncprogressDescCreateTime := syncprogressMixinFields0[0].Descriptor()
	// syncprogress.DefaultCreateTime holds the default value on creation for the create_time field.
	syncprogress.DefaultCreateTime = syncprogressDescCreateTime.Default.(func() time.Time)
	// syncprogressDescUpdateTime is the schema descriptor for update_time field.
	syncprogressDescUpdateTime := syncprogressMixinFields0[1].Descriptor()
	// syncprogress.DefaultUpdateTime holds the default value on creation for the update_time field.
	syncprogress.DefaultUpdateTime = syncprogressDescUpdateTime.Default.(func() time.Time)
	// syncprogress.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	syncprogress.UpdateDefaultUpdateTime = syncprogressDescUpdateTime.UpdateDefault.(func() time.Time)
}
