// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/fachebot/perp-dex-grid-bot/internal/ent/predicate"
	"github.com/fachebot/perp-dex-grid-bot/internal/ent/strategy"
	"github.com/shopspring/decimal"
)

// StrategyUpdate is the builder for updating Strategy entities.
type StrategyUpdate struct {
	config
	hooks    []Hook
	mutation *StrategyMutation
}

// Where appends a list predicates to the StrategyUpdate builder.
func (_u *StrategyUpdate) Where(ps ...predicate.Strategy) *StrategyUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdateTime sets the "update_time" field.
func (_u *StrategyUpdate) SetUpdateTime(v time.Time) *StrategyUpdate {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetGUID sets the "guid" field.
func (_u *StrategyUpdate) SetGUID(v string) *StrategyUpdate {
	_u.mutation.SetGUID(v)
	return _u
}

// SetNillableGUID sets the "guid" field if the given value is not nil.
func (_u *StrategyUpdate) SetNillableGUID(v *string) *StrategyUpdate {
	if v != nil {
		_u.SetGUID(*v)
	}
	return _u
}

// SetExchange sets the "exchange" field.
func (_u *StrategyUpdate) SetExchange(v string) *StrategyUpdate {
	_u.mutation.SetExchange(v)
	return _u
}

// SetNillableExchange sets the "exchange" field if the given value is not nil.
func (_u *StrategyUpdate) SetNillableExchange(v *string) *StrategyUpdate {
	if v != nil {
		_u.SetExchange(*v)
	}
	return _u
}

// SetSymbol sets the "symbol" field.
func (_u *StrategyUpdate) SetSymbol(v string) *StrategyUpdate {
	_u.mutation.SetSymbol(v)
	return _u
}

// SetNillableSymbol sets the "symbol" field if the given value is not nil.
func (_u *StrategyUpdate) SetNillableSymbol(v *string) *StrategyUpdate {
	if v != nil {
		_u.SetSymbol(*v)
	}
	return _u
}

// SetAccount sets the "account" field.
func (_u *StrategyUpdate) SetAccount(v string) *StrategyUpdate {
	_u.mutation.SetAccount(v)
	return _u
}

// SetNillableAccount sets the "account" field if the given value is not nil.
func (_u *StrategyUpdate) SetNillableAccount(v *string) *StrategyUpdate {
	if v != nil {
		_u.SetAccount(*v)
	}
	return _u
}

// SetMode sets the "mode" field.
func (_u *StrategyUpdate) SetMode(v strategy.Mode) *StrategyUpdate {
	_u.mutation.SetMode(v)
	return _u
}

// SetNillableMode sets the "mode" field if the given value is not nil.
func (_u *StrategyUpdate) SetNillableMode(v *strategy.Mode) *StrategyUpdate {
	if v != nil {
		_u.SetMode(*v)
	}
	return _u
}

// SetMarginMode sets the "marginMode" field.
func (_u *StrategyUpdate) SetMarginMode(v strategy.MarginMode) *StrategyUpdate {
	_u.mutation.SetMarginMode(v)
	return _u
}

// SetNillableMarginMode sets the "marginMode" field if the given value is not nil.
func (_u *StrategyUpdate) SetNillableMarginMode(v *strategy.MarginMode) *StrategyUpdate {
	if v != nil {
		_u.SetMarginMode(*v)
	}
	return _u
}

// SetQuantityMode sets the "quantityMode" field.
func (_u *StrategyUpdate) SetQuantityMode(v strategy.QuantityMode) *StrategyUpdate {
	_u.mutation.SetQuantityMode(v)
	return _u
}

// SetNillableQuantityMode sets the "quantityMode" field if the given value is not nil.
func (_u *StrategyUpdate) SetNillableQuantityMode(v *strategy.QuantityMode) *StrategyUpdate {
	if v != nil {
		_u.SetQuantityMode(*v)
	}
	return _u
}

// SetPriceUpper sets the "priceUpper" field.
func (_u *StrategyUpdate) SetPriceUpper(v decimal.Decimal) *StrategyUpdate {
	_u.mutation.SetPriceUpper(v)
	return _u
}

// SetNillablePriceUpper sets the "priceUpper" field if the given value is not nil.
func (_u *StrategyUpdate) SetNillablePriceUpper(v *decimal.Decimal) *StrategyUpdate {
	if v != nil {
		_u.SetPriceUpper(*v)
	}
	return _u
}

// SetPriceLower sets the "priceLower" field.
func (_u *StrategyUpdate) SetPriceLower(v decimal.Decimal) *StrategyUpdate {
	_u.mutation.SetPriceLower(v)
	return _u
}

// SetNillablePriceLower sets the "priceLower" field if the given value is not nil.
func (_u *StrategyUpdate) SetNillablePriceLower(v *decimal.Decimal) *StrategyUpdate {
	if v != nil {
		_u.SetPriceLower(*v)
	}
	return _u
}

// SetGridNum sets the "gridNum" field.
func (_u *StrategyUpdate) SetGridNum(v int) *StrategyUpdate {
	_u.mutation.ResetGridNum()
	_u.mutation.SetGridNum(v)
	return _u
}

// SetNillableGridNum sets the "gridNum" field if the given value is not nil.
func (_u *StrategyUpdate) SetNillableGridNum(v *int) *StrategyUpdate {
	if v != nil {
		_u.SetGridNum(*v)
	}
	return _u
}

// AddGridNum adds value to the "gridNum" field.
func (_u *StrategyUpdate) AddGridNum(v int) *StrategyUpdate {
	_u.mutation.AddGridNum(v)
	return _u
}

// SetLeverage sets the "leverage" field.
func (_u *StrategyUpdate) SetLeverage(v int) *StrategyUpdate {
	_u.mutation.ResetLeverage()
	_u.mutation.SetLeverage(v)
	return _u
}

// SetNillableLeverage sets the "leverage" field if the given value is not nil.
func (_u *StrategyUpdate) SetNillableLeverage(v *int) *StrategyUpdate {
	if v != nil {
		_u.SetLeverage(*v)
	}
	return _u
}

// AddLeverage adds value to the "leverage" field.
func (_u *StrategyUpdate) AddLeverage(v int) *StrategyUpdate {
	_u.mutation.AddLeverage(v)
	return _u
}

// SetInitialOrderSize sets the "initialOrderSize" field.
func (_u *StrategyUpdate) SetInitialOrderSize(v decimal.Decimal) *StrategyUpdate {
	_u.mutation.SetInitialOrderSize(v)
	return _u
}

// SetNillableInitialOrderSize sets the "initialOrderSize" field if the given value is not nil.
func (_u *StrategyUpdate) SetNillableInitialOrderSize(v *decimal.Decimal) *StrategyUpdate {
	if v != nil {
		_u.SetInitialOrderSize(*v)
	}
	return _u
}

// SetStopLossRatio sets the "stopLossRatio" field.
func (_u *StrategyUpdate) SetStopLossRatio(v decimal.Decimal) *StrategyUpdate {
	_u.mutation.SetStopLossRatio(v)
	return _u
}

// SetNillableStopLossRatio sets the "stopLossRatio" field if the given value is not nil.
func (_u *StrategyUpdate) SetNillableStopLossRatio(v *decimal.Decimal) *StrategyUpdate {
	if v != nil {
		_u.SetStopLossRatio(*v)
	}
	return _u
}

// SetTakeProfitRatio sets the "takeProfitRatio" field.
func (_u *StrategyUpdate) SetTakeProfitRatio(v decimal.Decimal) *StrategyUpdate {
	_u.mutation.SetTakeProfitRatio(v)
	return _u
}

// SetNillableTakeProfitRatio sets the "takeProfitRatio" field if the given value is not nil.
func (_u *StrategyUpdate) SetNillableTakeProfitRatio(v *decimal.Decimal) *StrategyUpdate {
	if v != nil {
		_u.SetTakeProfitRatio(*v)
	}
	return _u
}

// SetEnableAutoBuy sets the "enableAutoBuy" field.
func (_u *StrategyUpdate) SetEnableAutoBuy(v bool) *StrategyUpdate {
	_u.mutation.SetEnableAutoBuy(v)
	return _u
}

// SetNillableEnableAutoBuy sets the "enableAutoBuy" field if the given value is not nil.
func (_u *StrategyUpdate) SetNillableEnableAutoBuy(v *bool) *StrategyUpdate {
	if v != nil {
		_u.SetEnableAutoBuy(*v)
	}
	return _u
}

// SetEnableAutoSell sets the "enableAutoSell" field.
func (_u *StrategyUpdate) SetEnableAutoSell(v bool) *StrategyUpdate {
	_u.mutation.SetEnableAutoSell(v)
	return _u
}

// SetNillableEnableAutoSell sets the "enableAutoSell" field if the given value is not nil.
func (_u *StrategyUpdate) SetNillableEnableAutoSell(v *bool) *StrategyUpdate {
	if v != nil {
		_u.SetEnableAutoSell(*v)
	}
	return _u
}

// SetEnableAutoExit sets the "enableAutoExit" field.
func (_u *StrategyUpdate) SetEnableAutoExit(v bool) *StrategyUpdate {
	_u.mutation.SetEnableAutoExit(v)
	return _u
}

// SetNillableEnableAutoExit sets the "enableAutoExit" field if the given value is not nil.
func (_u *StrategyUpdate) SetNillableEnableAutoExit(v *bool) *StrategyUpdate {
	if v != nil {
		_u.SetEnableAutoExit(*v)
	}
	return _u
}

// SetEnablePushNotification sets the "enablePushNotification" field.
func (_u *StrategyUpdate) SetEnablePushNotification(v bool) *StrategyUpdate {
	_u.mutation.SetEnablePushNotification(v)
	return _u
}

// SetNillableEnablePushNotification sets the "enablePushNotification" field if the given value is not nil.
func (_u *StrategyUpdate) SetNillableEnablePushNotification(v *bool) *StrategyUpdate {
	if v != nil {
		_u.SetEnablePushNotification(*v)
	}
	return _u
}

// SetLastLowerThresholdAlertTime sets the "lastLowerThresholdAlertTime" field.
func (_u *StrategyUpdate) SetLastLowerThresholdAlertTime(v time.Time) *StrategyUpdate {
	_u.mutation.SetLastLowerThresholdAlertTime(v)
	return _u
}

// SetNillableLastLowerThresholdAlertTime sets the "lastLowerThresholdAlertTime" field if the given value is not nil.
func (_u *StrategyUpdate) SetNillableLastLowerThresholdAlertTime(v *time.Time) *StrategyUpdate {
	if v != nil {
		_u.SetLastLowerThresholdAlertTime(*v)
	}
	return _u
}

// ClearLastLowerThresholdAlertTime clears the value of the "lastLowerThresholdAlertTime" field.
func (_u *StrategyUpdate) ClearLastLowerThresholdAlertTime() *StrategyUpdate {
	_u.mutation.ClearLastLowerThresholdAlertTime()
	return _u
}

// SetLastUpperThresholdAlertTime sets the "lastUpperThresholdAlertTime" field.
func (_u *StrategyUpdate) SetLastUpperThresholdAlertTime(v time.Time) *StrategyUpdate {
	_u.mutation.SetLastUpperThresholdAlertTime(v)
	return _u
}

// SetNillableLastUpperThresholdAlertTime sets the "lastUpperThresholdAlertTime" field if the given value is not nil.
func (_u *StrategyUpdate) SetNillableLastUpperThresholdAlertTime(v *time.Time) *StrategyUpdate {
	if v != nil {
		_u.SetLastUpperThresholdAlertTime(*v)
	}
	return _u
}

// ClearLastUpperThresholdAlertTime clears the value of the "lastUpperThresholdAlertTime" field.
func (_u *StrategyUpdate) ClearLastUpperThresholdAlertTime() *StrategyUpdate {
	_u.mutation.ClearLastUpperThresholdAlertTime()
	return _u
}

// SetStatus sets the "status" field.
func (_u *StrategyUpdate) SetStatus(v strategy.Status) *StrategyUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *StrategyUpdate) SetNillableStatus(v *strategy.Status) *StrategyUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetExchangeApiKey sets the "exchangeApiKey" field.
func (_u *StrategyUpdate) SetExchangeApiKey(v string) *StrategyUpdate {
	_u.mutation.SetExchangeApiKey(v)
	return _u
}

// SetNillableExchangeApiKey sets the "exchangeApiKey" field if the given value is not nil.
func (_u *StrategyUpdate) SetNillableExchangeApiKey(v *string) *StrategyUpdate {
	if v != nil {
		_u.SetExchangeApiKey(*v)
	}
	return _u
}

// SetExchangeSecretKey sets the "exchangeSecretKey" field.
func (_u *StrategyUpdate) SetExchangeSecretKey(v string) *StrategyUpdate {
	_u.mutation.SetExchangeSecretKey(v)
	return _u
}

// SetNillableExchangeSecretKey sets the "exchangeSecretKey" field if the given value is not nil.
func (_u *StrategyUpdate) SetNillableExchangeSecretKey(v *string) *StrategyUpdate {
	if v != nil {
		_u.SetExchangeSecretKey(*v)
	}
	return _u
}

// SetExchangePassphrase sets the "exchangePassphrase" field.
func (_u *StrategyUpdate) SetExchangePassphrase(v string) *StrategyUpdate {
	_u.mutation.SetExchangePassphrase(v)
	return _u
}

// SetNillableExchangePassphrase sets the "exchangePassphrase" field if the given value is not nil.
func (_u *StrategyUpdate) SetNillableExchangePassphrase(v *string) *StrategyUpdate {
	if v != nil {
		_u.SetExchangePassphrase(*v)
	}
	return _u
}

// Mutation returns the StrategyMutation object of the builder.
func (_u *StrategyUpdate) Mutation() *StrategyMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *StrategyUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *StrategyUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *StrategyUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *StrategyUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *StrategyUpdate) defaults() {
	if _, ok := _u.mutation.UpdateTime(); !ok {
		v := strategy.UpdateDefaultUpdateTime()
		_u.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *StrategyUpdate) check() error {
	if v, ok := _u.mutation.GUID(); ok {
		if err := strategy.GUIDValidator(v); err != nil {
			return &ValidationError{Name: "guid", err: fmt.Errorf(`ent: validator failed for field "Strategy.guid": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Exchange(); ok {
		if err := strategy.ExchangeValidator(v); err != nil {
			return &ValidationError{Name: "exchange", err: fmt.Errorf(`ent: validator failed for field "Strategy.exchange": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Symbol(); ok {
		if err := strategy.SymbolValidator(v); err != nil {
			return &ValidationError{Name: "symbol", err: fmt.Errorf(`ent: validator failed for field "Strategy.symbol": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Mode(); ok {
		if err := strategy.ModeValidator(v); err != nil {
			return &ValidationError{Name: "mode", err: fmt.Errorf(`ent: validator failed for field "Strategy.mode": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MarginMode(); ok {
		if err := strategy.MarginModeValidator(v); err != nil {
			return &ValidationError{Name: "marginMode", err: fmt.Errorf(`ent: validator failed for field "Strategy.marginMode": %w`, err)}
		}
	}
	if v, ok := _u.mutation.QuantityMode(); ok {
		if err := strategy.QuantityModeValidator(v); err != nil {
			return &ValidationError{Name: "quantityMode", err: fmt.Errorf(`ent: validator failed for field "Strategy.quantityMode": %w`, err)}
		}
	}
	if v, ok := _u.mutation.GridNum(); ok {
		if err := strategy.GridNumValidator(v); err != nil {
			return &ValidationError{Name: "gridNum", err: fmt.Errorf(`ent: validator failed for field "Strategy.gridNum": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Leverage(); ok {
		if err := strategy.LeverageValidator(v); err != nil {
			return &ValidationError{Name: "leverage", err: fmt.Errorf(`ent: validator failed for field "Strategy.leverage": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := strategy.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Strategy.status": %w`, err)}
		}
	}
	return nil
}

func (_u *StrategyUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(strategy.Table, strategy.Columns, sqlgraph.NewFieldSpec(strategy.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(strategy.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.GUID(); ok {
		_spec.SetField(strategy.FieldGUID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Exchange(); ok {
		_spec.SetField(strategy.FieldExchange, field.TypeString, value)
	}
	if value, ok := _u.mutation.Symbol(); ok {
		_spec.SetField(strategy.FieldSymbol, field.TypeString, value)
	}
	if value, ok := _u.mutation.Account(); ok {
		_spec.SetField(strategy.FieldAccount, field.TypeString, value)
	}
	if value, ok := _u.mutation.Mode(); ok {
		_spec.SetField(strategy.FieldMode, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.MarginMode(); ok {
		_spec.SetField(strategy.FieldMarginMode, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.QuantityMode(); ok {
		_spec.SetField(strategy.FieldQuantityMode, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.PriceUpper(); ok {
		_spec.SetField(strategy.FieldPriceUpper, field.TypeString, value)
	}
	if value, ok := _u.mutation.PriceLower(); ok {
		_spec.SetField(strategy.FieldPriceLower, field.TypeString, value)
	}
	if value, ok := _u.mutation.GridNum(); ok {
		_spec.SetField(strategy.FieldGridNum, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedGridNum(); ok {
		_spec.AddField(strategy.FieldGridNum, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Leverage(); ok {
		_spec.SetField(strategy.FieldLeverage, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedLeverage(); ok {
		_spec.AddField(strategy.FieldLeverage, field.TypeInt, value)
	}
	if value, ok := _u.mutation.InitialOrderSize(); ok {
		_spec.SetField(strategy.FieldInitialOrderSize, field.TypeString, value)
	}
	if value, ok := _u.mutation.StopLossRatio(); ok {
		_spec.SetField(strategy.FieldStopLossRatio, field.TypeString, value)
	}
	if value, ok := _u.mutation.TakeProfitRatio(); ok {
		_spec.SetField(strategy.FieldTakeProfitRatio, field.TypeString, value)
	}
	if value, ok := _u.mutation.EnableAutoBuy(); ok {
		_spec.SetField(strategy.FieldEnableAutoBuy, field.TypeBool, value)
	}
	if value, ok := _u.mutation.EnableAutoSell(); ok {
		_spec.SetField(strategy.FieldEnableAutoSell, field.TypeBool, value)
	}
	if value, ok := _u.mutation.EnableAutoExit(); ok {
		_spec.SetField(strategy.FieldEnableAutoExit, field.TypeBool, value)
	}
	if value, ok := _u.mutation.EnablePushNotification(); ok {
		_spec.SetField(strategy.FieldEnablePushNotification, field.TypeBool, value)
	}
	if value, ok := _u.mutation.LastLowerThresholdAlertTime(); ok {
		_spec.SetField(strategy.FieldLastLowerThresholdAlertTime, field.TypeTime, value)
	}
	if _u.mutation.LastLowerThresholdAlertTimeCleared() {
		_spec.ClearField(strategy.FieldLastLowerThresholdAlertTime, field.TypeTime)
	}
	if value, ok := _u.mutation.LastUpperThresholdAlertTime(); ok {
		_spec.SetField(strategy.FieldLastUpperThresholdAlertTime, field.TypeTime, value)
	}
	if _u.mutation.LastUpperThresholdAlertTimeCleared() {
		_spec.ClearField(strategy.FieldLastUpperThresholdAlertTime, field.TypeTime)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(strategy.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ExchangeApiKey(); ok {
		_spec.SetField(strategy.FieldExchangeApiKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExchangeSecretKey(); ok {
		_spec.SetField(strategy.FieldExchangeSecretKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExchangePassphrase(); ok {
		_spec.SetField(strategy.FieldExchangePassphrase, field.TypeString, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{strategy.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// StrategyUpdateOne is the builder for updating a single Strategy entity.
type StrategyUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *StrategyMutation
}

// SetUpdateTime sets the "update_time" field.
func (_u *StrategyUpdateOne) SetUpdateTime(v time.Time) *StrategyUpdateOne {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetGUID sets the "guid" field.
func (_u *StrategyUpdateOne) SetGUID(v string) *StrategyUpdateOne {
	_u.mutation.SetGUID(v)
	return _u
}

// SetNillableGUID sets the "guid" field if the given value is not nil.
func (_u *StrategyUpdateOne) SetNillableGUID(v *string) *StrategyUpdateOne {
	if v != nil {
		_u.SetGUID(*v)
	}
	return _u
}

// SetExchange sets the "exchange" field.
func (_u *StrategyUpdateOne) SetExchange(v string) *StrategyUpdateOne {
	_u.mutation.SetExchange(v)
	return _u
}

// SetNillableExchange sets the "exchange" field if the given value is not nil.
func (_u *StrategyUpdateOne) SetNillableExchange(v *string) *StrategyUpdateOne {
	if v != nil {
		_u.SetExchange(*v)
	}
	return _u
}

// SetSymbol sets the "symbol" field.
func (_u *StrategyUpdateOne) SetSymbol(v string) *StrategyUpdateOne {
	_u.mutation.SetSymbol(v)
	return _u
}

// SetNillableSymbol sets the "symbol" field if the given value is not nil.
func (_u *StrategyUpdateOne) SetNillableSymbol(v *string) *StrategyUpdateOne {
	if v != nil {
		_u.SetSymbol(*v)
	}
	return _u
}

// SetAccount sets the "account" field.
func (_u *StrategyUpdateOne) SetAccount(v string) *StrategyUpdateOne {
	_u.mutation.SetAccount(v)
	return _u
}

// SetNillableAccount sets the "account" field if the given value is not nil.
func (_u *StrategyUpdateOne) SetNillableAccount(v *string) *StrategyUpdateOne {
	if v != nil {
		_u.SetAccount(*v)
	}
	return _u
}

// SetMode sets the "mode" field.
func (_u *StrategyUpdateOne) SetMode(v strategy.Mode) *StrategyUpdateOne {
	_u.mutation.SetMode(v)
	return _u
}

// SetNillableMode sets the "mode" field if the given value is not nil.
func (_u *StrategyUpdateOne) SetNillableMode(v *strategy.Mode) *StrategyUpdateOne {
	if v != nil {
		_u.SetMode(*v)
	}
	return _u
}

// SetMarginMode sets the "marginMode" field.
func (_u *StrategyUpdateOne) SetMarginMode(v strategy.MarginMode) *StrategyUpdateOne {
	_u.mutation.SetMarginMode(v)
	return _u
}

// SetNillableMarginMode sets the "marginMode" field if the given value is not nil.
func (_u *StrategyUpdateOne) SetNillableMarginMode(v *strategy.MarginMode) *StrategyUpdateOne {
	if v != nil {
		_u.SetMarginMode(*v)
	}
	return _u
}

// SetQuantityMode sets the "quantityMode" field.
func (_u *StrategyUpdateOne) SetQuantityMode(v strategy.QuantityMode) *StrategyUpdateOne {
	_u.mutation.SetQuantityMode(v)
	return _u
}

// SetNillableQuantityMode sets the "quantityMode" field if the given value is not nil.
func (_u *StrategyUpdateOne) SetNillableQuantityMode(v *strategy.QuantityMode) *StrategyUpdateOne {
	if v != nil {
		_u.SetQuantityMode(*v)
	}
	return _u
}

// SetPriceUpper sets the "priceUpper" field.
func (_u *StrategyUpdateOne) SetPriceUpper(v decimal.Decimal) *StrategyUpdateOne {
	_u.mutation.SetPriceUpper(v)
	return _u
}

// SetNillablePriceUpper sets the "priceUpper" field if the given value is not nil.
func (_u *StrategyUpdateOne) SetNillablePriceUpper(v *decimal.Decimal) *StrategyUpdateOne {
	if v != nil {
		_u.SetPriceUpper(*v)
	}
	return _u
}

// SetPriceLower sets the "priceLower" field.
func (_u *StrategyUpdateOne) SetPriceLower(v decimal.Decimal) *StrategyUpdateOne {
	_u.mutation.SetPriceLower(v)
	return _u
}

// SetNillablePriceLower sets the "priceLower" field if the given value is not nil.
func (_u *StrategyUpdateOne) SetNillablePriceLower(v *decimal.Decimal) *StrategyUpdateOne {
	if v != nil {
		_u.SetPriceLower(*v)
	}
	return _u
}

// SetGridNum sets the "gridNum" field.
func (_u *StrategyUpdateOne) SetGridNum(v int) *StrategyUpdateOne {
	_u.mutation.ResetGridNum()
	_u.mutation.SetGridNum(v)
	return _u
}

// SetNillableGridNum sets the "gridNum" field if the given value is not nil.
func (_u *StrategyUpdateOne) SetNillableGridNum(v *int) *StrategyUpdateOne {
	if v != nil {
		_u.SetGridNum(*v)
	}
	return _u
}

// AddGridNum adds value to the "gridNum" field.
func (_u *StrategyUpdateOne) AddGridNum(v int) *StrategyUpdateOne {
	_u.mutation.AddGridNum(v)
	return _u
}

// SetLeverage sets the "leverage" field.
func (_u *StrategyUpdateOne) SetLeverage(v int) *StrategyUpdateOne {
	_u.mutation.ResetLeverage()
	_u.mutation.SetLeverage(v)
	return _u
}

// SetNillableLeverage sets the "leverage" field if the given value is not nil.
func (_u *StrategyUpdateOne) SetNillableLeverage(v *int) *StrategyUpdateOne {
	if v != nil {
		_u.SetLeverage(*v)
	}
	return _u
}

// AddLeverage adds value to the "leverage" field.
func (_u *StrategyUpdateOne) AddLeverage(v int) *StrategyUpdateOne {
	_u.mutation.AddLeverage(v)
	return _u
}

// SetInitialOrderSize sets the "initialOrderSize" field.
func (_u *StrategyUpdateOne) SetInitialOrderSize(v decimal.Decimal) *StrategyUpdateOne {
	_u.mutation.SetInitialOrderSize(v)
	return _u
}

// SetNillableInitialOrderSize sets the "initialOrderSize" field if the given value is not nil.
func (_u *StrategyUpdateOne) SetNillableInitialOrderSize(v *decimal.Decimal) *StrategyUpdateOne {
	if v != nil {
		_u.SetInitialOrderSize(*v)
	}
	return _u
}

// SetStopLossRatio sets the "stopLossRatio" field.
func (_u *StrategyUpdateOne) SetStopLossRatio(v decimal.Decimal) *StrategyUpdateOne {
	_u.mutation.SetStopLossRatio(v)
	return _u
}

// SetNillableStopLossRatio sets the "stopLossRatio" field if the given value is not nil.
func (_u *StrategyUpdateOne) SetNillableStopLossRatio(v *decimal.Decimal) *StrategyUpdateOne {
	if v != nil {
		_u.SetStopLossRatio(*v)
	}
	return _u
}

// SetTakeProfitRatio sets the "takeProfitRatio" field.
func (_u *StrategyUpdateOne) SetTakeProfitRatio(v decimal.Decimal) *StrategyUpdateOne {
	_u.mutation.SetTakeProfitRatio(v)
	return _u
}

// SetNillableTakeProfitRatio sets the "takeProfitRatio" field if the given value is not nil.
func (_u *StrategyUpdateOne) SetNillableTakeProfitRatio(v *decimal.Decimal) *StrategyUpdateOne {
	if v != nil {
		_u.SetTakeProfitRatio(*v)
	}
	return _u
}

// SetEnableAutoBuy sets the "enableAutoBuy" field.
func (_u *StrategyUpdateOne) SetEnableAutoBuy(v bool) *StrategyUpdateOne {
	_u.mutation.SetEnableAutoBuy(v)
	return _u
}

// SetNillableEnableAutoBuy sets the "enableAutoBuy" field if the given value is not nil.
func (_u *StrategyUpdateOne) SetNillableEnableAutoBuy(v *bool) *StrategyUpdateOne {
	if v != nil {
		_u.SetEnableAutoBuy(*v)
	}
	return _u
}

// SetEnableAutoSell sets the "enableAutoSell" field.
func (_u *StrategyUpdateOne) SetEnableAutoSell(v bool) *StrategyUpdateOne {
	_u.mutation.SetEnableAutoSell(v)
	return _u
}

// SetNillableEnableAutoSell sets the "enableAutoSell" field if the given value is not nil.
func (_u *StrategyUpdateOne) SetNillableEnableAutoSell(v *bool) *StrategyUpdateOne {
	if v != nil {
		_u.SetEnableAutoSell(*v)
	}
	return _u
}

// SetEnableAutoExit sets the "enableAutoExit" field.
func (_u *StrategyUpdateOne) SetEnableAutoExit(v bool) *StrategyUpdateOne {
	_u.mutation.SetEnableAutoExit(v)
	return _u
}

// SetNillableEnableAutoExit sets the "enableAutoExit" field if the given value is not nil.
func (_u *StrategyUpdateOne) SetNillableEnableAutoExit(v *bool) *StrategyUpdateOne {
	if v != nil {
		_u.SetEnableAutoExit(*v)
	}
	return _u
}

// SetEnablePushNotification sets the "enablePushNotification" field.
func (_u *StrategyUpdateOne) SetEnablePushNotification(v bool) *StrategyUpdateOne {
	_u.mutation.SetEnablePushNotification(v)
	return _u
}

// SetNillableEnablePushNotification sets the "enablePushNotification" field if the given value is not nil.
func (_u *StrategyUpdateOne) SetNillableEnablePushNotification(v *bool) *StrategyUpdateOne {
	if v != nil {
		_u.SetEnablePushNotification(*v)
	}
	return _u
}

// SetLastLowerThresholdAlertTime sets the "lastLowerThresholdAlertTime" field.
func (_u *StrategyUpdateOne) SetLastLowerThresholdAlertTime(v time.Time) *StrategyUpdateOne {
	_u.mutation.SetLastLowerThresholdAlertTime(v)
	return _u
}

// SetNillableLastLowerThresholdAlertTime sets the "lastLowerThresholdAlertTime" field if the given value is not nil.
func (_u *StrategyUpdateOne) SetNillableLastLowerThresholdAlertTime(v *time.Time) *StrategyUpdateOne {
	if v != nil {
		_u.SetLastLowerThresholdAlertTime(*v)
	}
	return _u
}

// ClearLastLowerThresholdAlertTime clears the value of the "lastLowerThresholdAlertTime" field.
func (_u *StrategyUpdateOne) ClearLastLowerThresholdAlertTime() *StrategyUpdateOne {
	_u.mutation.ClearLastLowerThresholdAlertTime()
	return _u
}

// SetLastUpperThresholdAlertTime sets the "lastUpperThresholdAlertTime" field.
func (_u *StrategyUpdateOne) SetLastUpperThresholdAlertTime(v time.Time) *StrategyUpdateOne {
	_u.mutation.SetLastUpperThresholdAlertTime(v)
	return _u
}

// SetNillableLastUpperThresholdAlertTime sets the "lastUpperThresholdAlertTime" field if the given value is not nil.
func (_u *StrategyUpdateOne) SetNillableLastUpperThresholdAlertTime(v *time.Time) *StrategyUpdateOne {
	if v != nil {
		_u.SetLastUpperThresholdAlertTime(*v)
	}
	return _u
}

// ClearLastUpperThresholdAlertTime clears the value of the "lastUpperThresholdAlertTime" field.
func (_u *StrategyUpdateOne) ClearLastUpperThresholdAlertTime() *StrategyUpdateOne {
	_u.mutation.ClearLastUpperThresholdAlertTime()
	return _u
}

// SetStatus sets the "status" field.
func (_u *StrategyUpdateOne) SetStatus(v strategy.Status) *StrategyUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *StrategyUpdateOne) SetNillableStatus(v *strategy.Status) *StrategyUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetExchangeApiKey sets the "exchangeApiKey" field.
func (_u *StrategyUpdateOne) SetExchangeApiKey(v string) *StrategyUpdateOne {
	_u.mutation.SetExchangeApiKey(v)
	return _u
}

// SetNillableExchangeApiKey sets the "exchangeApiKey" field if the given value is not nil.
func (_u *StrategyUpdateOne) SetNillableExchangeApiKey(v *string) *StrategyUpdateOne {
	if v != nil {
		_u.SetExchangeApiKey(*v)
	}
	return _u
}

// SetExchangeSecretKey sets the "exchangeSecretKey" field.
func (_u *StrategyUpdateOne) SetExchangeSecretKey(v string) *StrategyUpdateOne {
	_u.mutation.SetExchangeSecretKey(v)
	return _u
}

// SetNillableExchangeSecretKey sets the "exchangeSecretKey" field if the given value is not nil.
func (_u *StrategyUpdateOne) SetNillableExchangeSecretKey(v *string) *StrategyUpdateOne {
	if v != nil {
		_u.SetExchangeSecretKey(*v)
	}
	return _u
}

// SetExchangePassphrase sets the "exchangePassphrase" field.
func (_u *StrategyUpdateOne) SetExchangePassphrase(v string) *StrategyUpdateOne {
	_u.mutation.SetExchangePassphrase(v)
	return _u
}

// SetNillableExchangePassphrase sets the "exchangePassphrase" field if the given value is not nil.
func (_u *StrategyUpdateOne) SetNillableExchangePassphrase(v *string) *StrategyUpdateOne {
	if v != nil {
		_u.SetExchangePassphrase(*v)
	}
	return _u
}

// Mutation returns the StrategyMutation object of the builder.
func (_u *StrategyUpdateOne) Mutation() *StrategyMutation {
	return _u.mutation
}

// Where appends a list predicates to the StrategyUpdate builder.
func (_u *StrategyUpdateOne) Where(ps ...predicate.Strategy) *StrategyUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *StrategyUpdateOne) Select(field string, fields ...string) *StrategyUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Strategy entity.
func (_u *StrategyUpdateOne) Save(ctx context.Context) (*Strategy, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *StrategyUpdateOne) SaveX(ctx context.Context) *Strategy {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *StrategyUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *StrategyUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *StrategyUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdateTime(); !ok {
		v := strategy.UpdateDefaultUpdateTime()
		_u.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *StrategyUpdateOne) check() error {
	if v, ok := _u.mutation.GUID(); ok {
		if err := strategy.GUIDValidator(v); err != nil {
			return &ValidationError{Name: "guid", err: fmt.Errorf(`ent: validator failed for field "Strategy.guid": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Exchange(); ok {
		if err := strategy.ExchangeValidator(v); err != nil {
			return &ValidationError{Name: "exchange", err: fmt.Errorf(`ent: validator failed for field "Strategy.exchange": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Symbol(); ok {
		if err := strategy.SymbolValidator(v); err != nil {
			return &ValidationError{Name: "symbol", err: fmt.Errorf(`ent: validator failed for field "Strategy.symbol": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Mode(); ok {
		if err := strategy.ModeValidator(v); err != nil {
			return &ValidationError{Name: "mode", err: fmt.Errorf(`ent: validator failed for field "Strategy.mode": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MarginMode(); ok {
		if err := strategy.MarginModeValidator(v); err != nil {
			return &ValidationError{Name: "marginMode", err: fmt.Errorf(`ent: validator failed for field "Strategy.marginMode": %w`, err)}
		}
	}
	if v, ok := _u.mutation.QuantityMode(); ok {
		if err := strategy.QuantityModeValidator(v); err != nil {
			return &ValidationError{Name: "quantityMode", err: fmt.Errorf(`ent: validator failed for field "Strategy.quantityMode": %w`, err)}
		}
	}
	if v, ok := _u.mutation.GridNum(); ok {
		if err := strategy.GridNumValidator(v); err != nil {
			return &ValidationError{Name: "gridNum", err: fmt.Errorf(`ent: validator failed for field "Strategy.gridNum": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Leverage(); ok {
		if err := strategy.LeverageValidator(v); err != nil {
			return &ValidationError{Name: "leverage", err: fmt.Errorf(`ent: validator failed for field "Strategy.leverage": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := strategy.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Strategy.status": %w`, err)}
		}
	}
	return nil
}

func (_u *StrategyUpdateOne) sqlSave(ctx context.Context) (_node *Strategy, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(strategy.Table, strategy.Columns, sqlgraph.NewFieldSpec(strategy.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Strategy.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, strategy.FieldID)
		for _, f := range fields {
			if !strategy.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != strategy.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(strategy.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.GUID(); ok {
		_spec.SetField(strategy.FieldGUID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Exchange(); ok {
		_spec.SetField(strategy.FieldExchange, field.TypeString, value)
	}
	if value, ok := _u.mutation.Symbol(); ok {
		_spec.SetField(strategy.FieldSymbol, field.TypeString, value)
	}
	if value, ok := _u.mutation.Account(); ok {
		_spec.SetField(strategy.FieldAccount, field.TypeString, value)
	}
	if value, ok := _u.mutation.Mode(); ok {
		_spec.SetField(strategy.FieldMode, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.MarginMode(); ok {
		_spec.SetField(strategy.FieldMarginMode, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.QuantityMode(); ok {
		_spec.SetField(strategy.FieldQuantityMode, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.PriceUpper(); ok {
		_spec.SetField(strategy.FieldPriceUpper, field.TypeString, value)
	}
	if value, ok := _u.mutation.PriceLower(); ok {
		_spec.SetField(strategy.FieldPriceLower, field.TypeString, value)
	}
	if value, ok := _u.mutation.GridNum(); ok {
		_spec.SetField(strategy.FieldGridNum, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedGridNum(); ok {
		_spec.AddField(strategy.FieldGridNum, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Leverage(); ok {
		_spec.SetField(strategy.FieldLeverage, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedLeverage(); ok {
		_spec.AddField(strategy.FieldLeverage, field.TypeInt, value)
	}
	if value, ok := _u.mutation.InitialOrderSize(); ok {
		_spec.SetField(strategy.FieldInitialOrderSize, field.TypeString, value)
	}
	if value, ok := _u.mutation.StopLossRatio(); ok {
		_spec.SetField(strategy.FieldStopLossRatio, field.TypeString, value)
	}
	if value, ok := _u.mutation.TakeProfitRatio(); ok {
		_spec.SetField(strategy.FieldTakeProfitRatio, field.TypeString, value)
	}
	if value, ok := _u.mutation.EnableAutoBuy(); ok {
		_spec.SetField(strategy.FieldEnableAutoBuy, field.TypeBool, value)
	}
	if value, ok := _u.mutation.EnableAutoSell(); ok {
		_spec.SetField(strategy.FieldEnableAutoSell, field.TypeBool, value)
	}
	if value, ok := _u.mutation.EnableAutoExit(); ok {
		_spec.SetField(strategy.FieldEnableAutoExit, field.TypeBool, value)
	}
	if value, ok := _u.mutation.EnablePushNotification(); ok {
		_spec.SetField(strategy.FieldEnablePushNotification, field.TypeBool, value)
	}
	if value, ok := _u.mutation.LastLowerThresholdAlertTime(); ok {
		_spec.SetField(strategy.FieldLastLowerThresholdAlertTime, field.TypeTime, value)
	}
	if _u.mutation.LastLowerThresholdAlertTimeCleared() {
		_spec.ClearField(strategy.FieldLastLowerThresholdAlertTime, field.TypeTime)
	}
	if value, ok := _u.mutation.LastUpperThresholdAlertTime(); ok {
		_spec.SetField(strategy.FieldLastUpperThresholdAlertTime, field.TypeTime, value)
	}
	if _u.mutation.LastUpperThresholdAlertTimeCleared() {
		_spec.ClearField(strategy.FieldLastUpperThresholdAlertTime, field.TypeTime)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(strategy.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ExchangeApiKey(); ok {
		_spec.SetField(strategy.FieldExchangeApiKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExchangeSecretKey(); ok {
		_spec.SetField(strategy.FieldExchangeSecretKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExchangePassphrase(); ok {
		_spec.SetField(strategy.FieldExchangePassphrase, field.TypeString, value)
	}
	_node = &Strategy{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{strategy.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
