// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/fachebot/perp-dex-grid-bot/internal/ent/strategy"
	"github.com/shopspring/decimal"
)

// StrategyCreate is the builder for creating a Strategy entity.
type StrategyCreate struct {
	config
	mutation *StrategyMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreateTime sets the "create_time" field.
func (_c *StrategyCreate) SetCreateTime(v time.Time) *StrategyCreate {
	_c.mutation.SetCreateTime(v)
	return _c
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (_c *StrategyCreate) SetNillableCreateTime(v *time.Time) *StrategyCreate {
	if v != nil {
		_c.SetCreateTime(*v)
	}
	return _c
}

// SetUpdateTime sets the "update_time" field.
func (_c *StrategyCreate) SetUpdateTime(v time.Time) *StrategyCreate {
	_c.mutation.SetUpdateTime(v)
	return _c
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (_c *StrategyCreate) SetNillableUpdateTime(v *time.Time) *StrategyCreate {
	if v != nil {
		_c.SetUpdateTime(*v)
	}
	return _c
}

// SetGUID sets the "guid" field.
func (_c *StrategyCreate) SetGUID(v string) *StrategyCreate {
	_c.mutation.SetGUID(v)
	return _c
}

// SetOwner sets the "owner" field.
func (_c *StrategyCreate) SetOwner(v int64) *StrategyCreate {
	_c.mutation.SetOwner(v)
	return _c
}

// SetExchange sets the "exchange" field.
func (_c *StrategyCreate) SetExchange(v string) *StrategyCreate {
	_c.mutation.SetExchange(v)
	return _c
}

// SetSymbol sets the "symbol" field.
func (_c *StrategyCreate) SetSymbol(v string) *StrategyCreate {
	_c.mutation.SetSymbol(v)
	return _c
}

// SetAccount sets the "account" field.
func (_c *StrategyCreate) SetAccount(v string) *StrategyCreate {
	_c.mutation.SetAccount(v)
	return _c
}

// SetMode sets the "mode" field.
func (_c *StrategyCreate) SetMode(v strategy.Mode) *StrategyCreate {
	_c.mutation.SetMode(v)
	return _c
}

// SetMarginMode sets the "marginMode" field.
func (_c *StrategyCreate) SetMarginMode(v strategy.MarginMode) *StrategyCreate {
	_c.mutation.SetMarginMode(v)
	return _c
}

// SetQuantityMode sets the "quantityMode" field.
func (_c *StrategyCreate) SetQuantityMode(v strategy.QuantityMode) *StrategyCreate {
	_c.mutation.SetQuantityMode(v)
	return _c
}

// SetPriceUpper sets the "priceUpper" field.
func (_c *StrategyCreate) SetPriceUpper(v decimal.Decimal) *StrategyCreate {
	_c.mutation.SetPriceUpper(v)
	return _c
}

// SetPriceLower sets the "priceLower" field.
func (_c *StrategyCreate) SetPriceLower(v decimal.Decimal) *StrategyCreate {
	_c.mutation.SetPriceLower(v)
	return _c
}

// SetGridNum sets the "gridNum" field.
func (_c *StrategyCreate) SetGridNum(v int) *StrategyCreate {
	_c.mutation.SetGridNum(v)
	return _c
}

// SetNillableGridNum sets the "gridNum" field if the given value is not nil.
func (_c *StrategyCreate) SetNillableGridNum(v *int) *StrategyCreate {
	if v != nil {
		_c.SetGridNum(*v)
	}
	return _c
}

// SetLeverage sets the "leverage" field.
func (_c *StrategyCreate) SetLeverage(v int) *StrategyCreate {
	_c.mutation.SetLeverage(v)
	return _c
}

// SetNillableLeverage sets the "leverage" field if the given value is not nil.
func (_c *StrategyCreate) SetNillableLeverage(v *int) *StrategyCreate {
	if v != nil {
		_c.SetLeverage(*v)
	}
	return _c
}

// SetInitialOrderSize sets the "initialOrderSize" field.
func (_c *StrategyCreate) SetInitialOrderSize(v decimal.Decimal) *StrategyCreate {
	_c.mutation.SetInitialOrderSize(v)
	return _c
}

// SetStopLossRatio sets the "stopLossRatio" field.
func (_c *StrategyCreate) SetStopLossRatio(v decimal.Decimal) *StrategyCreate {
	_c.mutation.SetStopLossRatio(v)
	return _c
}

// SetTakeProfitRatio sets the "takeProfitRatio" field.
func (_c *StrategyCreate) SetTakeProfitRatio(v decimal.Decimal) *StrategyCreate {
	_c.mutation.SetTakeProfitRatio(v)
	return _c
}

// SetEnableAutoExit sets the "enableAutoExit" field.
func (_c *StrategyCreate) SetEnableAutoExit(v bool) *StrategyCreate {
	_c.mutation.SetEnableAutoExit(v)
	return _c
}

// SetEnablePushNotification sets the "enablePushNotification" field.
func (_c *StrategyCreate) SetEnablePushNotification(v bool) *StrategyCreate {
	_c.mutation.SetEnablePushNotification(v)
	return _c
}

// SetLastLowerThresholdAlertTime sets the "lastLowerThresholdAlertTime" field.
func (_c *StrategyCreate) SetLastLowerThresholdAlertTime(v time.Time) *StrategyCreate {
	_c.mutation.SetLastLowerThresholdAlertTime(v)
	return _c
}

// SetNillableLastLowerThresholdAlertTime sets the "lastLowerThresholdAlertTime" field if the given value is not nil.
func (_c *StrategyCreate) SetNillableLastLowerThresholdAlertTime(v *time.Time) *StrategyCreate {
	if v != nil {
		_c.SetLastLowerThresholdAlertTime(*v)
	}
	return _c
}

// SetLastUpperThresholdAlertTime sets the "lastUpperThresholdAlertTime" field.
func (_c *StrategyCreate) SetLastUpperThresholdAlertTime(v time.Time) *StrategyCreate {
	_c.mutation.SetLastUpperThresholdAlertTime(v)
	return _c
}

// SetNillableLastUpperThresholdAlertTime sets the "lastUpperThresholdAlertTime" field if the given value is not nil.
func (_c *StrategyCreate) SetNillableLastUpperThresholdAlertTime(v *time.Time) *StrategyCreate {
	if v != nil {
		_c.SetLastUpperThresholdAlertTime(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *StrategyCreate) SetStatus(v strategy.Status) *StrategyCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetExchangeApiKey sets the "exchangeApiKey" field.
func (_c *StrategyCreate) SetExchangeApiKey(v string) *StrategyCreate {
	_c.mutation.SetExchangeApiKey(v)
	return _c
}

// SetExchangeSecretKey sets the "exchangeSecretKey" field.
func (_c *StrategyCreate) SetExchangeSecretKey(v string) *StrategyCreate {
	_c.mutation.SetExchangeSecretKey(v)
	return _c
}

// SetExchangePassphrase sets the "exchangePassphrase" field.
func (_c *StrategyCreate) SetExchangePassphrase(v string) *StrategyCreate {
	_c.mutation.SetExchangePassphrase(v)
	return _c
}

// Mutation returns the StrategyMutation object of the builder.
func (_c *StrategyCreate) Mutation() *StrategyMutation {
	return _c.mutation
}

// Save creates the Strategy in the database.
func (_c *StrategyCreate) Save(ctx context.Context) (*Strategy, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *StrategyCreate) SaveX(ctx context.Context) *Strategy {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *StrategyCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *StrategyCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *StrategyCreate) defaults() {
	if _, ok := _c.mutation.CreateTime(); !ok {
		v := strategy.DefaultCreateTime()
		_c.mutation.SetCreateTime(v)
	}
	if _, ok := _c.mutation.UpdateTime(); !ok {
		v := strategy.DefaultUpdateTime()
		_c.mutation.SetUpdateTime(v)
	}
	if _, ok := _c.mutation.GridNum(); !ok {
		v := strategy.DefaultGridNum
		_c.mutation.SetGridNum(v)
	}
	if _, ok := _c.mutation.Leverage(); !ok {
		v := strategy.DefaultLeverage
		_c.mutation.SetLeverage(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *StrategyCreate) check() error {
	if _, ok := _c.mutation.CreateTime(); !ok {
		return &ValidationError{Name: "create_time", err: errors.New(`ent: missing required field "Strategy.create_time"`)}
	}
	if _, ok := _c.mutation.UpdateTime(); !ok {
		return &ValidationError{Name: "update_time", err: errors.New(`ent: missing required field "Strategy.update_time"`)}
	}
	if _, ok := _c.mutation.GUID(); !ok {
		return &ValidationError{Name: "guid", err: errors.New(`ent: missing required field "Strategy.guid"`)}
	}
	if v, ok := _c.mutation.GUID(); ok {
		if err := strategy.GUIDValidator(v); err != nil {
			return &ValidationError{Name: "guid", err: fmt.Errorf(`ent: validator failed for field "Strategy.guid": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Owner(); !ok {
		return &ValidationError{Name: "owner", err: errors.New(`ent: missing required field "Strategy.owner"`)}
	}
	if _, ok := _c.mutation.Exchange(); !ok {
		return &ValidationError{Name: "exchange", err: errors.New(`ent: missing required field "Strategy.exchange"`)}
	}
	if v, ok := _c.mutation.Exchange(); ok {
		if err := strategy.ExchangeValidator(v); err != nil {
			return &ValidationError{Name: "exchange", err: fmt.Errorf(`ent: validator failed for field "Strategy.exchange": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Symbol(); !ok {
		return &ValidationError{Name: "symbol", err: errors.New(`ent: missing required field "Strategy.symbol"`)}
	}
	if v, ok := _c.mutation.Symbol(); ok {
		if err := strategy.SymbolValidator(v); err != nil {
			return &ValidationError{Name: "symbol", err: fmt.Errorf(`ent: validator failed for field "Strategy.symbol": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Account(); !ok {
		return &ValidationError{Name: "account", err: errors.New(`ent: missing required field "Strategy.account"`)}
	}
	if _, ok := _c.mutation.Mode(); !ok {
		return &ValidationError{Name: "mode", err: errors.New(`ent: missing required field "Strategy.mode"`)}
	}
	if v, ok := _c.mutation.Mode(); ok {
		if err := strategy.ModeValidator(v); err != nil {
			return &ValidationError{Name: "mode", err: fmt.Errorf(`ent: validator failed for field "Strategy.mode": %w`, err)}
		}
	}
	if _, ok := _c.mutation.MarginMode(); !ok {
		return &ValidationError{Name: "marginMode", err: errors.New(`ent: missing required field "Strategy.marginMode"`)}
	}
	if v, ok := _c.mutation.MarginMode(); ok {
		if err := strategy.MarginModeValidator(v); err != nil {
			return &ValidationError{Name: "marginMode", err: fmt.Errorf(`ent: validator failed for field "Strategy.marginMode": %w`, err)}
		}
	}
	if _, ok := _c.mutation.QuantityMode(); !ok {
		return &ValidationError{Name: "quantityMode", err: errors.New(`ent: missing required field "Strategy.quantityMode"`)}
	}
	if v, ok := _c.mutation.QuantityMode(); ok {
		if err := strategy.QuantityModeValidator(v); err != nil {
			return &ValidationError{Name: "quantityMode", err: fmt.Errorf(`ent: validator failed for field "Strategy.quantityMode": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PriceUpper(); !ok {
		return &ValidationError{Name: "priceUpper", err: errors.New(`ent: missing required field "Strategy.priceUpper"`)}
	}
	if _, ok := _c.mutation.PriceLower(); !ok {
		return &ValidationError{Name: "priceLower", err: errors.New(`ent: missing required field "Strategy.priceLower"`)}
	}
	if _, ok := _c.mutation.GridNum(); !ok {
		return &ValidationError{Name: "gridNum", err: errors.New(`ent: missing required field "Strategy.gridNum"`)}
	}
	if v, ok := _c.mutation.GridNum(); ok {
		if err := strategy.GridNumValidator(v); err != nil {
			return &ValidationError{Name: "gridNum", err: fmt.Errorf(`ent: validator failed for field "Strategy.gridNum": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Leverage(); !ok {
		return &ValidationError{Name: "leverage", err: errors.New(`ent: missing required field "Strategy.leverage"`)}
	}
	if v, ok := _c.mutation.Leverage(); ok {
		if err := strategy.LeverageValidator(v); err != nil {
			return &ValidationError{Name: "leverage", err: fmt.Errorf(`ent: validator failed for field "Strategy.leverage": %w`, err)}
		}
	}
	if _, ok := _c.mutation.InitialOrderSize(); !ok {
		return &ValidationError{Name: "initialOrderSize", err: errors.New(`ent: missing required field "Strategy.initialOrderSize"`)}
	}
	if _, ok := _c.mutation.StopLossRatio(); !ok {
		return &ValidationError{Name: "stopLossRatio", err: errors.New(`ent: missing required field "Strategy.stopLossRatio"`)}
	}
	if _, ok := _c.mutation.TakeProfitRatio(); !ok {
		return &ValidationError{Name: "takeProfitRatio", err: errors.New(`ent: missing required field "Strategy.takeProfitRatio"`)}
	}
	if _, ok := _c.mutation.EnableAutoExit(); !ok {
		return &ValidationError{Name: "enableAutoExit", err: errors.New(`ent: missing required field "Strategy.enableAutoExit"`)}
	}
	if _, ok := _c.mutation.EnablePushNotification(); !ok {
		return &ValidationError{Name: "enablePushNotification", err: errors.New(`ent: missing required field "Strategy.enablePushNotification"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Strategy.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := strategy.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Strategy.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ExchangeApiKey(); !ok {
		return &ValidationError{Name: "exchangeApiKey", err: errors.New(`ent: missing required field "Strategy.exchangeApiKey"`)}
	}
	if _, ok := _c.mutation.ExchangeSecretKey(); !ok {
		return &ValidationError{Name: "exchangeSecretKey", err: errors.New(`ent: missing required field "Strategy.exchangeSecretKey"`)}
	}
	if _, ok := _c.mutation.ExchangePassphrase(); !ok {
		return &ValidationError{Name: "exchangePassphrase", err: errors.New(`ent: missing required field "Strategy.exchangePassphrase"`)}
	}
	return nil
}

func (_c *StrategyCreate) sqlSave(ctx context.Context) (*Strategy, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *StrategyCreate) createSpec() (*Strategy, *sqlgraph.CreateSpec) {
	var (
		_node = &Strategy{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(strategy.Table, sqlgraph.NewFieldSpec(strategy.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreateTime(); ok {
		_spec.SetField(strategy.FieldCreateTime, field.TypeTime, value)
		_node.CreateTime = value
	}
	if value, ok := _c.mutation.UpdateTime(); ok {
		_spec.SetField(strategy.FieldUpdateTime, field.TypeTime, value)
		_node.UpdateTime = value
	}
	if value, ok := _c.mutation.GUID(); ok {
		_spec.SetField(strategy.FieldGUID, field.TypeString, value)
		_node.GUID = value
	}
	if value, ok := _c.mutation.Owner(); ok {
		_spec.SetField(strategy.FieldOwner, field.TypeInt64, value)
		_node.Owner = value
	}
	if value, ok := _c.mutation.Exchange(); ok {
		_spec.SetField(strategy.FieldExchange, field.TypeString, value)
		_node.Exchange = value
	}
	if value, ok := _c.mutation.Symbol(); ok {
		_spec.SetField(strategy.FieldSymbol, field.TypeString, value)
		_node.Symbol = value
	}
	if value, ok := _c.mutation.Account(); ok {
		_spec.SetField(strategy.FieldAccount, field.TypeString, value)
		_node.Account = value
	}
	if value, ok := _c.mutation.Mode(); ok {
		_spec.SetField(strategy.FieldMode, field.TypeEnum, value)
		_node.Mode = value
	}
	if value, ok := _c.mutation.MarginMode(); ok {
		_spec.SetField(strategy.FieldMarginMode, field.TypeEnum, value)
		_node.MarginMode = value
	}
	if value, ok := _c.mutation.QuantityMode(); ok {
		_spec.SetField(strategy.FieldQuantityMode, field.TypeEnum, value)
		_node.QuantityMode = value
	}
	if value, ok := _c.mutation.PriceUpper(); ok {
		_spec.SetField(strategy.FieldPriceUpper, field.TypeString, value)
		_node.PriceUpper = value
	}
	if value, ok := _c.mutation.PriceLower(); ok {
		_spec.SetField(strategy.FieldPriceLower, field.TypeString, value)
		_node.PriceLower = value
	}
	if value, ok := _c.mutation.GridNum(); ok {
		_spec.SetField(strategy.FieldGridNum, field.TypeInt, value)
		_node.GridNum = value
	}
	if value, ok := _c.mutation.Leverage(); ok {
		_spec.SetField(strategy.FieldLeverage, field.TypeInt, value)
		_node.Leverage = value
	}
	if value, ok := _c.mutation.InitialOrderSize(); ok {
		_spec.SetField(strategy.FieldInitialOrderSize, field.TypeString, value)
		_node.InitialOrderSize = value
	}
	if value, ok := _c.mutation.StopLossRatio(); ok {
		_spec.SetField(strategy.FieldStopLossRatio, field.TypeString, value)
		_node.StopLossRatio = value
	}
	if value, ok := _c.mutation.TakeProfitRatio(); ok {
		_spec.SetField(strategy.FieldTakeProfitRatio, field.TypeString, value)
		_node.TakeProfitRatio = value
	}
	if value, ok := _c.mutation.EnableAutoExit(); ok {
		_spec.SetField(strategy.FieldEnableAutoExit, field.TypeBool, value)
		_node.EnableAutoExit = value
	}
	if value, ok := _c.mutation.EnablePushNotification(); ok {
		_spec.SetField(strategy.FieldEnablePushNotification, field.TypeBool, value)
		_node.EnablePushNotification = value
	}
	if value, ok := _c.mutation.LastLowerThresholdAlertTime(); ok {
		_spec.SetField(strategy.FieldLastLowerThresholdAlertTime, field.TypeTime, value)
		_node.LastLowerThresholdAlertTime = &value
	}
	if value, ok := _c.mutation.LastUpperThresholdAlertTime(); ok {
		_spec.SetField(strategy.FieldLastUpperThresholdAlertTime, field.TypeTime, value)
		_node.LastUpperThresholdAlertTime = &value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(strategy.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.ExchangeApiKey(); ok {
		_spec.SetField(strategy.FieldExchangeApiKey, field.TypeString, value)
		_node.ExchangeApiKey = value
	}
	if value, ok := _c.mutation.ExchangeSecretKey(); ok {
		_spec.SetField(strategy.FieldExchangeSecretKey, field.TypeString, value)
		_node.ExchangeSecretKey = value
	}
	if value, ok := _c.mutation.ExchangePassphrase(); ok {
		_spec.SetField(strategy.FieldExchangePassphrase, field.TypeString, value)
		_node.ExchangePassphrase = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Strategy.Create().
//		SetCreateTime(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.StrategyUpsert) {
//			SetCreateTime(v+v).
//		}).
//		Exec(ctx)
func (_c *StrategyCreate) OnConflict(opts ...sql.ConflictOption) *StrategyUpsertOne {
	_c.conflict = opts
	return &StrategyUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Strategy.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *StrategyCreate) OnConflictColumns(columns ...string) *StrategyUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &StrategyUpsertOne{
		create: _c,
	}
}

type (
	// StrategyUpsertOne is the builder for "upsert"-ing
	//  one Strategy node.
	StrategyUpsertOne struct {
		create *StrategyCreate
	}

	// StrategyUpsert is the "OnConflict" setter.
	StrategyUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdateTime sets the "update_time" field.
func (u *StrategyUpsert) SetUpdateTime(v time.Time) *StrategyUpsert {
	u.Set(strategy.FieldUpdateTime, v)
	return u
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *StrategyUpsert) UpdateUpdateTime() *StrategyUpsert {
	u.SetExcluded(strategy.FieldUpdateTime)
	return u
}

// SetGUID sets the "guid" field.
func (u *StrategyUpsert) SetGUID(v string) *StrategyUpsert {
	u.Set(strategy.FieldGUID, v)
	return u
}

// UpdateGUID sets the "guid" field to the value that was provided on create.
func (u *StrategyUpsert) UpdateGUID() *StrategyUpsert {
	u.SetExcluded(strategy.FieldGUID)
	return u
}

// SetOwner sets the "owner" field.
func (u *StrategyUpsert) SetOwner(v int64) *StrategyUpsert {
	u.Set(strategy.FieldOwner, v)
	return u
}

// UpdateOwner sets the "owner" field to the value that was provided on create.
func (u *StrategyUpsert) UpdateOwner() *StrategyUpsert {
	u.SetExcluded(strategy.FieldOwner)
	return u
}

// AddOwner adds v to the "owner" field.
func (u *StrategyUpsert) AddOwner(v int64) *StrategyUpsert {
	u.Add(strategy.FieldOwner, v)
	return u
}

// SetExchange sets the "exchange" field.
func (u *StrategyUpsert) SetExchange(v string) *StrategyUpsert {
	u.Set(strategy.FieldExchange, v)
	return u
}

// UpdateExchange sets the "exchange" field to the value that was provided on create.
func (u *StrategyUpsert) UpdateExchange() *StrategyUpsert {
	u.SetExcluded(strategy.FieldExchange)
	return u
}

// SetSymbol sets the "symbol" field.
func (u *StrategyUpsert) SetSymbol(v string) *StrategyUpsert {
	u.Set(strategy.FieldSymbol, v)
	return u
}

// UpdateSymbol sets the "symbol" field to the value that was provided on create.
func (u *StrategyUpsert) UpdateSymbol() *StrategyUpsert {
	u.SetExcluded(strategy.FieldSymbol)
	return u
}

// SetAccount sets the "account" field.
func (u *StrategyUpsert) SetAccount(v string) *StrategyUpsert {
	u.Set(strategy.FieldAccount, v)
	return u
}

// UpdateAccount sets the "account" field to the value that was provided on create.
func (u *StrategyUpsert) UpdateAccount() *StrategyUpsert {
	u.SetExcluded(strategy.FieldAccount)
	return u
}

// SetMode sets the "mode" field.
func (u *StrategyUpsert) SetMode(v strategy.Mode) *StrategyUpsert {
	u.Set(strategy.FieldMode, v)
	return u
}

// UpdateMode sets the "mode" field to the value that was provided on create.
func (u *StrategyUpsert) UpdateMode() *StrategyUpsert {
	u.SetExcluded(strategy.FieldMode)
	return u
}

// SetMarginMode sets the "marginMode" field.
func (u *StrategyUpsert) SetMarginMode(v strategy.MarginMode) *StrategyUpsert {
	u.Set(strategy.FieldMarginMode, v)
	return u
}

// UpdateMarginMode sets the "marginMode" field to the value that was provided on create.
func (u *StrategyUpsert) UpdateMarginMode() *StrategyUpsert {
	u.SetExcluded(strategy.FieldMarginMode)
	return u
}

// SetQuantityMode sets the "quantityMode" field.
func (u *StrategyUpsert) SetQuantityMode(v strategy.QuantityMode) *StrategyUpsert {
	u.Set(strategy.FieldQuantityMode, v)
	return u
}

// UpdateQuantityMode sets the "quantityMode" field to the value that was provided on create.
func (u *StrategyUpsert) UpdateQuantityMode() *StrategyUpsert {
	u.SetExcluded(strategy.FieldQuantityMode)
	return u
}

// SetPriceUpper sets the "priceUpper" field.
func (u *StrategyUpsert) SetPriceUpper(v decimal.Decimal) *StrategyUpsert {
	u.Set(strategy.FieldPriceUpper, v)
	return u
}

// UpdatePriceUpper sets the "priceUpper" field to the value that was provided on create.
func (u *StrategyUpsert) UpdatePriceUpper() *StrategyUpsert {
	u.SetExcluded(strategy.FieldPriceUpper)
	return u
}

// SetPriceLower sets the "priceLower" field.
func (u *StrategyUpsert) SetPriceLower(v decimal.Decimal) *StrategyUpsert {
	u.Set(strategy.FieldPriceLower, v)
	return u
}

// UpdatePriceLower sets the "priceLower" field to the value that was provided on create.
func (u *StrategyUpsert) UpdatePriceLower() *StrategyUpsert {
	u.SetExcluded(strategy.FieldPriceLower)
	return u
}

// SetGridNum sets the "gridNum" field.
func (u *StrategyUpsert) SetGridNum(v int) *StrategyUpsert {
	u.Set(strategy.FieldGridNum, v)
	return u
}

// UpdateGridNum sets the "gridNum" field to the value that was provided on create.
func (u *StrategyUpsert) UpdateGridNum() *StrategyUpsert {
	u.SetExcluded(strategy.FieldGridNum)
	return u
}

// AddGridNum adds v to the "gridNum" field.
func (u *StrategyUpsert) AddGridNum(v int) *StrategyUpsert {
	u.Add(strategy.FieldGridNum, v)
	return u
}

// SetLeverage sets the "leverage" field.
func (u *StrategyUpsert) SetLeverage(v int) *StrategyUpsert {
	u.Set(strategy.FieldLeverage, v)
	return u
}

// UpdateLeverage sets the "leverage" field to the value that was provided on create.
func (u *StrategyUpsert) UpdateLeverage() *StrategyUpsert {
	u.SetExcluded(strategy.FieldLeverage)
	return u
}

// AddLeverage adds v to the "leverage" field.
func (u *StrategyUpsert) AddLeverage(v int) *StrategyUpsert {
	u.Add(strategy.FieldLeverage, v)
	return u
}

// SetInitialOrderSize sets the "initialOrderSize" field.
func (u *StrategyUpsert) SetInitialOrderSize(v decimal.Decimal) *StrategyUpsert {
	u.Set(strategy.FieldInitialOrderSize, v)
	return u
}

// UpdateInitialOrderSize sets the "initialOrderSize" field to the value that was provided on create.
func (u *StrategyUpsert) UpdateInitialOrderSize() *StrategyUpsert {
	u.SetExcluded(strategy.FieldInitialOrderSize)
	return u
}

// SetStopLossRatio sets the "stopLossRatio" field.
func (u *StrategyUpsert) SetStopLossRatio(v decimal.Decimal) *StrategyUpsert {
	u.Set(strategy.FieldStopLossRatio, v)
	return u
}

// UpdateStopLossRatio sets the "stopLossRatio" field to the value that was provided on create.
func (u *StrategyUpsert) UpdateStopLossRatio() *StrategyUpsert {
	u.SetExcluded(strategy.FieldStopLossRatio)
	return u
}

// SetTakeProfitRatio sets the "takeProfitRatio" field.
func (u *StrategyUpsert) SetTakeProfitRatio(v decimal.Decimal) *StrategyUpsert {
	u.Set(strategy.FieldTakeProfitRatio, v)
	return u
}

// UpdateTakeProfitRatio sets the "takeProfitRatio" field to the value that was provided on create.
func (u *StrategyUpsert) UpdateTakeProfitRatio() *StrategyUpsert {
	u.SetExcluded(strategy.FieldTakeProfitRatio)
	return u
}

// SetEnableAutoExit sets the "enableAutoExit" field.
func (u *StrategyUpsert) SetEnableAutoExit(v bool) *StrategyUpsert {
	u.Set(strategy.FieldEnableAutoExit, v)
	return u
}

// UpdateEnableAutoExit sets the "enableAutoExit" field to the value that was provided on create.
func (u *StrategyUpsert) UpdateEnableAutoExit() *StrategyUpsert {
	u.SetExcluded(strategy.FieldEnableAutoExit)
	return u
}

// SetEnablePushNotification sets the "enablePushNotification" field.
func (u *StrategyUpsert) SetEnablePushNotification(v bool) *StrategyUpsert {
	u.Set(strategy.FieldEnablePushNotification, v)
	return u
}

// UpdateEnablePushNotification sets the "enablePushNotification" field to the value that was provided on create.
func (u *StrategyUpsert) UpdateEnablePushNotification() *StrategyUpsert {
	u.SetExcluded(strategy.FieldEnablePushNotification)
	return u
}

// SetLastLowerThresholdAlertTime sets the "lastLowerThresholdAlertTime" field.
func (u *StrategyUpsert) SetLastLowerThresholdAlertTime(v time.Time) *StrategyUpsert {
	u.Set(strategy.FieldLastLowerThresholdAlertTime, v)
	return u
}

// UpdateLastLowerThresholdAlertTime sets the "lastLowerThresholdAlertTime" field to the value that was provided on create.
func (u *StrategyUpsert) UpdateLastLowerThresholdAlertTime() *StrategyUpsert {
	u.SetExcluded(strategy.FieldLastLowerThresholdAlertTime)
	return u
}

// ClearLastLowerThresholdAlertTime clears the value of the "lastLowerThresholdAlertTime" field.
func (u *StrategyUpsert) ClearLastLowerThresholdAlertTime() *StrategyUpsert {
	u.SetNull(strategy.FieldLastLowerThresholdAlertTime)
	return u
}

// SetLastUpperThresholdAlertTime sets the "lastUpperThresholdAlertTime" field.
func (u *StrategyUpsert) SetLastUpperThresholdAlertTime(v time.Time) *StrategyUpsert {
	u.Set(strategy.FieldLastUpperThresholdAlertTime, v)
	return u
}

// UpdateLastUpperThresholdAlertTime sets the "lastUpperThresholdAlertTime" field to the value that was provided on create.
func (u *StrategyUpsert) UpdateLastUpperThresholdAlertTime() *StrategyUpsert {
	u.SetExcluded(strategy.FieldLastUpperThresholdAlertTime)
	return u
}

// ClearLastUpperThresholdAlertTime clears the value of the "lastUpperThresholdAlertTime" field.
func (u *StrategyUpsert) ClearLastUpperThresholdAlertTime() *StrategyUpsert {
	u.SetNull(strategy.FieldLastUpperThresholdAlertTime)
	return u
}

// SetStatus sets the "status" field.
func (u *StrategyUpsert) SetStatus(v strategy.Status) *StrategyUpsert {
	u.Set(strategy.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *StrategyUpsert) UpdateStatus() *StrategyUpsert {
	u.SetExcluded(strategy.FieldStatus)
	return u
}

// SetExchangeApiKey sets the "exchangeApiKey" field.
func (u *StrategyUpsert) SetExchangeApiKey(v string) *StrategyUpsert {
	u.Set(strategy.FieldExchangeApiKey, v)
	return u
}

// UpdateExchangeApiKey sets the "exchangeApiKey" field to the value that was provided on create.
func (u *StrategyUpsert) UpdateExchangeApiKey() *StrategyUpsert {
	u.SetExcluded(strategy.FieldExchangeApiKey)
	return u
}

// SetExchangeSecretKey sets the "exchangeSecretKey" field.
func (u *StrategyUpsert) SetExchangeSecretKey(v string) *StrategyUpsert {
	u.Set(strategy.FieldExchangeSecretKey, v)
	return u
}

// UpdateExchangeSecretKey sets the "exchangeSecretKey" field to the value that was provided on create.
func (u *StrategyUpsert) UpdateExchangeSecretKey() *StrategyUpsert {
	u.SetExcluded(strategy.FieldExchangeSecretKey)
	return u
}

// SetExchangePassphrase sets the "exchangePassphrase" field.
func (u *StrategyUpsert) SetExchangePassphrase(v string) *StrategyUpsert {
	u.Set(strategy.FieldExchangePassphrase, v)
	return u
}

// UpdateExchangePassphrase sets the "exchangePassphrase" field to the value that was provided on create.
func (u *StrategyUpsert) UpdateExchangePassphrase() *StrategyUpsert {
	u.SetExcluded(strategy.FieldExchangePassphrase)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.Strategy.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *StrategyUpsertOne) UpdateNewValues() *StrategyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreateTime(); exists {
			s.SetIgnore(strategy.FieldCreateTime)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Strategy.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *StrategyUpsertOne) Ignore() *StrategyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *StrategyUpsertOne) DoNothing() *StrategyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the StrategyCreate.OnConflict
// documentation for more info.
func (u *StrategyUpsertOne) Update(set func(*StrategyUpsert)) *StrategyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&StrategyUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdateTime sets the "update_time" field.
func (u *StrategyUpsertOne) SetUpdateTime(v time.Time) *StrategyUpsertOne {
	return u.Update(func(s *StrategyUpsert) {
		s.SetUpdateTime(v)
	})
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *StrategyUpsertOne) UpdateUpdateTime() *StrategyUpsertOne {
	return u.Update(func(s *StrategyUpsert) {
		s.UpdateUpdateTime()
	})
}

// SetGUID sets the "guid" field.
func (u *StrategyUpsertOne) SetGUID(v string) *StrategyUpsertOne {
	return u.Update(func(s *StrategyUpsert) {
		s.SetGUID(v)
	})
}

// UpdateGUID sets the "guid" field to the value that was provided on create.
func (u *StrategyUpsertOne) UpdateGUID() *StrategyUpsertOne {
	return u.Update(func(s *StrategyUpsert) {
		s.UpdateGUID()
	})
}

// SetOwner sets the "owner" field.
func (u *StrategyUpsertOne) SetOwner(v int64) *StrategyUpsertOne {
	return u.Update(func(s *StrategyUpsert) {
		s.SetOwner(v)
	})
}

// AddOwner adds v to the "owner" field.
func (u *StrategyUpsertOne) AddOwner(v int64) *StrategyUpsertOne {
	return u.Update(func(s *StrategyUpsert) {
		s.AddOwner(v)
	})
}

// UpdateOwner sets the "owner" field to the value that was provided on create.
func (u *StrategyUpsertOne) UpdateOwner() *StrategyUpsertOne {
	return u.Update(func(s *StrategyUpsert) {
		s.UpdateOwner()
	})
}

// SetExchange sets the "exchange" field.
func (u *StrategyUpsertOne) SetExchange(v string) *StrategyUpsertOne {
	return u.Update(func(s *StrategyUpsert) {
		s.SetExchange(v)
	})
}

// UpdateExchange sets the "exchange" field to the value that was provided on create.
func (u *StrategyUpsertOne) UpdateExchange() *StrategyUpsertOne {
	return u.Update(func(s *StrategyUpsert) {
		s.UpdateExchange()
	})
}

// SetSymbol sets the "symbol" field.
func (u *StrategyUpsertOne) SetSymbol(v string) *StrategyUpsertOne {
	return u.Update(func(s *StrategyUpsert) {
		s.SetSymbol(v)
	})
}

// UpdateSymbol sets the "symbol" field to the value that was provided on create.
func (u *StrategyUpsertOne) UpdateSymbol() *StrategyUpsertOne {
	return u.Update(func(s *StrategyUpsert) {
		s.UpdateSymbol()
	})
}

// SetAccount sets the "account" field.
func (u *StrategyUpsertOne) SetAccount(v string) *StrategyUpsertOne {
	return u.Update(func(s *StrategyUpsert) {
		s.SetAccount(v)
	})
}

// UpdateAccount sets the "account" field to the value that was provided on create.
func (u *StrategyUpsertOne) UpdateAccount() *StrategyUpsertOne {
	return u.Update(func(s *StrategyUpsert) {
		s.UpdateAccount()
	})
}

// SetMode sets the "mode" field.
func (u *StrategyUpsertOne) SetMode(v strategy.Mode) *StrategyUpsertOne {
	return u.Update(func(s *StrategyUpsert) {
		s.SetMode(v)
	})
}

// UpdateMode sets the "mode" field to the value that was provided on create.
func (u *StrategyUpsertOne) UpdateMode() *StrategyUpsertOne {
	return u.Update(func(s *StrategyUpsert) {
		s.UpdateMode()
	})
}

// SetMarginMode sets the "marginMode" field.
func (u *StrategyUpsertOne) SetMarginMode(v strategy.MarginMode) *StrategyUpsertOne {
	return u.Update(func(s *StrategyUpsert) {
		s.SetMarginMode(v)
	})
}

// UpdateMarginMode sets the "marginMode" field to the value that was provided on create.
func (u *StrategyUpsertOne) UpdateMarginMode() *StrategyUpsertOne {
	return u.Update(func(s *StrategyUpsert) {
		s.UpdateMarginMode()
	})
}

// SetQuantityMode sets the "quantityMode" field.
func (u *StrategyUpsertOne) SetQuantityMode(v strategy.QuantityMode) *StrategyUpsertOne {
	return u.Update(func(s *StrategyUpsert) {
		s.SetQuantityMode(v)
	})
}

// UpdateQuantityMode sets the "quantityMode" field to the value that was provided on create.
func (u *StrategyUpsertOne) UpdateQuantityMode() *StrategyUpsertOne {
	return u.Update(func(s *StrategyUpsert) {
		s.UpdateQuantityMode()
	})
}

// SetPriceUpper sets the "priceUpper" field.
func (u *StrategyUpsertOne) SetPriceUpper(v decimal.Decimal) *StrategyUpsertOne {
	return u.Update(func(s *StrategyUpsert) {
		s.SetPriceUpper(v)
	})
}

// UpdatePriceUpper sets the "priceUpper" field to the value that was provided on create.
func (u *StrategyUpsertOne) UpdatePriceUpper() *StrategyUpsertOne {
	return u.Update(func(s *StrategyUpsert) {
		s.UpdatePriceUpper()
	})
}

// SetPriceLower sets the "priceLower" field.
func (u *StrategyUpsertOne) SetPriceLower(v decimal.Decimal) *StrategyUpsertOne {
	return u.Update(func(s *StrategyUpsert) {
		s.SetPriceLower(v)
	})
}

// UpdatePriceLower sets the "priceLower" field to the value that was provided on create.
func (u *StrategyUpsertOne) UpdatePriceLower() *StrategyUpsertOne {
	return u.Update(func(s *StrategyUpsert) {
		s.UpdatePriceLower()
	})
}

// SetGridNum sets the "gridNum" field.
func (u *StrategyUpsertOne) SetGridNum(v int) *StrategyUpsertOne {
	return u.Update(func(s *StrategyUpsert) {
		s.SetGridNum(v)
	})
}

// AddGridNum adds v to the "gridNum" field.
func (u *StrategyUpsertOne) AddGridNum(v int) *StrategyUpsertOne {
	return u.Update(func(s *StrategyUpsert) {
		s.AddGridNum(v)
	})
}

// UpdateGridNum sets the "gridNum" field to the value that was provided on create.
func (u *StrategyUpsertOne) UpdateGridNum() *StrategyUpsertOne {
	return u.Update(func(s *StrategyUpsert) {
		s.UpdateGridNum()
	})
}

// SetLeverage sets the "leverage" field.
func (u *StrategyUpsertOne) SetLeverage(v int) *StrategyUpsertOne {
	return u.Update(func(s *StrategyUpsert) {
		s.SetLeverage(v)
	})
}

// AddLeverage adds v to the "leverage" field.
func (u *StrategyUpsertOne) AddLeverage(v int) *StrategyUpsertOne {
	return u.Update(func(s *StrategyUpsert) {
		s.AddLeverage(v)
	})
}

// UpdateLeverage sets the "leverage" field to the value that was provided on create.
func (u *StrategyUpsertOne) UpdateLeverage() *StrategyUpsertOne {
	return u.Update(func(s *StrategyUpsert) {
		s.UpdateLeverage()
	})
}

// SetInitialOrderSize sets the "initialOrderSize" field.
func (u *StrategyUpsertOne) SetInitialOrderSize(v decimal.Decimal) *StrategyUpsertOne {
	return u.Update(func(s *StrategyUpsert) {
		s.SetInitialOrderSize(v)
	})
}

// UpdateInitialOrderSize sets the "initialOrderSize" field to the value that was provided on create.
func (u *StrategyUpsertOne) UpdateInitialOrderSize() *StrategyUpsertOne {
	return u.Update(func(s *StrategyUpsert) {
		s.UpdateInitialOrderSize()
	})
}

// SetStopLossRatio sets the "stopLossRatio" field.
func (u *StrategyUpsertOne) SetStopLossRatio(v decimal.Decimal) *StrategyUpsertOne {
	return u.Update(func(s *StrategyUpsert) {
		s.SetStopLossRatio(v)
	})
}

// UpdateStopLossRatio sets the "stopLossRatio" field to the value that was provided on create.
func (u *StrategyUpsertOne) UpdateStopLossRatio() *StrategyUpsertOne {
	return u.Update(func(s *StrategyUpsert) {
		s.UpdateStopLossRatio()
	})
}

// SetTakeProfitRatio sets the "takeProfitRatio" field.
func (u *StrategyUpsertOne) SetTakeProfitRatio(v decimal.Decimal) *StrategyUpsertOne {
	return u.Update(func(s *StrategyUpsert) {
		s.SetTakeProfitRatio(v)
	})
}

// UpdateTakeProfitRatio sets the "takeProfitRatio" field to the value that was provided on create.
func (u *StrategyUpsertOne) UpdateTakeProfitRatio() *StrategyUpsertOne {
	return u.Update(func(s *StrategyUpsert) {
		s.UpdateTakeProfitRatio()
	})
}

// SetEnableAutoExit sets the "enableAutoExit" field.
func (u *StrategyUpsertOne) SetEnableAutoExit(v bool) *StrategyUpsertOne {
	return u.Update(func(s *StrategyUpsert) {
		s.SetEnableAutoExit(v)
	})
}

// UpdateEnableAutoExit sets the "enableAutoExit" field to the value that was provided on create.
func (u *StrategyUpsertOne) UpdateEnableAutoExit() *StrategyUpsertOne {
	return u.Update(func(s *StrategyUpsert) {
		s.UpdateEnableAutoExit()
	})
}

// SetEnablePushNotification sets the "enablePushNotification" field.
func (u *StrategyUpsertOne) SetEnablePushNotification(v bool) *StrategyUpsertOne {
	return u.Update(func(s *StrategyUpsert) {
		s.SetEnablePushNotification(v)
	})
}

// UpdateEnablePushNotification sets the "enablePushNotification" field to the value that was provided on create.
func (u *StrategyUpsertOne) UpdateEnablePushNotification() *StrategyUpsertOne {
	return u.Update(func(s *StrategyUpsert) {
		s.UpdateEnablePushNotification()
	})
}

// SetLastLowerThresholdAlertTime sets the "lastLowerThresholdAlertTime" field.
func (u *StrategyUpsertOne) SetLastLowerThresholdAlertTime(v time.Time) *StrategyUpsertOne {
	return u.Update(func(s *StrategyUpsert) {
		s.SetLastLowerThresholdAlertTime(v)
	})
}

// UpdateLastLowerThresholdAlertTime sets the "lastLowerThresholdAlertTime" field to the value that was provided on create.
func (u *StrategyUpsertOne) UpdateLastLowerThresholdAlertTime() *StrategyUpsertOne {
	return u.Update(func(s *StrategyUpsert) {
		s.UpdateLastLowerThresholdAlertTime()
	})
}

// ClearLastLowerThresholdAlertTime clears the value of the "lastLowerThresholdAlertTime" field.
func (u *StrategyUpsertOne) ClearLastLowerThresholdAlertTime() *StrategyUpsertOne {
	return u.Update(func(s *StrategyUpsert) {
		s.ClearLastLowerThresholdAlertTime()
	})
}

// SetLastUpperThresholdAlertTime sets the "lastUpperThresholdAlertTime" field.
func (u *StrategyUpsertOne) SetLastUpperThresholdAlertTime(v time.Time) *StrategyUpsertOne {
	return u.Update(func(s *StrategyUpsert) {
		s.SetLastUpperThresholdAlertTime(v)
	})
}

// UpdateLastUpperThresholdAlertTime sets the "lastUpperThresholdAlertTime" field to the value that was provided on create.
func (u *StrategyUpsertOne) UpdateLastUpperThresholdAlertTime() *StrategyUpsertOne {
	return u.Update(func(s *StrategyUpsert) {
		s.UpdateLastUpperThresholdAlertTime()
	})
}

// ClearLastUpperThresholdAlertTime clears the value of the "lastUpperThresholdAlertTime" field.
func (u *StrategyUpsertOne) ClearLastUpperThresholdAlertTime() *StrategyUpsertOne {
	return u.Update(func(s *StrategyUpsert) {
		s.ClearLastUpperThresholdAlertTime()
	})
}

// SetStatus sets the "status" field.
func (u *StrategyUpsertOne) SetStatus(v strategy.Status) *StrategyUpsertOne {
	return u.Update(func(s *StrategyUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *StrategyUpsertOne) UpdateStatus() *StrategyUpsertOne {
	return u.Update(func(s *StrategyUpsert) {
		s.UpdateStatus()
	})
}

// SetExchangeApiKey sets the "exchangeApiKey" field.
func (u *StrategyUpsertOne) SetExchangeApiKey(v string) *StrategyUpsertOne {
	return u.Update(func(s *StrategyUpsert) {
		s.SetExchangeApiKey(v)
	})
}

// UpdateExchangeApiKey sets the "exchangeApiKey" field to the value that was provided on create.
func (u *StrategyUpsertOne) UpdateExchangeApiKey() *StrategyUpsertOne {
	return u.Update(func(s *StrategyUpsert) {
		s.UpdateExchangeApiKey()
	})
}

// SetExchangeSecretKey sets the "exchangeSecretKey" field.
func (u *StrategyUpsertOne) SetExchangeSecretKey(v string) *StrategyUpsertOne {
	return u.Update(func(s *StrategyUpsert) {
		s.SetExchangeSecretKey(v)
	})
}

// UpdateExchangeSecretKey sets the "exchangeSecretKey" field to the value that was provided on create.
func (u *StrategyUpsertOne) UpdateExchangeSecretKey() *StrategyUpsertOne {
	return u.Update(func(s *StrategyUpsert) {
		s.UpdateExchangeSecretKey()
	})
}

// SetExchangePassphrase sets the "exchangePassphrase" field.
func (u *StrategyUpsertOne) SetExchangePassphrase(v string) *StrategyUpsertOne {
	return u.Update(func(s *StrategyUpsert) {
		s.SetExchangePassphrase(v)
	})
}

// UpdateExchangePassphrase sets the "exchangePassphrase" field to the value that was provided on create.
func (u *StrategyUpsertOne) UpdateExchangePassphrase() *StrategyUpsertOne {
	return u.Update(func(s *StrategyUpsert) {
		s.UpdateExchangePassphrase()
	})
}

// Exec executes the query.
func (u *StrategyUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for StrategyCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *StrategyUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *StrategyUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *StrategyUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// StrategyCreateBulk is the builder for creating many Strategy entities in bulk.
type StrategyCreateBulk struct {
	config
	err      error
	builders []*StrategyCreate
	conflict []sql.ConflictOption
}

// Save creates the Strategy entities in the database.
func (_c *StrategyCreateBulk) Save(ctx context.Context) ([]*Strategy, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Strategy, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*StrategyMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *StrategyCreateBulk) SaveX(ctx context.Context) []*Strategy {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *StrategyCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *StrategyCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Strategy.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.StrategyUpsert) {
//			SetCreateTime(v+v).
//		}).
//		Exec(ctx)
func (_c *StrategyCreateBulk) OnConflict(opts ...sql.ConflictOption) *StrategyUpsertBulk {
	_c.conflict = opts
	return &StrategyUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Strategy.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *StrategyCreateBulk) OnConflictColumns(columns ...string) *StrategyUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &StrategyUpsertBulk{
		create: _c,
	}
}

// StrategyUpsertBulk is the builder for "upsert"-ing
// a bulk of Strategy nodes.
type StrategyUpsertBulk struct {
	create *StrategyCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Strategy.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *StrategyUpsertBulk) UpdateNewValues() *StrategyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreateTime(); exists {
				s.SetIgnore(strategy.FieldCreateTime)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Strategy.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *StrategyUpsertBulk) Ignore() *StrategyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *StrategyUpsertBulk) DoNothing() *StrategyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the StrategyCreateBulk.OnConflict
// documentation for more info.
func (u *StrategyUpsertBulk) Update(set func(*StrategyUpsert)) *StrategyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&StrategyUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdateTime sets the "update_time" field.
func (u *StrategyUpsertBulk) SetUpdateTime(v time.Time) *StrategyUpsertBulk {
	return u.Update(func(s *StrategyUpsert) {
		s.SetUpdateTime(v)
	})
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *StrategyUpsertBulk) UpdateUpdateTime() *StrategyUpsertBulk {
	return u.Update(func(s *StrategyUpsert) {
		s.UpdateUpdateTime()
	})
}

// SetGUID sets the "guid" field.
func (u *StrategyUpsertBulk) SetGUID(v string) *StrategyUpsertBulk {
	return u.Update(func(s *StrategyUpsert) {
		s.SetGUID(v)
	})
}

// UpdateGUID sets the "guid" field to the value that was provided on create.
func (u *StrategyUpsertBulk) UpdateGUID() *StrategyUpsertBulk {
	return u.Update(func(s *StrategyUpsert) {
		s.UpdateGUID()
	})
}

// SetOwner sets the "owner" field.
func (u *StrategyUpsertBulk) SetOwner(v int64) *StrategyUpsertBulk {
	return u.Update(func(s *StrategyUpsert) {
		s.SetOwner(v)
	})
}

// AddOwner adds v to the "owner" field.
func (u *StrategyUpsertBulk) AddOwner(v int64) *StrategyUpsertBulk {
	return u.Update(func(s *StrategyUpsert) {
		s.AddOwner(v)
	})
}

// UpdateOwner sets the "owner" field to the value that was provided on create.
func (u *StrategyUpsertBulk) UpdateOwner() *StrategyUpsertBulk {
	return u.Update(func(s *StrategyUpsert) {
		s.UpdateOwner()
	})
}

// SetExchange sets the "exchange" field.
func (u *StrategyUpsertBulk) SetExchange(v string) *StrategyUpsertBulk {
	return u.Update(func(s *StrategyUpsert) {
		s.SetExchange(v)
	})
}

// UpdateExchange sets the "exchange" field to the value that was provided on create.
func (u *StrategyUpsertBulk) UpdateExchange() *StrategyUpsertBulk {
	return u.Update(func(s *StrategyUpsert) {
		s.UpdateExchange()
	})
}

// SetSymbol sets the "symbol" field.
func (u *StrategyUpsertBulk) SetSymbol(v string) *StrategyUpsertBulk {
	return u.Update(func(s *StrategyUpsert) {
		s.SetSymbol(v)
	})
}

// UpdateSymbol sets the "symbol" field to the value that was provided on create.
func (u *StrategyUpsertBulk) UpdateSymbol() *StrategyUpsertBulk {
	return u.Update(func(s *StrategyUpsert) {
		s.UpdateSymbol()
	})
}

// SetAccount sets the "account" field.
func (u *StrategyUpsertBulk) SetAccount(v string) *StrategyUpsertBulk {
	return u.Update(func(s *StrategyUpsert) {
		s.SetAccount(v)
	})
}

// UpdateAccount sets the "account" field to the value that was provided on create.
func (u *StrategyUpsertBulk) UpdateAccount() *StrategyUpsertBulk {
	return u.Update(func(s *StrategyUpsert) {
		s.UpdateAccount()
	})
}

// SetMode sets the "mode" field.
func (u *StrategyUpsertBulk) SetMode(v strategy.Mode) *StrategyUpsertBulk {
	return u.Update(func(s *StrategyUpsert) {
		s.SetMode(v)
	})
}

// UpdateMode sets the "mode" field to the value that was provided on create.
func (u *StrategyUpsertBulk) UpdateMode() *StrategyUpsertBulk {
	return u.Update(func(s *StrategyUpsert) {
		s.UpdateMode()
	})
}

// SetMarginMode sets the "marginMode" field.
func (u *StrategyUpsertBulk) SetMarginMode(v strategy.MarginMode) *StrategyUpsertBulk {
	return u.Update(func(s *StrategyUpsert) {
		s.SetMarginMode(v)
	})
}

// UpdateMarginMode sets the "marginMode" field to the value that was provided on create.
func (u *StrategyUpsertBulk) UpdateMarginMode() *StrategyUpsertBulk {
	return u.Update(func(s *StrategyUpsert) {
		s.UpdateMarginMode()
	})
}

// SetQuantityMode sets the "quantityMode" field.
func (u *StrategyUpsertBulk) SetQuantityMode(v strategy.QuantityMode) *StrategyUpsertBulk {
	return u.Update(func(s *StrategyUpsert) {
		s.SetQuantityMode(v)
	})
}

// UpdateQuantityMode sets the "quantityMode" field to the value that was provided on create.
func (u *StrategyUpsertBulk) UpdateQuantityMode() *StrategyUpsertBulk {
	return u.Update(func(s *StrategyUpsert) {
		s.UpdateQuantityMode()
	})
}

// SetPriceUpper sets the "priceUpper" field.
func (u *StrategyUpsertBulk) SetPriceUpper(v decimal.Decimal) *StrategyUpsertBulk {
	return u.Update(func(s *StrategyUpsert) {
		s.SetPriceUpper(v)
	})
}

// UpdatePriceUpper sets the "priceUpper" field to the value that was provided on create.
func (u *StrategyUpsertBulk) UpdatePriceUpper() *StrategyUpsertBulk {
	return u.Update(func(s *StrategyUpsert) {
		s.UpdatePriceUpper()
	})
}

// SetPriceLower sets the "priceLower" field.
func (u *StrategyUpsertBulk) SetPriceLower(v decimal.Decimal) *StrategyUpsertBulk {
	return u.Update(func(s *StrategyUpsert) {
		s.SetPriceLower(v)
	})
}

// UpdatePriceLower sets the "priceLower" field to the value that was provided on create.
func (u *StrategyUpsertBulk) UpdatePriceLower() *StrategyUpsertBulk {
	return u.Update(func(s *StrategyUpsert) {
		s.UpdatePriceLower()
	})
}

// SetGridNum sets the "gridNum" field.
func (u *StrategyUpsertBulk) SetGridNum(v int) *StrategyUpsertBulk {
	return u.Update(func(s *StrategyUpsert) {
		s.SetGridNum(v)
	})
}

// AddGridNum adds v to the "gridNum" field.
func (u *StrategyUpsertBulk) AddGridNum(v int) *StrategyUpsertBulk {
	return u.Update(func(s *StrategyUpsert) {
		s.AddGridNum(v)
	})
}

// UpdateGridNum sets the "gridNum" field to the value that was provided on create.
func (u *StrategyUpsertBulk) UpdateGridNum() *StrategyUpsertBulk {
	return u.Update(func(s *StrategyUpsert) {
		s.UpdateGridNum()
	})
}

// SetLeverage sets the "leverage" field.
func (u *StrategyUpsertBulk) SetLeverage(v int) *StrategyUpsertBulk {
	return u.Update(func(s *StrategyUpsert) {
		s.SetLeverage(v)
	})
}

// AddLeverage adds v to the "leverage" field.
func (u *StrategyUpsertBulk) AddLeverage(v int) *StrategyUpsertBulk {
	return u.Update(func(s *StrategyUpsert) {
		s.AddLeverage(v)
	})
}

// UpdateLeverage sets the "leverage" field to the value that was provided on create.
func (u *StrategyUpsertBulk) UpdateLeverage() *StrategyUpsertBulk {
	return u.Update(func(s *StrategyUpsert) {
		s.UpdateLeverage()
	})
}

// SetInitialOrderSize sets the "initialOrderSize" field.
func (u *StrategyUpsertBulk) SetInitialOrderSize(v decimal.Decimal) *StrategyUpsertBulk {
	return u.Update(func(s *StrategyUpsert) {
		s.SetInitialOrderSize(v)
	})
}

// UpdateInitialOrderSize sets the "initialOrderSize" field to the value that was provided on create.
func (u *StrategyUpsertBulk) UpdateInitialOrderSize() *StrategyUpsertBulk {
	return u.Update(func(s *StrategyUpsert) {
		s.UpdateInitialOrderSize()
	})
}

// SetStopLossRatio sets the "stopLossRatio" field.
func (u *StrategyUpsertBulk) SetStopLossRatio(v decimal.Decimal) *StrategyUpsertBulk {
	return u.Update(func(s *StrategyUpsert) {
		s.SetStopLossRatio(v)
	})
}

// UpdateStopLossRatio sets the "stopLossRatio" field to the value that was provided on create.
func (u *StrategyUpsertBulk) UpdateStopLossRatio() *StrategyUpsertBulk {
	return u.Update(func(s *StrategyUpsert) {
		s.UpdateStopLossRatio()
	})
}

// SetTakeProfitRatio sets the "takeProfitRatio" field.
func (u *StrategyUpsertBulk) SetTakeProfitRatio(v decimal.Decimal) *StrategyUpsertBulk {
	return u.Update(func(s *StrategyUpsert) {
		s.SetTakeProfitRatio(v)
	})
}

// UpdateTakeProfitRatio sets the "takeProfitRatio" field to the value that was provided on create.
func (u *StrategyUpsertBulk) UpdateTakeProfitRatio() *StrategyUpsertBulk {
	return u.Update(func(s *StrategyUpsert) {
		s.UpdateTakeProfitRatio()
	})
}

// SetEnableAutoExit sets the "enableAutoExit" field.
func (u *StrategyUpsertBulk) SetEnableAutoExit(v bool) *StrategyUpsertBulk {
	return u.Update(func(s *StrategyUpsert) {
		s.SetEnableAutoExit(v)
	})
}

// UpdateEnableAutoExit sets the "enableAutoExit" field to the value that was provided on create.
func (u *StrategyUpsertBulk) UpdateEnableAutoExit() *StrategyUpsertBulk {
	return u.Update(func(s *StrategyUpsert) {
		s.UpdateEnableAutoExit()
	})
}

// SetEnablePushNotification sets the "enablePushNotification" field.
func (u *StrategyUpsertBulk) SetEnablePushNotification(v bool) *StrategyUpsertBulk {
	return u.Update(func(s *StrategyUpsert) {
		s.SetEnablePushNotification(v)
	})
}

// UpdateEnablePushNotification sets the "enablePushNotification" field to the value that was provided on create.
func (u *StrategyUpsertBulk) UpdateEnablePushNotification() *StrategyUpsertBulk {
	return u.Update(func(s *StrategyUpsert) {
		s.UpdateEnablePushNotification()
	})
}

// SetLastLowerThresholdAlertTime sets the "lastLowerThresholdAlertTime" field.
func (u *StrategyUpsertBulk) SetLastLowerThresholdAlertTime(v time.Time) *StrategyUpsertBulk {
	return u.Update(func(s *StrategyUpsert) {
		s.SetLastLowerThresholdAlertTime(v)
	})
}

// UpdateLastLowerThresholdAlertTime sets the "lastLowerThresholdAlertTime" field to the value that was provided on create.
func (u *StrategyUpsertBulk) UpdateLastLowerThresholdAlertTime() *StrategyUpsertBulk {
	return u.Update(func(s *StrategyUpsert) {
		s.UpdateLastLowerThresholdAlertTime()
	})
}

// ClearLastLowerThresholdAlertTime clears the value of the "lastLowerThresholdAlertTime" field.
func (u *StrategyUpsertBulk) ClearLastLowerThresholdAlertTime() *StrategyUpsertBulk {
	return u.Update(func(s *StrategyUpsert) {
		s.ClearLastLowerThresholdAlertTime()
	})
}

// SetLastUpperThresholdAlertTime sets the "lastUpperThresholdAlertTime" field.
func (u *StrategyUpsertBulk) SetLastUpperThresholdAlertTime(v time.Time) *StrategyUpsertBulk {
	return u.Update(func(s *StrategyUpsert) {
		s.SetLastUpperThresholdAlertTime(v)
	})
}

// UpdateLastUpperThresholdAlertTime sets the "lastUpperThresholdAlertTime" field to the value that was provided on create.
func (u *StrategyUpsertBulk) UpdateLastUpperThresholdAlertTime() *StrategyUpsertBulk {
	return u.Update(func(s *StrategyUpsert) {
		s.UpdateLastUpperThresholdAlertTime()
	})
}

// ClearLastUpperThresholdAlertTime clears the value of the "lastUpperThresholdAlertTime" field.
func (u *StrategyUpsertBulk) ClearLastUpperThresholdAlertTime() *StrategyUpsertBulk {
	return u.Update(func(s *StrategyUpsert) {
		s.ClearLastUpperThresholdAlertTime()
	})
}

// SetStatus sets the "status" field.
func (u *StrategyUpsertBulk) SetStatus(v strategy.Status) *StrategyUpsertBulk {
	return u.Update(func(s *StrategyUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *StrategyUpsertBulk) UpdateStatus() *StrategyUpsertBulk {
	return u.Update(func(s *StrategyUpsert) {
		s.UpdateStatus()
	})
}

// SetExchangeApiKey sets the "exchangeApiKey" field.
func (u *StrategyUpsertBulk) SetExchangeApiKey(v string) *StrategyUpsertBulk {
	return u.Update(func(s *StrategyUpsert) {
		s.SetExchangeApiKey(v)
	})
}

// UpdateExchangeApiKey sets the "exchangeApiKey" field to the value that was provided on create.
func (u *StrategyUpsertBulk) UpdateExchangeApiKey() *StrategyUpsertBulk {
	return u.Update(func(s *StrategyUpsert) {
		s.UpdateExchangeApiKey()
	})
}

// SetExchangeSecretKey sets the "exchangeSecretKey" field.
func (u *StrategyUpsertBulk) SetExchangeSecretKey(v string) *StrategyUpsertBulk {
	return u.Update(func(s *StrategyUpsert) {
		s.SetExchangeSecretKey(v)
	})
}

// UpdateExchangeSecretKey sets the "exchangeSecretKey" field to the value that was provided on create.
func (u *StrategyUpsertBulk) UpdateExchangeSecretKey() *StrategyUpsertBulk {
	return u.Update(func(s *StrategyUpsert) {
		s.UpdateExchangeSecretKey()
	})
}

// SetExchangePassphrase sets the "exchangePassphrase" field.
func (u *StrategyUpsertBulk) SetExchangePassphrase(v string) *StrategyUpsertBulk {
	return u.Update(func(s *StrategyUpsert) {
		s.SetExchangePassphrase(v)
	})
}

// UpdateExchangePassphrase sets the "exchangePassphrase" field to the value that was provided on create.
func (u *StrategyUpsertBulk) UpdateExchangePassphrase() *StrategyUpsertBulk {
	return u.Update(func(s *StrategyUpsert) {
		s.UpdateExchangePassphrase()
	})
}

// Exec executes the query.
func (u *StrategyUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the StrategyCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for StrategyCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *StrategyUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
