// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/fachebot/omni-grid-bot/internal/ent/predicate"
	"github.com/fachebot/omni-grid-bot/internal/ent/syncprogress"
)

// SyncProgressDelete is the builder for deleting a SyncProgress entity.
type SyncProgressDelete struct {
	config
	hooks    []Hook
	mutation *SyncProgressMutation
}

// Where appends a list predicates to the SyncProgressDelete builder.
func (_d *SyncProgressDelete) Where(ps ...predicate.SyncProgress) *SyncProgressDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *SyncProgressDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *SyncProgressDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *SyncProgressDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(syncprogress.Table, sqlgraph.NewFieldSpec(syncprogress.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// SyncProgressDeleteOne is the builder for deleting a single SyncProgress entity.
type SyncProgressDeleteOne struct {
	_d *SyncProgressDelete
}

// Where appends a list predicates to the SyncProgressDelete builder.
func (_d *SyncProgressDeleteOne) Where(ps ...predicate.SyncProgress) *SyncProgressDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *SyncProgressDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{syncprogress.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *SyncProgressDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
