// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/fachebot/perp-dex-grid-bot/internal/ent/predicate"
	"github.com/fachebot/perp-dex-grid-bot/internal/ent/syncprogress"
)

// SyncProgressUpdate is the builder for updating SyncProgress entities.
type SyncProgressUpdate struct {
	config
	hooks    []Hook
	mutation *SyncProgressMutation
}

// Where appends a list predicates to the SyncProgressUpdate builder.
func (_u *SyncProgressUpdate) Where(ps ...predicate.SyncProgress) *SyncProgressUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdateTime sets the "update_time" field.
func (_u *SyncProgressUpdate) SetUpdateTime(v time.Time) *SyncProgressUpdate {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetExchange sets the "exchange" field.
func (_u *SyncProgressUpdate) SetExchange(v string) *SyncProgressUpdate {
	_u.mutation.SetExchange(v)
	return _u
}

// SetNillableExchange sets the "exchange" field if the given value is not nil.
func (_u *SyncProgressUpdate) SetNillableExchange(v *string) *SyncProgressUpdate {
	if v != nil {
		_u.SetExchange(*v)
	}
	return _u
}

// SetAccount sets the "account" field.
func (_u *SyncProgressUpdate) SetAccount(v string) *SyncProgressUpdate {
	_u.mutation.SetAccount(v)
	return _u
}

// SetNillableAccount sets the "account" field if the given value is not nil.
func (_u *SyncProgressUpdate) SetNillableAccount(v *string) *SyncProgressUpdate {
	if v != nil {
		_u.SetAccount(*v)
	}
	return _u
}

// SetTimestamp sets the "timestamp" field.
func (_u *SyncProgressUpdate) SetTimestamp(v int64) *SyncProgressUpdate {
	_u.mutation.ResetTimestamp()
	_u.mutation.SetTimestamp(v)
	return _u
}

// SetNillableTimestamp sets the "timestamp" field if the given value is not nil.
func (_u *SyncProgressUpdate) SetNillableTimestamp(v *int64) *SyncProgressUpdate {
	if v != nil {
		_u.SetTimestamp(*v)
	}
	return _u
}

// AddTimestamp adds value to the "timestamp" field.
func (_u *SyncProgressUpdate) AddTimestamp(v int64) *SyncProgressUpdate {
	_u.mutation.AddTimestamp(v)
	return _u
}

// Mutation returns the SyncProgressMutation object of the builder.
func (_u *SyncProgressUpdate) Mutation() *SyncProgressMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SyncProgressUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SyncProgressUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SyncProgressUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SyncProgressUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SyncProgressUpdate) defaults() {
	if _, ok := _u.mutation.UpdateTime(); !ok {
		v := syncprogress.UpdateDefaultUpdateTime()
		_u.mutation.SetUpdateTime(v)
	}
}

func (_u *SyncProgressUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(syncprogress.Table, syncprogress.Columns, sqlgraph.NewFieldSpec(syncprogress.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(syncprogress.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Exchange(); ok {
		_spec.SetField(syncprogress.FieldExchange, field.TypeString, value)
	}
	if value, ok := _u.mutation.Account(); ok {
		_spec.SetField(syncprogress.FieldAccount, field.TypeString, value)
	}
	if value, ok := _u.mutation.Timestamp(); ok {
		_spec.SetField(syncprogress.FieldTimestamp, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTimestamp(); ok {
		_spec.AddField(syncprogress.FieldTimestamp, field.TypeInt64, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{syncprogress.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SyncProgressUpdateOne is the builder for updating a single SyncProgress entity.
type SyncProgressUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SyncProgressMutation
}

// SetUpdateTime sets the "update_time" field.
func (_u *SyncProgressUpdateOne) SetUpdateTime(v time.Time) *SyncProgressUpdateOne {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetExchange sets the "exchange" field.
func (_u *SyncProgressUpdateOne) SetExchange(v string) *SyncProgressUpdateOne {
	_u.mutation.SetExchange(v)
	return _u
}

// SetNillableExchange sets the "exchange" field if the given value is not nil.
func (_u *SyncProgressUpdateOne) SetNillableExchange(v *string) *SyncProgressUpdateOne {
	if v != nil {
		_u.SetExchange(*v)
	}
	return _u
}

// SetAccount sets the "account" field.
func (_u *SyncProgressUpdateOne) SetAccount(v string) *SyncProgressUpdateOne {
	_u.mutation.SetAccount(v)
	return _u
}

// SetNillableAccount sets the "account" field if the given value is not nil.
func (_u *SyncProgressUpdateOne) SetNillableAccount(v *string) *SyncProgressUpdateOne {
	if v != nil {
		_u.SetAccount(*v)
	}
	return _u
}

// SetTimestamp sets the "timestamp" field.
func (_u *SyncProgressUpdateOne) SetTimestamp(v int64) *SyncProgressUpdateOne {
	_u.mutation.ResetTimestamp()
	_u.mutation.SetTimestamp(v)
	return _u
}

// SetNillableTimestamp sets the "timestamp" field if the given value is not nil.
func (_u *SyncProgressUpdateOne) SetNillableTimestamp(v *int64) *SyncProgressUpdateOne {
	if v != nil {
		_u.SetTimestamp(*v)
	}
	return _u
}

// AddTimestamp adds value to the "timestamp" field.
func (_u *SyncProgressUpdateOne) AddTimestamp(v int64) *SyncProgressUpdateOne {
	_u.mutation.AddTimestamp(v)
	return _u
}

// Mutation returns the SyncProgressMutation object of the builder.
func (_u *SyncProgressUpdateOne) Mutation() *SyncProgressMutation {
	return _u.mutation
}

// Where appends a list predicates to the SyncProgressUpdate builder.
func (_u *SyncProgressUpdateOne) Where(ps ...predicate.SyncProgress) *SyncProgressUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SyncProgressUpdateOne) Select(field string, fields ...string) *SyncProgressUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SyncProgress entity.
func (_u *SyncProgressUpdateOne) Save(ctx context.Context) (*SyncProgress, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SyncProgressUpdateOne) SaveX(ctx context.Context) *SyncProgress {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SyncProgressUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SyncProgressUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SyncProgressUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdateTime(); !ok {
		v := syncprogress.UpdateDefaultUpdateTime()
		_u.mutation.SetUpdateTime(v)
	}
}

func (_u *SyncProgressUpdateOne) sqlSave(ctx context.Context) (_node *SyncProgress, err error) {
	_spec := sqlgraph.NewUpdateSpec(syncprogress.Table, syncprogress.Columns, sqlgraph.NewFieldSpec(syncprogress.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SyncProgress.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, syncprogress.FieldID)
		for _, f := range fields {
			if !syncprogress.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != syncprogress.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(syncprogress.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Exchange(); ok {
		_spec.SetField(syncprogress.FieldExchange, field.TypeString, value)
	}
	if value, ok := _u.mutation.Account(); ok {
		_spec.SetField(syncprogress.FieldAccount, field.TypeString, value)
	}
	if value, ok := _u.mutation.Timestamp(); ok {
		_spec.SetField(syncprogress.FieldTimestamp, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTimestamp(); ok {
		_spec.AddField(syncprogress.FieldTimestamp, field.TypeInt64, value)
	}
	_node = &SyncProgress{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{syncprogress.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
