// Code generated by ent, DO NOT EDIT.

package matchedtrades

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the matchedtrades type in the database.
	Label = "matched_trades"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldStrategyId holds the string denoting the strategyid field in the database.
	FieldStrategyId = "strategy_id"
	// FieldPrice holds the string denoting the price field in the database.
	FieldPrice = "price"
	// FieldBuyClientOrderId holds the string denoting the buyclientorderid field in the database.
	FieldBuyClientOrderId = "buy_client_order_id"
	// FieldBuyBaseAmount holds the string denoting the buybaseamount field in the database.
	FieldBuyBaseAmount = "buy_base_amount"
	// FieldBuyQuoteAmount holds the string denoting the buyquoteamount field in the database.
	FieldBuyQuoteAmount = "buy_quote_amount"
	// FieldBuyOrderTimestamp holds the string denoting the buyordertimestamp field in the database.
	FieldBuyOrderTimestamp = "buy_order_timestamp"
	// FieldSellClientOrderId holds the string denoting the sellclientorderid field in the database.
	FieldSellClientOrderId = "sell_client_order_id"
	// FieldSellBaseAmount holds the string denoting the sellbaseamount field in the database.
	FieldSellBaseAmount = "sell_base_amount"
	// FieldSellQuoteAmount holds the string denoting the sellquoteamount field in the database.
	FieldSellQuoteAmount = "sell_quote_amount"
	// FieldSellOrderTimestamp holds the string denoting the sellordertimestamp field in the database.
	FieldSellOrderTimestamp = "sell_order_timestamp"
	// Table holds the table name of the matchedtrades in the database.
	Table = "matched_trades"
)

// Columns holds all SQL columns for matchedtrades fields.
var Columns = []string{
	FieldID,
	FieldStrategyId,
	FieldPrice,
	FieldBuyClientOrderId,
	FieldBuyBaseAmount,
	FieldBuyQuoteAmount,
	FieldBuyOrderTimestamp,
	FieldSellClientOrderId,
	FieldSellBaseAmount,
	FieldSellQuoteAmount,
	FieldSellOrderTimestamp,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// StrategyIdValidator is a validator for the "strategyId" field. It is called by the builders before save.
	StrategyIdValidator func(string) error
)

// OrderOption defines the ordering options for the MatchedTrades queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByStrategyId orders the results by the strategyId field.
func ByStrategyId(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStrategyId, opts...).ToFunc()
}

// ByPrice orders the results by the price field.
func ByPrice(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPrice, opts...).ToFunc()
}

// ByBuyClientOrderId orders the results by the buyClientOrderId field.
func ByBuyClientOrderId(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBuyClientOrderId, opts...).ToFunc()
}

// ByBuyBaseAmount orders the results by the buyBaseAmount field.
func ByBuyBaseAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBuyBaseAmount, opts...).ToFunc()
}

// ByBuyQuoteAmount orders the results by the buyQuoteAmount field.
func ByBuyQuoteAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBuyQuoteAmount, opts...).ToFunc()
}

// ByBuyOrderTimestamp orders the results by the buyOrderTimestamp field.
func ByBuyOrderTimestamp(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBuyOrderTimestamp, opts...).ToFunc()
}

// BySellClientOrderId orders the results by the sellClientOrderId field.
func BySellClientOrderId(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSellClientOrderId, opts...).ToFunc()
}

// BySellBaseAmount orders the results by the sellBaseAmount field.
func BySellBaseAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSellBaseAmount, opts...).ToFunc()
}

// BySellQuoteAmount orders the results by the sellQuoteAmount field.
func BySellQuoteAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSellQuoteAmount, opts...).ToFunc()
}

// BySellOrderTimestamp orders the results by the sellOrderTimestamp field.
func BySellOrderTimestamp(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSellOrderTimestamp, opts...).ToFunc()
}
