// Code generated by ent, DO NOT EDIT.

package strategy

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the strategy type in the database.
	Label = "strategy"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreateTime holds the string denoting the create_time field in the database.
	FieldCreateTime = "create_time"
	// FieldUpdateTime holds the string denoting the update_time field in the database.
	FieldUpdateTime = "update_time"
	// FieldGUID holds the string denoting the guid field in the database.
	FieldGUID = "guid"
	// FieldOwner holds the string denoting the owner field in the database.
	FieldOwner = "owner"
	// FieldExchange holds the string denoting the exchange field in the database.
	FieldExchange = "exchange"
	// FieldSymbol holds the string denoting the symbol field in the database.
	FieldSymbol = "symbol"
	// FieldAccount holds the string denoting the account field in the database.
	FieldAccount = "account"
	// FieldMode holds the string denoting the mode field in the database.
	FieldMode = "mode"
	// FieldMarginMode holds the string denoting the marginmode field in the database.
	FieldMarginMode = "margin_mode"
	// FieldQuantityMode holds the string denoting the quantitymode field in the database.
	FieldQuantityMode = "quantity_mode"
	// FieldPriceUpper holds the string denoting the priceupper field in the database.
	FieldPriceUpper = "price_upper"
	// FieldPriceLower holds the string denoting the pricelower field in the database.
	FieldPriceLower = "price_lower"
	// FieldGridNum holds the string denoting the gridnum field in the database.
	FieldGridNum = "grid_num"
	// FieldLeverage holds the string denoting the leverage field in the database.
	FieldLeverage = "leverage"
	// FieldInitialOrderSize holds the string denoting the initialordersize field in the database.
	FieldInitialOrderSize = "initial_order_size"
	// FieldSlippageBps holds the string denoting the slippagebps field in the database.
	FieldSlippageBps = "slippage_bps"
	// FieldEntryPrice holds the string denoting the entryprice field in the database.
	FieldEntryPrice = "entry_price"
	// FieldTriggerStopLossPrice holds the string denoting the triggerstoplossprice field in the database.
	FieldTriggerStopLossPrice = "trigger_stop_loss_price"
	// FieldTriggerTakeProfitPrice holds the string denoting the triggertakeprofitprice field in the database.
	FieldTriggerTakeProfitPrice = "trigger_take_profit_price"
	// FieldEnablePushNotification holds the string denoting the enablepushnotification field in the database.
	FieldEnablePushNotification = "enable_push_notification"
	// FieldEnablePushMatchedNotification holds the string denoting the enablepushmatchednotification field in the database.
	FieldEnablePushMatchedNotification = "enable_push_matched_notification"
	// FieldLastLowerThresholdAlertTime holds the string denoting the lastlowerthresholdalerttime field in the database.
	FieldLastLowerThresholdAlertTime = "last_lower_threshold_alert_time"
	// FieldLastUpperThresholdAlertTime holds the string denoting the lastupperthresholdalerttime field in the database.
	FieldLastUpperThresholdAlertTime = "last_upper_threshold_alert_time"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldExchangeApiKey holds the string denoting the exchangeapikey field in the database.
	FieldExchangeApiKey = "exchange_api_key"
	// FieldExchangeSecretKey holds the string denoting the exchangesecretkey field in the database.
	FieldExchangeSecretKey = "exchange_secret_key"
	// FieldExchangePassphrase holds the string denoting the exchangepassphrase field in the database.
	FieldExchangePassphrase = "exchange_passphrase"
	// FieldStartTime holds the string denoting the starttime field in the database.
	FieldStartTime = "start_time"
	// Table holds the table name of the strategy in the database.
	Table = "strategies"
)

// Columns holds all SQL columns for strategy fields.
var Columns = []string{
	FieldID,
	FieldCreateTime,
	FieldUpdateTime,
	FieldGUID,
	FieldOwner,
	FieldExchange,
	FieldSymbol,
	FieldAccount,
	FieldMode,
	FieldMarginMode,
	FieldQuantityMode,
	FieldPriceUpper,
	FieldPriceLower,
	FieldGridNum,
	FieldLeverage,
	FieldInitialOrderSize,
	FieldSlippageBps,
	FieldEntryPrice,
	FieldTriggerStopLossPrice,
	FieldTriggerTakeProfitPrice,
	FieldEnablePushNotification,
	FieldEnablePushMatchedNotification,
	FieldLastLowerThresholdAlertTime,
	FieldLastUpperThresholdAlertTime,
	FieldStatus,
	FieldExchangeApiKey,
	FieldExchangeSecretKey,
	FieldExchangePassphrase,
	FieldStartTime,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreateTime holds the default value on creation for the "create_time" field.
	DefaultCreateTime func() time.Time
	// DefaultUpdateTime holds the default value on creation for the "update_time" field.
	DefaultUpdateTime func() time.Time
	// UpdateDefaultUpdateTime holds the default value on update for the "update_time" field.
	UpdateDefaultUpdateTime func() time.Time
	// GUIDValidator is a validator for the "guid" field. It is called by the builders before save.
	GUIDValidator func(string) error
	// ExchangeValidator is a validator for the "exchange" field. It is called by the builders before save.
	ExchangeValidator func(string) error
	// SymbolValidator is a validator for the "symbol" field. It is called by the builders before save.
	SymbolValidator func(string) error
	// DefaultGridNum holds the default value on creation for the "gridNum" field.
	DefaultGridNum int
	// GridNumValidator is a validator for the "gridNum" field. It is called by the builders before save.
	GridNumValidator func(int) error
	// DefaultLeverage holds the default value on creation for the "leverage" field.
	DefaultLeverage int
	// LeverageValidator is a validator for the "leverage" field. It is called by the builders before save.
	LeverageValidator func(int) error
	// SlippageBpsValidator is a validator for the "slippageBps" field. It is called by the builders before save.
	SlippageBpsValidator func(int) error
)

// Mode defines the type for the "mode" enum field.
type Mode string

// Mode values.
const (
	ModeLong  Mode = "long"
	ModeShort Mode = "short"
)

func (m Mode) String() string {
	return string(m)
}

// ModeValidator is a validator for the "mode" field enum values. It is called by the builders before save.
func ModeValidator(m Mode) error {
	switch m {
	case ModeLong, ModeShort:
		return nil
	default:
		return fmt.Errorf("strategy: invalid enum value for mode field: %q", m)
	}
}

// MarginMode defines the type for the "marginMode" enum field.
type MarginMode string

// MarginMode values.
const (
	MarginModeCross    MarginMode = "cross"
	MarginModeIsolated MarginMode = "isolated"
)

func (mm MarginMode) String() string {
	return string(mm)
}

// MarginModeValidator is a validator for the "marginMode" field enum values. It is called by the builders before save.
func MarginModeValidator(mm MarginMode) error {
	switch mm {
	case MarginModeCross, MarginModeIsolated:
		return nil
	default:
		return fmt.Errorf("strategy: invalid enum value for marginMode field: %q", mm)
	}
}

// QuantityMode defines the type for the "quantityMode" enum field.
type QuantityMode string

// QuantityMode values.
const (
	QuantityModeArithmetic QuantityMode = "arithmetic"
	QuantityModeGeometric  QuantityMode = "geometric"
)

func (qm QuantityMode) String() string {
	return string(qm)
}

// QuantityModeValidator is a validator for the "quantityMode" field enum values. It is called by the builders before save.
func QuantityModeValidator(qm QuantityMode) error {
	switch qm {
	case QuantityModeArithmetic, QuantityModeGeometric:
		return nil
	default:
		return fmt.Errorf("strategy: invalid enum value for quantityMode field: %q", qm)
	}
}

// Status defines the type for the "status" enum field.
type Status string

// Status values.
const (
	StatusActive   Status = "active"
	StatusInactive Status = "inactive"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusActive, StatusInactive:
		return nil
	default:
		return fmt.Errorf("strategy: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the Strategy queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreateTime orders the results by the create_time field.
func ByCreateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreateTime, opts...).ToFunc()
}

// ByUpdateTime orders the results by the update_time field.
func ByUpdateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdateTime, opts...).ToFunc()
}

// ByGUID orders the results by the guid field.
func ByGUID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGUID, opts...).ToFunc()
}

// ByOwner orders the results by the owner field.
func ByOwner(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOwner, opts...).ToFunc()
}

// ByExchange orders the results by the exchange field.
func ByExchange(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExchange, opts...).ToFunc()
}

// BySymbol orders the results by the symbol field.
func BySymbol(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSymbol, opts...).ToFunc()
}

// ByAccount orders the results by the account field.
func ByAccount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccount, opts...).ToFunc()
}

// ByMode orders the results by the mode field.
func ByMode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMode, opts...).ToFunc()
}

// ByMarginMode orders the results by the marginMode field.
func ByMarginMode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMarginMode, opts...).ToFunc()
}

// ByQuantityMode orders the results by the quantityMode field.
func ByQuantityMode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldQuantityMode, opts...).ToFunc()
}

// ByPriceUpper orders the results by the priceUpper field.
func ByPriceUpper(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPriceUpper, opts...).ToFunc()
}

// ByPriceLower orders the results by the priceLower field.
func ByPriceLower(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPriceLower, opts...).ToFunc()
}

// ByGridNum orders the results by the gridNum field.
func ByGridNum(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGridNum, opts...).ToFunc()
}

// ByLeverage orders the results by the leverage field.
func ByLeverage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLeverage, opts...).ToFunc()
}

// ByInitialOrderSize orders the results by the initialOrderSize field.
func ByInitialOrderSize(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInitialOrderSize, opts...).ToFunc()
}

// BySlippageBps orders the results by the slippageBps field.
func BySlippageBps(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSlippageBps, opts...).ToFunc()
}

// ByEntryPrice orders the results by the entryPrice field.
func ByEntryPrice(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEntryPrice, opts...).ToFunc()
}

// ByTriggerStopLossPrice orders the results by the triggerStopLossPrice field.
func ByTriggerStopLossPrice(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTriggerStopLossPrice, opts...).ToFunc()
}

// ByTriggerTakeProfitPrice orders the results by the triggerTakeProfitPrice field.
func ByTriggerTakeProfitPrice(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTriggerTakeProfitPrice, opts...).ToFunc()
}

// ByEnablePushNotification orders the results by the enablePushNotification field.
func ByEnablePushNotification(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEnablePushNotification, opts...).ToFunc()
}

// ByEnablePushMatchedNotification orders the results by the enablePushMatchedNotification field.
func ByEnablePushMatchedNotification(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEnablePushMatchedNotification, opts...).ToFunc()
}

// ByLastLowerThresholdAlertTime orders the results by the lastLowerThresholdAlertTime field.
func ByLastLowerThresholdAlertTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastLowerThresholdAlertTime, opts...).ToFunc()
}

// ByLastUpperThresholdAlertTime orders the results by the lastUpperThresholdAlertTime field.
func ByLastUpperThresholdAlertTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastUpperThresholdAlertTime, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByExchangeApiKey orders the results by the exchangeApiKey field.
func ByExchangeApiKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExchangeApiKey, opts...).ToFunc()
}

// ByExchangeSecretKey orders the results by the exchangeSecretKey field.
func ByExchangeSecretKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExchangeSecretKey, opts...).ToFunc()
}

// ByExchangePassphrase orders the results by the exchangePassphrase field.
func ByExchangePassphrase(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExchangePassphrase, opts...).ToFunc()
}

// ByStartTime orders the results by the startTime field.
func ByStartTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStartTime, opts...).ToFunc()
}
