// Code generated by ent, DO NOT EDIT.

package grid

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the grid type in the database.
	Label = "grid"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreateTime holds the string denoting the create_time field in the database.
	FieldCreateTime = "create_time"
	// FieldUpdateTime holds the string denoting the update_time field in the database.
	FieldUpdateTime = "update_time"
	// FieldStrategyId holds the string denoting the strategyid field in the database.
	FieldStrategyId = "strategy_id"
	// FieldExchange holds the string denoting the exchange field in the database.
	FieldExchange = "exchange"
	// FieldSymbol holds the string denoting the symbol field in the database.
	FieldSymbol = "symbol"
	// FieldAccount holds the string denoting the account field in the database.
	FieldAccount = "account"
	// FieldLevel holds the string denoting the level field in the database.
	FieldLevel = "level"
	// FieldPrice holds the string denoting the price field in the database.
	FieldPrice = "price"
	// FieldQuantity holds the string denoting the quantity field in the database.
	FieldQuantity = "quantity"
	// FieldBuyClientOrderId holds the string denoting the buyclientorderid field in the database.
	FieldBuyClientOrderId = "buy_client_order_id"
	// FieldBuyClientOrderTime holds the string denoting the buyclientordertime field in the database.
	FieldBuyClientOrderTime = "buy_client_order_time"
	// FieldSellClientOrderId holds the string denoting the sellclientorderid field in the database.
	FieldSellClientOrderId = "sell_client_order_id"
	// FieldSellClientOrderTime holds the string denoting the sellclientordertime field in the database.
	FieldSellClientOrderTime = "sell_client_order_time"
	// Table holds the table name of the grid in the database.
	Table = "grids"
)

// Columns holds all SQL columns for grid fields.
var Columns = []string{
	FieldID,
	FieldCreateTime,
	FieldUpdateTime,
	FieldStrategyId,
	FieldExchange,
	FieldSymbol,
	FieldAccount,
	FieldLevel,
	FieldPrice,
	FieldQuantity,
	FieldBuyClientOrderId,
	FieldBuyClientOrderTime,
	FieldSellClientOrderId,
	FieldSellClientOrderTime,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreateTime holds the default value on creation for the "create_time" field.
	DefaultCreateTime func() time.Time
	// DefaultUpdateTime holds the default value on creation for the "update_time" field.
	DefaultUpdateTime func() time.Time
	// UpdateDefaultUpdateTime holds the default value on update for the "update_time" field.
	UpdateDefaultUpdateTime func() time.Time
	// StrategyIdValidator is a validator for the "strategyId" field. It is called by the builders before save.
	StrategyIdValidator func(string) error
	// ExchangeValidator is a validator for the "exchange" field. It is called by the builders before save.
	ExchangeValidator func(string) error
	// SymbolValidator is a validator for the "symbol" field. It is called by the builders before save.
	SymbolValidator func(string) error
)

// OrderOption defines the ordering options for the Grid queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreateTime orders the results by the create_time field.
func ByCreateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreateTime, opts...).ToFunc()
}

// ByUpdateTime orders the results by the update_time field.
func ByUpdateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdateTime, opts...).ToFunc()
}

// ByStrategyId orders the results by the strategyId field.
func ByStrategyId(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStrategyId, opts...).ToFunc()
}

// ByExchange orders the results by the exchange field.
func ByExchange(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExchange, opts...).ToFunc()
}

// BySymbol orders the results by the symbol field.
func BySymbol(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSymbol, opts...).ToFunc()
}

// ByAccount orders the results by the account field.
func ByAccount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccount, opts...).ToFunc()
}

// ByLevel orders the results by the level field.
func ByLevel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLevel, opts...).ToFunc()
}

// ByPrice orders the results by the price field.
func ByPrice(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPrice, opts...).ToFunc()
}

// ByQuantity orders the results by the quantity field.
func ByQuantity(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldQuantity, opts...).ToFunc()
}

// ByBuyClientOrderId orders the results by the buyClientOrderId field.
func ByBuyClientOrderId(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBuyClientOrderId, opts...).ToFunc()
}

// ByBuyClientOrderTime orders the results by the buyClientOrderTime field.
func ByBuyClientOrderTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBuyClientOrderTime, opts...).ToFunc()
}

// BySellClientOrderId orders the results by the sellClientOrderId field.
func BySellClientOrderId(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSellClientOrderId, opts...).ToFunc()
}

// BySellClientOrderTime orders the results by the sellClientOrderTime field.
func BySellClientOrderTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSellClientOrderTime, opts...).ToFunc()
}
