// Code generated by ent, DO NOT EDIT.

package grid

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/fachebot/omni-grid-bot/internal/ent/predicate"
	"github.com/shopspring/decimal"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Grid {
	return predicate.Grid(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Grid {
	return predicate.Grid(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Grid {
	return predicate.Grid(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Grid {
	return predicate.Grid(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Grid {
	return predicate.Grid(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Grid {
	return predicate.Grid(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Grid {
	return predicate.Grid(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Grid {
	return predicate.Grid(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Grid {
	return predicate.Grid(sql.FieldLTE(FieldID, id))
}

// CreateTime applies equality check predicate on the "create_time" field. It's identical to CreateTimeEQ.
func CreateTime(v time.Time) predicate.Grid {
	return predicate.Grid(sql.FieldEQ(FieldCreateTime, v))
}

// UpdateTime applies equality check predicate on the "update_time" field. It's identical to UpdateTimeEQ.
func UpdateTime(v time.Time) predicate.Grid {
	return predicate.Grid(sql.FieldEQ(FieldUpdateTime, v))
}

// StrategyId applies equality check predicate on the "strategyId" field. It's identical to StrategyIdEQ.
func StrategyId(v string) predicate.Grid {
	return predicate.Grid(sql.FieldEQ(FieldStrategyId, v))
}

// Exchange applies equality check predicate on the "exchange" field. It's identical to ExchangeEQ.
func Exchange(v string) predicate.Grid {
	return predicate.Grid(sql.FieldEQ(FieldExchange, v))
}

// Symbol applies equality check predicate on the "symbol" field. It's identical to SymbolEQ.
func Symbol(v string) predicate.Grid {
	return predicate.Grid(sql.FieldEQ(FieldSymbol, v))
}

// Account applies equality check predicate on the "account" field. It's identical to AccountEQ.
func Account(v string) predicate.Grid {
	return predicate.Grid(sql.FieldEQ(FieldAccount, v))
}

// Level applies equality check predicate on the "level" field. It's identical to LevelEQ.
func Level(v int) predicate.Grid {
	return predicate.Grid(sql.FieldEQ(FieldLevel, v))
}

// Price applies equality check predicate on the "price" field. It's identical to PriceEQ.
func Price(v decimal.Decimal) predicate.Grid {
	return predicate.Grid(sql.FieldEQ(FieldPrice, v))
}

// Quantity applies equality check predicate on the "quantity" field. It's identical to QuantityEQ.
func Quantity(v decimal.Decimal) predicate.Grid {
	return predicate.Grid(sql.FieldEQ(FieldQuantity, v))
}

// BuyClientOrderId applies equality check predicate on the "buyClientOrderId" field. It's identical to BuyClientOrderIdEQ.
func BuyClientOrderId(v string) predicate.Grid {
	return predicate.Grid(sql.FieldEQ(FieldBuyClientOrderId, v))
}

// SellClientOrderId applies equality check predicate on the "sellClientOrderId" field. It's identical to SellClientOrderIdEQ.
func SellClientOrderId(v string) predicate.Grid {
	return predicate.Grid(sql.FieldEQ(FieldSellClientOrderId, v))
}

// CreateTimeEQ applies the EQ predicate on the "create_time" field.
func CreateTimeEQ(v time.Time) predicate.Grid {
	return predicate.Grid(sql.FieldEQ(FieldCreateTime, v))
}

// CreateTimeNEQ applies the NEQ predicate on the "create_time" field.
func CreateTimeNEQ(v time.Time) predicate.Grid {
	return predicate.Grid(sql.FieldNEQ(FieldCreateTime, v))
}

// CreateTimeIn applies the In predicate on the "create_time" field.
func CreateTimeIn(vs ...time.Time) predicate.Grid {
	return predicate.Grid(sql.FieldIn(FieldCreateTime, vs...))
}

// CreateTimeNotIn applies the NotIn predicate on the "create_time" field.
func CreateTimeNotIn(vs ...time.Time) predicate.Grid {
	return predicate.Grid(sql.FieldNotIn(FieldCreateTime, vs...))
}

// CreateTimeGT applies the GT predicate on the "create_time" field.
func CreateTimeGT(v time.Time) predicate.Grid {
	return predicate.Grid(sql.FieldGT(FieldCreateTime, v))
}

// CreateTimeGTE applies the GTE predicate on the "create_time" field.
func CreateTimeGTE(v time.Time) predicate.Grid {
	return predicate.Grid(sql.FieldGTE(FieldCreateTime, v))
}

// CreateTimeLT applies the LT predicate on the "create_time" field.
func CreateTimeLT(v time.Time) predicate.Grid {
	return predicate.Grid(sql.FieldLT(FieldCreateTime, v))
}

// CreateTimeLTE applies the LTE predicate on the "create_time" field.
func CreateTimeLTE(v time.Time) predicate.Grid {
	return predicate.Grid(sql.FieldLTE(FieldCreateTime, v))
}

// UpdateTimeEQ applies the EQ predicate on the "update_time" field.
func UpdateTimeEQ(v time.Time) predicate.Grid {
	return predicate.Grid(sql.FieldEQ(FieldUpdateTime, v))
}

// UpdateTimeNEQ applies the NEQ predicate on the "update_time" field.
func UpdateTimeNEQ(v time.Time) predicate.Grid {
	return predicate.Grid(sql.FieldNEQ(FieldUpdateTime, v))
}

// UpdateTimeIn applies the In predicate on the "update_time" field.
func UpdateTimeIn(vs ...time.Time) predicate.Grid {
	return predicate.Grid(sql.FieldIn(FieldUpdateTime, vs...))
}

// UpdateTimeNotIn applies the NotIn predicate on the "update_time" field.
func UpdateTimeNotIn(vs ...time.Time) predicate.Grid {
	return predicate.Grid(sql.FieldNotIn(FieldUpdateTime, vs...))
}

// UpdateTimeGT applies the GT predicate on the "update_time" field.
func UpdateTimeGT(v time.Time) predicate.Grid {
	return predicate.Grid(sql.FieldGT(FieldUpdateTime, v))
}

// UpdateTimeGTE applies the GTE predicate on the "update_time" field.
func UpdateTimeGTE(v time.Time) predicate.Grid {
	return predicate.Grid(sql.FieldGTE(FieldUpdateTime, v))
}

// UpdateTimeLT applies the LT predicate on the "update_time" field.
func UpdateTimeLT(v time.Time) predicate.Grid {
	return predicate.Grid(sql.FieldLT(FieldUpdateTime, v))
}

// UpdateTimeLTE applies the LTE predicate on the "update_time" field.
func UpdateTimeLTE(v time.Time) predicate.Grid {
	return predicate.Grid(sql.FieldLTE(FieldUpdateTime, v))
}

// StrategyIdEQ applies the EQ predicate on the "strategyId" field.
func StrategyIdEQ(v string) predicate.Grid {
	return predicate.Grid(sql.FieldEQ(FieldStrategyId, v))
}

// StrategyIdNEQ applies the NEQ predicate on the "strategyId" field.
func StrategyIdNEQ(v string) predicate.Grid {
	return predicate.Grid(sql.FieldNEQ(FieldStrategyId, v))
}

// StrategyIdIn applies the In predicate on the "strategyId" field.
func StrategyIdIn(vs ...string) predicate.Grid {
	return predicate.Grid(sql.FieldIn(FieldStrategyId, vs...))
}

// StrategyIdNotIn applies the NotIn predicate on the "strategyId" field.
func StrategyIdNotIn(vs ...string) predicate.Grid {
	return predicate.Grid(sql.FieldNotIn(FieldStrategyId, vs...))
}

// StrategyIdGT applies the GT predicate on the "strategyId" field.
func StrategyIdGT(v string) predicate.Grid {
	return predicate.Grid(sql.FieldGT(FieldStrategyId, v))
}

// StrategyIdGTE applies the GTE predicate on the "strategyId" field.
func StrategyIdGTE(v string) predicate.Grid {
	return predicate.Grid(sql.FieldGTE(FieldStrategyId, v))
}

// StrategyIdLT applies the LT predicate on the "strategyId" field.
func StrategyIdLT(v string) predicate.Grid {
	return predicate.Grid(sql.FieldLT(FieldStrategyId, v))
}

// StrategyIdLTE applies the LTE predicate on the "strategyId" field.
func StrategyIdLTE(v string) predicate.Grid {
	return predicate.Grid(sql.FieldLTE(FieldStrategyId, v))
}

// StrategyIdContains applies the Contains predicate on the "strategyId" field.
func StrategyIdContains(v string) predicate.Grid {
	return predicate.Grid(sql.FieldContains(FieldStrategyId, v))
}

// StrategyIdHasPrefix applies the HasPrefix predicate on the "strategyId" field.
func StrategyIdHasPrefix(v string) predicate.Grid {
	return predicate.Grid(sql.FieldHasPrefix(FieldStrategyId, v))
}

// StrategyIdHasSuffix applies the HasSuffix predicate on the "strategyId" field.
func StrategyIdHasSuffix(v string) predicate.Grid {
	return predicate.Grid(sql.FieldHasSuffix(FieldStrategyId, v))
}

// StrategyIdEqualFold applies the EqualFold predicate on the "strategyId" field.
func StrategyIdEqualFold(v string) predicate.Grid {
	return predicate.Grid(sql.FieldEqualFold(FieldStrategyId, v))
}

// StrategyIdContainsFold applies the ContainsFold predicate on the "strategyId" field.
func StrategyIdContainsFold(v string) predicate.Grid {
	return predicate.Grid(sql.FieldContainsFold(FieldStrategyId, v))
}

// ExchangeEQ applies the EQ predicate on the "exchange" field.
func ExchangeEQ(v string) predicate.Grid {
	return predicate.Grid(sql.FieldEQ(FieldExchange, v))
}

// ExchangeNEQ applies the NEQ predicate on the "exchange" field.
func ExchangeNEQ(v string) predicate.Grid {
	return predicate.Grid(sql.FieldNEQ(FieldExchange, v))
}

// ExchangeIn applies the In predicate on the "exchange" field.
func ExchangeIn(vs ...string) predicate.Grid {
	return predicate.Grid(sql.FieldIn(FieldExchange, vs...))
}

// ExchangeNotIn applies the NotIn predicate on the "exchange" field.
func ExchangeNotIn(vs ...string) predicate.Grid {
	return predicate.Grid(sql.FieldNotIn(FieldExchange, vs...))
}

// ExchangeGT applies the GT predicate on the "exchange" field.
func ExchangeGT(v string) predicate.Grid {
	return predicate.Grid(sql.FieldGT(FieldExchange, v))
}

// ExchangeGTE applies the GTE predicate on the "exchange" field.
func ExchangeGTE(v string) predicate.Grid {
	return predicate.Grid(sql.FieldGTE(FieldExchange, v))
}

// ExchangeLT applies the LT predicate on the "exchange" field.
func ExchangeLT(v string) predicate.Grid {
	return predicate.Grid(sql.FieldLT(FieldExchange, v))
}

// ExchangeLTE applies the LTE predicate on the "exchange" field.
func ExchangeLTE(v string) predicate.Grid {
	return predicate.Grid(sql.FieldLTE(FieldExchange, v))
}

// ExchangeContains applies the Contains predicate on the "exchange" field.
func ExchangeContains(v string) predicate.Grid {
	return predicate.Grid(sql.FieldContains(FieldExchange, v))
}

// ExchangeHasPrefix applies the HasPrefix predicate on the "exchange" field.
func ExchangeHasPrefix(v string) predicate.Grid {
	return predicate.Grid(sql.FieldHasPrefix(FieldExchange, v))
}

// ExchangeHasSuffix applies the HasSuffix predicate on the "exchange" field.
func ExchangeHasSuffix(v string) predicate.Grid {
	return predicate.Grid(sql.FieldHasSuffix(FieldExchange, v))
}

// ExchangeEqualFold applies the EqualFold predicate on the "exchange" field.
func ExchangeEqualFold(v string) predicate.Grid {
	return predicate.Grid(sql.FieldEqualFold(FieldExchange, v))
}

// ExchangeContainsFold applies the ContainsFold predicate on the "exchange" field.
func ExchangeContainsFold(v string) predicate.Grid {
	return predicate.Grid(sql.FieldContainsFold(FieldExchange, v))
}

// SymbolEQ applies the EQ predicate on the "symbol" field.
func SymbolEQ(v string) predicate.Grid {
	return predicate.Grid(sql.FieldEQ(FieldSymbol, v))
}

// SymbolNEQ applies the NEQ predicate on the "symbol" field.
func SymbolNEQ(v string) predicate.Grid {
	return predicate.Grid(sql.FieldNEQ(FieldSymbol, v))
}

// SymbolIn applies the In predicate on the "symbol" field.
func SymbolIn(vs ...string) predicate.Grid {
	return predicate.Grid(sql.FieldIn(FieldSymbol, vs...))
}

// SymbolNotIn applies the NotIn predicate on the "symbol" field.
func SymbolNotIn(vs ...string) predicate.Grid {
	return predicate.Grid(sql.FieldNotIn(FieldSymbol, vs...))
}

// SymbolGT applies the GT predicate on the "symbol" field.
func SymbolGT(v string) predicate.Grid {
	return predicate.Grid(sql.FieldGT(FieldSymbol, v))
}

// SymbolGTE applies the GTE predicate on the "symbol" field.
func SymbolGTE(v string) predicate.Grid {
	return predicate.Grid(sql.FieldGTE(FieldSymbol, v))
}

// SymbolLT applies the LT predicate on the "symbol" field.
func SymbolLT(v string) predicate.Grid {
	return predicate.Grid(sql.FieldLT(FieldSymbol, v))
}

// SymbolLTE applies the LTE predicate on the "symbol" field.
func SymbolLTE(v string) predicate.Grid {
	return predicate.Grid(sql.FieldLTE(FieldSymbol, v))
}

// SymbolContains applies the Contains predicate on the "symbol" field.
func SymbolContains(v string) predicate.Grid {
	return predicate.Grid(sql.FieldContains(FieldSymbol, v))
}

// SymbolHasPrefix applies the HasPrefix predicate on the "symbol" field.
func SymbolHasPrefix(v string) predicate.Grid {
	return predicate.Grid(sql.FieldHasPrefix(FieldSymbol, v))
}

// SymbolHasSuffix applies the HasSuffix predicate on the "symbol" field.
func SymbolHasSuffix(v string) predicate.Grid {
	return predicate.Grid(sql.FieldHasSuffix(FieldSymbol, v))
}

// SymbolEqualFold applies the EqualFold predicate on the "symbol" field.
func SymbolEqualFold(v string) predicate.Grid {
	return predicate.Grid(sql.FieldEqualFold(FieldSymbol, v))
}

// SymbolContainsFold applies the ContainsFold predicate on the "symbol" field.
func SymbolContainsFold(v string) predicate.Grid {
	return predicate.Grid(sql.FieldContainsFold(FieldSymbol, v))
}

// AccountEQ applies the EQ predicate on the "account" field.
func AccountEQ(v string) predicate.Grid {
	return predicate.Grid(sql.FieldEQ(FieldAccount, v))
}

// AccountNEQ applies the NEQ predicate on the "account" field.
func AccountNEQ(v string) predicate.Grid {
	return predicate.Grid(sql.FieldNEQ(FieldAccount, v))
}

// AccountIn applies the In predicate on the "account" field.
func AccountIn(vs ...string) predicate.Grid {
	return predicate.Grid(sql.FieldIn(FieldAccount, vs...))
}

// AccountNotIn applies the NotIn predicate on the "account" field.
func AccountNotIn(vs ...string) predicate.Grid {
	return predicate.Grid(sql.FieldNotIn(FieldAccount, vs...))
}

// AccountGT applies the GT predicate on the "account" field.
func AccountGT(v string) predicate.Grid {
	return predicate.Grid(sql.FieldGT(FieldAccount, v))
}

// AccountGTE applies the GTE predicate on the "account" field.
func AccountGTE(v string) predicate.Grid {
	return predicate.Grid(sql.FieldGTE(FieldAccount, v))
}

// AccountLT applies the LT predicate on the "account" field.
func AccountLT(v string) predicate.Grid {
	return predicate.Grid(sql.FieldLT(FieldAccount, v))
}

// AccountLTE applies the LTE predicate on the "account" field.
func AccountLTE(v string) predicate.Grid {
	return predicate.Grid(sql.FieldLTE(FieldAccount, v))
}

// AccountContains applies the Contains predicate on the "account" field.
func AccountContains(v string) predicate.Grid {
	return predicate.Grid(sql.FieldContains(FieldAccount, v))
}

// AccountHasPrefix applies the HasPrefix predicate on the "account" field.
func AccountHasPrefix(v string) predicate.Grid {
	return predicate.Grid(sql.FieldHasPrefix(FieldAccount, v))
}

// AccountHasSuffix applies the HasSuffix predicate on the "account" field.
func AccountHasSuffix(v string) predicate.Grid {
	return predicate.Grid(sql.FieldHasSuffix(FieldAccount, v))
}

// AccountEqualFold applies the EqualFold predicate on the "account" field.
func AccountEqualFold(v string) predicate.Grid {
	return predicate.Grid(sql.FieldEqualFold(FieldAccount, v))
}

// AccountContainsFold applies the ContainsFold predicate on the "account" field.
func AccountContainsFold(v string) predicate.Grid {
	return predicate.Grid(sql.FieldContainsFold(FieldAccount, v))
}

// LevelEQ applies the EQ predicate on the "level" field.
func LevelEQ(v int) predicate.Grid {
	return predicate.Grid(sql.FieldEQ(FieldLevel, v))
}

// LevelNEQ applies the NEQ predicate on the "level" field.
func LevelNEQ(v int) predicate.Grid {
	return predicate.Grid(sql.FieldNEQ(FieldLevel, v))
}

// LevelIn applies the In predicate on the "level" field.
func LevelIn(vs ...int) predicate.Grid {
	return predicate.Grid(sql.FieldIn(FieldLevel, vs...))
}

// LevelNotIn applies the NotIn predicate on the "level" field.
func LevelNotIn(vs ...int) predicate.Grid {
	return predicate.Grid(sql.FieldNotIn(FieldLevel, vs...))
}

// LevelGT applies the GT predicate on the "level" field.
func LevelGT(v int) predicate.Grid {
	return predicate.Grid(sql.FieldGT(FieldLevel, v))
}

// LevelGTE applies the GTE predicate on the "level" field.
func LevelGTE(v int) predicate.Grid {
	return predicate.Grid(sql.FieldGTE(FieldLevel, v))
}

// LevelLT applies the LT predicate on the "level" field.
func LevelLT(v int) predicate.Grid {
	return predicate.Grid(sql.FieldLT(FieldLevel, v))
}

// LevelLTE applies the LTE predicate on the "level" field.
func LevelLTE(v int) predicate.Grid {
	return predicate.Grid(sql.FieldLTE(FieldLevel, v))
}

// PriceEQ applies the EQ predicate on the "price" field.
func PriceEQ(v decimal.Decimal) predicate.Grid {
	return predicate.Grid(sql.FieldEQ(FieldPrice, v))
}

// PriceNEQ applies the NEQ predicate on the "price" field.
func PriceNEQ(v decimal.Decimal) predicate.Grid {
	return predicate.Grid(sql.FieldNEQ(FieldPrice, v))
}

// PriceIn applies the In predicate on the "price" field.
func PriceIn(vs ...decimal.Decimal) predicate.Grid {
	return predicate.Grid(sql.FieldIn(FieldPrice, vs...))
}

// PriceNotIn applies the NotIn predicate on the "price" field.
func PriceNotIn(vs ...decimal.Decimal) predicate.Grid {
	return predicate.Grid(sql.FieldNotIn(FieldPrice, vs...))
}

// PriceGT applies the GT predicate on the "price" field.
func PriceGT(v decimal.Decimal) predicate.Grid {
	return predicate.Grid(sql.FieldGT(FieldPrice, v))
}

// PriceGTE applies the GTE predicate on the "price" field.
func PriceGTE(v decimal.Decimal) predicate.Grid {
	return predicate.Grid(sql.FieldGTE(FieldPrice, v))
}

// PriceLT applies the LT predicate on the "price" field.
func PriceLT(v decimal.Decimal) predicate.Grid {
	return predicate.Grid(sql.FieldLT(FieldPrice, v))
}

// PriceLTE applies the LTE predicate on the "price" field.
func PriceLTE(v decimal.Decimal) predicate.Grid {
	return predicate.Grid(sql.FieldLTE(FieldPrice, v))
}

// PriceContains applies the Contains predicate on the "price" field.
func PriceContains(v decimal.Decimal) predicate.Grid {
	vc := v.String()
	return predicate.Grid(sql.FieldContains(FieldPrice, vc))
}

// PriceHasPrefix applies the HasPrefix predicate on the "price" field.
func PriceHasPrefix(v decimal.Decimal) predicate.Grid {
	vc := v.String()
	return predicate.Grid(sql.FieldHasPrefix(FieldPrice, vc))
}

// PriceHasSuffix applies the HasSuffix predicate on the "price" field.
func PriceHasSuffix(v decimal.Decimal) predicate.Grid {
	vc := v.String()
	return predicate.Grid(sql.FieldHasSuffix(FieldPrice, vc))
}

// PriceEqualFold applies the EqualFold predicate on the "price" field.
func PriceEqualFold(v decimal.Decimal) predicate.Grid {
	vc := v.String()
	return predicate.Grid(sql.FieldEqualFold(FieldPrice, vc))
}

// PriceContainsFold applies the ContainsFold predicate on the "price" field.
func PriceContainsFold(v decimal.Decimal) predicate.Grid {
	vc := v.String()
	return predicate.Grid(sql.FieldContainsFold(FieldPrice, vc))
}

// QuantityEQ applies the EQ predicate on the "quantity" field.
func QuantityEQ(v decimal.Decimal) predicate.Grid {
	return predicate.Grid(sql.FieldEQ(FieldQuantity, v))
}

// QuantityNEQ applies the NEQ predicate on the "quantity" field.
func QuantityNEQ(v decimal.Decimal) predicate.Grid {
	return predicate.Grid(sql.FieldNEQ(FieldQuantity, v))
}

// QuantityIn applies the In predicate on the "quantity" field.
func QuantityIn(vs ...decimal.Decimal) predicate.Grid {
	return predicate.Grid(sql.FieldIn(FieldQuantity, vs...))
}

// QuantityNotIn applies the NotIn predicate on the "quantity" field.
func QuantityNotIn(vs ...decimal.Decimal) predicate.Grid {
	return predicate.Grid(sql.FieldNotIn(FieldQuantity, vs...))
}

// QuantityGT applies the GT predicate on the "quantity" field.
func QuantityGT(v decimal.Decimal) predicate.Grid {
	return predicate.Grid(sql.FieldGT(FieldQuantity, v))
}

// QuantityGTE applies the GTE predicate on the "quantity" field.
func QuantityGTE(v decimal.Decimal) predicate.Grid {
	return predicate.Grid(sql.FieldGTE(FieldQuantity, v))
}

// QuantityLT applies the LT predicate on the "quantity" field.
func QuantityLT(v decimal.Decimal) predicate.Grid {
	return predicate.Grid(sql.FieldLT(FieldQuantity, v))
}

// QuantityLTE applies the LTE predicate on the "quantity" field.
func QuantityLTE(v decimal.Decimal) predicate.Grid {
	return predicate.Grid(sql.FieldLTE(FieldQuantity, v))
}

// QuantityContains applies the Contains predicate on the "quantity" field.
func QuantityContains(v decimal.Decimal) predicate.Grid {
	vc := v.String()
	return predicate.Grid(sql.FieldContains(FieldQuantity, vc))
}

// QuantityHasPrefix applies the HasPrefix predicate on the "quantity" field.
func QuantityHasPrefix(v decimal.Decimal) predicate.Grid {
	vc := v.String()
	return predicate.Grid(sql.FieldHasPrefix(FieldQuantity, vc))
}

// QuantityHasSuffix applies the HasSuffix predicate on the "quantity" field.
func QuantityHasSuffix(v decimal.Decimal) predicate.Grid {
	vc := v.String()
	return predicate.Grid(sql.FieldHasSuffix(FieldQuantity, vc))
}

// QuantityEqualFold applies the EqualFold predicate on the "quantity" field.
func QuantityEqualFold(v decimal.Decimal) predicate.Grid {
	vc := v.String()
	return predicate.Grid(sql.FieldEqualFold(FieldQuantity, vc))
}

// QuantityContainsFold applies the ContainsFold predicate on the "quantity" field.
func QuantityContainsFold(v decimal.Decimal) predicate.Grid {
	vc := v.String()
	return predicate.Grid(sql.FieldContainsFold(FieldQuantity, vc))
}

// BuyClientOrderIdEQ applies the EQ predicate on the "buyClientOrderId" field.
func BuyClientOrderIdEQ(v string) predicate.Grid {
	return predicate.Grid(sql.FieldEQ(FieldBuyClientOrderId, v))
}

// BuyClientOrderIdNEQ applies the NEQ predicate on the "buyClientOrderId" field.
func BuyClientOrderIdNEQ(v string) predicate.Grid {
	return predicate.Grid(sql.FieldNEQ(FieldBuyClientOrderId, v))
}

// BuyClientOrderIdIn applies the In predicate on the "buyClientOrderId" field.
func BuyClientOrderIdIn(vs ...string) predicate.Grid {
	return predicate.Grid(sql.FieldIn(FieldBuyClientOrderId, vs...))
}

// BuyClientOrderIdNotIn applies the NotIn predicate on the "buyClientOrderId" field.
func BuyClientOrderIdNotIn(vs ...string) predicate.Grid {
	return predicate.Grid(sql.FieldNotIn(FieldBuyClientOrderId, vs...))
}

// BuyClientOrderIdGT applies the GT predicate on the "buyClientOrderId" field.
func BuyClientOrderIdGT(v string) predicate.Grid {
	return predicate.Grid(sql.FieldGT(FieldBuyClientOrderId, v))
}

// BuyClientOrderIdGTE applies the GTE predicate on the "buyClientOrderId" field.
func BuyClientOrderIdGTE(v string) predicate.Grid {
	return predicate.Grid(sql.FieldGTE(FieldBuyClientOrderId, v))
}

// BuyClientOrderIdLT applies the LT predicate on the "buyClientOrderId" field.
func BuyClientOrderIdLT(v string) predicate.Grid {
	return predicate.Grid(sql.FieldLT(FieldBuyClientOrderId, v))
}

// BuyClientOrderIdLTE applies the LTE predicate on the "buyClientOrderId" field.
func BuyClientOrderIdLTE(v string) predicate.Grid {
	return predicate.Grid(sql.FieldLTE(FieldBuyClientOrderId, v))
}

// BuyClientOrderIdContains applies the Contains predicate on the "buyClientOrderId" field.
func BuyClientOrderIdContains(v string) predicate.Grid {
	return predicate.Grid(sql.FieldContains(FieldBuyClientOrderId, v))
}

// BuyClientOrderIdHasPrefix applies the HasPrefix predicate on the "buyClientOrderId" field.
func BuyClientOrderIdHasPrefix(v string) predicate.Grid {
	return predicate.Grid(sql.FieldHasPrefix(FieldBuyClientOrderId, v))
}

// BuyClientOrderIdHasSuffix applies the HasSuffix predicate on the "buyClientOrderId" field.
func BuyClientOrderIdHasSuffix(v string) predicate.Grid {
	return predicate.Grid(sql.FieldHasSuffix(FieldBuyClientOrderId, v))
}

// BuyClientOrderIdIsNil applies the IsNil predicate on the "buyClientOrderId" field.
func BuyClientOrderIdIsNil() predicate.Grid {
	return predicate.Grid(sql.FieldIsNull(FieldBuyClientOrderId))
}

// BuyClientOrderIdNotNil applies the NotNil predicate on the "buyClientOrderId" field.
func BuyClientOrderIdNotNil() predicate.Grid {
	return predicate.Grid(sql.FieldNotNull(FieldBuyClientOrderId))
}

// BuyClientOrderIdEqualFold applies the EqualFold predicate on the "buyClientOrderId" field.
func BuyClientOrderIdEqualFold(v string) predicate.Grid {
	return predicate.Grid(sql.FieldEqualFold(FieldBuyClientOrderId, v))
}

// BuyClientOrderIdContainsFold applies the ContainsFold predicate on the "buyClientOrderId" field.
func BuyClientOrderIdContainsFold(v string) predicate.Grid {
	return predicate.Grid(sql.FieldContainsFold(FieldBuyClientOrderId, v))
}

// SellClientOrderIdEQ applies the EQ predicate on the "sellClientOrderId" field.
func SellClientOrderIdEQ(v string) predicate.Grid {
	return predicate.Grid(sql.FieldEQ(FieldSellClientOrderId, v))
}

// SellClientOrderIdNEQ applies the NEQ predicate on the "sellClientOrderId" field.
func SellClientOrderIdNEQ(v string) predicate.Grid {
	return predicate.Grid(sql.FieldNEQ(FieldSellClientOrderId, v))
}

// SellClientOrderIdIn applies the In predicate on the "sellClientOrderId" field.
func SellClientOrderIdIn(vs ...string) predicate.Grid {
	return predicate.Grid(sql.FieldIn(FieldSellClientOrderId, vs...))
}

// SellClientOrderIdNotIn applies the NotIn predicate on the "sellClientOrderId" field.
func SellClientOrderIdNotIn(vs ...string) predicate.Grid {
	return predicate.Grid(sql.FieldNotIn(FieldSellClientOrderId, vs...))
}

// SellClientOrderIdGT applies the GT predicate on the "sellClientOrderId" field.
func SellClientOrderIdGT(v string) predicate.Grid {
	return predicate.Grid(sql.FieldGT(FieldSellClientOrderId, v))
}

// SellClientOrderIdGTE applies the GTE predicate on the "sellClientOrderId" field.
func SellClientOrderIdGTE(v string) predicate.Grid {
	return predicate.Grid(sql.FieldGTE(FieldSellClientOrderId, v))
}

// SellClientOrderIdLT applies the LT predicate on the "sellClientOrderId" field.
func SellClientOrderIdLT(v string) predicate.Grid {
	return predicate.Grid(sql.FieldLT(FieldSellClientOrderId, v))
}

// SellClientOrderIdLTE applies the LTE predicate on the "sellClientOrderId" field.
func SellClientOrderIdLTE(v string) predicate.Grid {
	return predicate.Grid(sql.FieldLTE(FieldSellClientOrderId, v))
}

// SellClientOrderIdContains applies the Contains predicate on the "sellClientOrderId" field.
func SellClientOrderIdContains(v string) predicate.Grid {
	return predicate.Grid(sql.FieldContains(FieldSellClientOrderId, v))
}

// SellClientOrderIdHasPrefix applies the HasPrefix predicate on the "sellClientOrderId" field.
func SellClientOrderIdHasPrefix(v string) predicate.Grid {
	return predicate.Grid(sql.FieldHasPrefix(FieldSellClientOrderId, v))
}

// SellClientOrderIdHasSuffix applies the HasSuffix predicate on the "sellClientOrderId" field.
func SellClientOrderIdHasSuffix(v string) predicate.Grid {
	return predicate.Grid(sql.FieldHasSuffix(FieldSellClientOrderId, v))
}

// SellClientOrderIdIsNil applies the IsNil predicate on the "sellClientOrderId" field.
func SellClientOrderIdIsNil() predicate.Grid {
	return predicate.Grid(sql.FieldIsNull(FieldSellClientOrderId))
}

// SellClientOrderIdNotNil applies the NotNil predicate on the "sellClientOrderId" field.
func SellClientOrderIdNotNil() predicate.Grid {
	return predicate.Grid(sql.FieldNotNull(FieldSellClientOrderId))
}

// SellClientOrderIdEqualFold applies the EqualFold predicate on the "sellClientOrderId" field.
func SellClientOrderIdEqualFold(v string) predicate.Grid {
	return predicate.Grid(sql.FieldEqualFold(FieldSellClientOrderId, v))
}

// SellClientOrderIdContainsFold applies the ContainsFold predicate on the "sellClientOrderId" field.
func SellClientOrderIdContainsFold(v string) predicate.Grid {
	return predicate.Grid(sql.FieldContainsFold(FieldSellClientOrderId, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Grid) predicate.Grid {
	return predicate.Grid(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Grid) predicate.Grid {
	return predicate.Grid(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Grid) predicate.Grid {
	return predicate.Grid(sql.NotPredicates(p))
}
