// Code generated by ent, DO NOT EDIT.

package matchedtrade

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the matchedtrade type in the database.
	Label = "matched_trade"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreateTime holds the string denoting the create_time field in the database.
	FieldCreateTime = "create_time"
	// FieldUpdateTime holds the string denoting the update_time field in the database.
	FieldUpdateTime = "update_time"
	// FieldStrategyId holds the string denoting the strategyid field in the database.
	FieldStrategyId = "strategy_id"
	// FieldAccount holds the string denoting the account field in the database.
	FieldAccount = "account"
	// FieldSymbol holds the string denoting the symbol field in the database.
	FieldSymbol = "symbol"
	// FieldBuyClientOrderId holds the string denoting the buyclientorderid field in the database.
	FieldBuyClientOrderId = "buy_client_order_id"
	// FieldBuyBaseAmount holds the string denoting the buybaseamount field in the database.
	FieldBuyBaseAmount = "buy_base_amount"
	// FieldBuyQuoteAmount holds the string denoting the buyquoteamount field in the database.
	FieldBuyQuoteAmount = "buy_quote_amount"
	// FieldBuyOrderTimestamp holds the string denoting the buyordertimestamp field in the database.
	FieldBuyOrderTimestamp = "buy_order_timestamp"
	// FieldSellClientOrderId holds the string denoting the sellclientorderid field in the database.
	FieldSellClientOrderId = "sell_client_order_id"
	// FieldSellBaseAmount holds the string denoting the sellbaseamount field in the database.
	FieldSellBaseAmount = "sell_base_amount"
	// FieldSellQuoteAmount holds the string denoting the sellquoteamount field in the database.
	FieldSellQuoteAmount = "sell_quote_amount"
	// FieldSellOrderTimestamp holds the string denoting the sellordertimestamp field in the database.
	FieldSellOrderTimestamp = "sell_order_timestamp"
	// FieldProfit holds the string denoting the profit field in the database.
	FieldProfit = "profit"
	// Table holds the table name of the matchedtrade in the database.
	Table = "matched_trades"
)

// Columns holds all SQL columns for matchedtrade fields.
var Columns = []string{
	FieldID,
	FieldCreateTime,
	FieldUpdateTime,
	FieldStrategyId,
	FieldAccount,
	FieldSymbol,
	FieldBuyClientOrderId,
	FieldBuyBaseAmount,
	FieldBuyQuoteAmount,
	FieldBuyOrderTimestamp,
	FieldSellClientOrderId,
	FieldSellBaseAmount,
	FieldSellQuoteAmount,
	FieldSellOrderTimestamp,
	FieldProfit,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreateTime holds the default value on creation for the "create_time" field.
	DefaultCreateTime func() time.Time
	// DefaultUpdateTime holds the default value on creation for the "update_time" field.
	DefaultUpdateTime func() time.Time
	// UpdateDefaultUpdateTime holds the default value on update for the "update_time" field.
	UpdateDefaultUpdateTime func() time.Time
	// StrategyIdValidator is a validator for the "strategyId" field. It is called by the builders before save.
	StrategyIdValidator func(string) error
)

// OrderOption defines the ordering options for the MatchedTrade queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreateTime orders the results by the create_time field.
func ByCreateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreateTime, opts...).ToFunc()
}

// ByUpdateTime orders the results by the update_time field.
func ByUpdateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdateTime, opts...).ToFunc()
}

// ByStrategyId orders the results by the strategyId field.
func ByStrategyId(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStrategyId, opts...).ToFunc()
}

// ByAccount orders the results by the account field.
func ByAccount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccount, opts...).ToFunc()
}

// BySymbol orders the results by the symbol field.
func BySymbol(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSymbol, opts...).ToFunc()
}

// ByBuyClientOrderId orders the results by the buyClientOrderId field.
func ByBuyClientOrderId(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBuyClientOrderId, opts...).ToFunc()
}

// ByBuyBaseAmount orders the results by the buyBaseAmount field.
func ByBuyBaseAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBuyBaseAmount, opts...).ToFunc()
}

// ByBuyQuoteAmount orders the results by the buyQuoteAmount field.
func ByBuyQuoteAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBuyQuoteAmount, opts...).ToFunc()
}

// ByBuyOrderTimestamp orders the results by the buyOrderTimestamp field.
func ByBuyOrderTimestamp(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBuyOrderTimestamp, opts...).ToFunc()
}

// BySellClientOrderId orders the results by the sellClientOrderId field.
func BySellClientOrderId(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSellClientOrderId, opts...).ToFunc()
}

// BySellBaseAmount orders the results by the sellBaseAmount field.
func BySellBaseAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSellBaseAmount, opts...).ToFunc()
}

// BySellQuoteAmount orders the results by the sellQuoteAmount field.
func BySellQuoteAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSellQuoteAmount, opts...).ToFunc()
}

// BySellOrderTimestamp orders the results by the sellOrderTimestamp field.
func BySellOrderTimestamp(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSellOrderTimestamp, opts...).ToFunc()
}

// ByProfit orders the results by the profit field.
func ByProfit(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProfit, opts...).ToFunc()
}
