// Code generated by ent, DO NOT EDIT.

package syncprogress

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/fachebot/perp-dex-grid-bot/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.SyncProgress {
	return predicate.SyncProgress(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.SyncProgress {
	return predicate.SyncProgress(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.SyncProgress {
	return predicate.SyncProgress(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.SyncProgress {
	return predicate.SyncProgress(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.SyncProgress {
	return predicate.SyncProgress(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.SyncProgress {
	return predicate.SyncProgress(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.SyncProgress {
	return predicate.SyncProgress(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.SyncProgress {
	return predicate.SyncProgress(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.SyncProgress {
	return predicate.SyncProgress(sql.FieldLTE(FieldID, id))
}

// CreateTime applies equality check predicate on the "create_time" field. It's identical to CreateTimeEQ.
func CreateTime(v time.Time) predicate.SyncProgress {
	return predicate.SyncProgress(sql.FieldEQ(FieldCreateTime, v))
}

// UpdateTime applies equality check predicate on the "update_time" field. It's identical to UpdateTimeEQ.
func UpdateTime(v time.Time) predicate.SyncProgress {
	return predicate.SyncProgress(sql.FieldEQ(FieldUpdateTime, v))
}

// Exchange applies equality check predicate on the "exchange" field. It's identical to ExchangeEQ.
func Exchange(v string) predicate.SyncProgress {
	return predicate.SyncProgress(sql.FieldEQ(FieldExchange, v))
}

// Account applies equality check predicate on the "account" field. It's identical to AccountEQ.
func Account(v string) predicate.SyncProgress {
	return predicate.SyncProgress(sql.FieldEQ(FieldAccount, v))
}

// Timestamp applies equality check predicate on the "timestamp" field. It's identical to TimestampEQ.
func Timestamp(v int64) predicate.SyncProgress {
	return predicate.SyncProgress(sql.FieldEQ(FieldTimestamp, v))
}

// CreateTimeEQ applies the EQ predicate on the "create_time" field.
func CreateTimeEQ(v time.Time) predicate.SyncProgress {
	return predicate.SyncProgress(sql.FieldEQ(FieldCreateTime, v))
}

// CreateTimeNEQ applies the NEQ predicate on the "create_time" field.
func CreateTimeNEQ(v time.Time) predicate.SyncProgress {
	return predicate.SyncProgress(sql.FieldNEQ(FieldCreateTime, v))
}

// CreateTimeIn applies the In predicate on the "create_time" field.
func CreateTimeIn(vs ...time.Time) predicate.SyncProgress {
	return predicate.SyncProgress(sql.FieldIn(FieldCreateTime, vs...))
}

// CreateTimeNotIn applies the NotIn predicate on the "create_time" field.
func CreateTimeNotIn(vs ...time.Time) predicate.SyncProgress {
	return predicate.SyncProgress(sql.FieldNotIn(FieldCreateTime, vs...))
}

// CreateTimeGT applies the GT predicate on the "create_time" field.
func CreateTimeGT(v time.Time) predicate.SyncProgress {
	return predicate.SyncProgress(sql.FieldGT(FieldCreateTime, v))
}

// CreateTimeGTE applies the GTE predicate on the "create_time" field.
func CreateTimeGTE(v time.Time) predicate.SyncProgress {
	return predicate.SyncProgress(sql.FieldGTE(FieldCreateTime, v))
}

// CreateTimeLT applies the LT predicate on the "create_time" field.
func CreateTimeLT(v time.Time) predicate.SyncProgress {
	return predicate.SyncProgress(sql.FieldLT(FieldCreateTime, v))
}

// CreateTimeLTE applies the LTE predicate on the "create_time" field.
func CreateTimeLTE(v time.Time) predicate.SyncProgress {
	return predicate.SyncProgress(sql.FieldLTE(FieldCreateTime, v))
}

// UpdateTimeEQ applies the EQ predicate on the "update_time" field.
func UpdateTimeEQ(v time.Time) predicate.SyncProgress {
	return predicate.SyncProgress(sql.FieldEQ(FieldUpdateTime, v))
}

// UpdateTimeNEQ applies the NEQ predicate on the "update_time" field.
func UpdateTimeNEQ(v time.Time) predicate.SyncProgress {
	return predicate.SyncProgress(sql.FieldNEQ(FieldUpdateTime, v))
}

// UpdateTimeIn applies the In predicate on the "update_time" field.
func UpdateTimeIn(vs ...time.Time) predicate.SyncProgress {
	return predicate.SyncProgress(sql.FieldIn(FieldUpdateTime, vs...))
}

// UpdateTimeNotIn applies the NotIn predicate on the "update_time" field.
func UpdateTimeNotIn(vs ...time.Time) predicate.SyncProgress {
	return predicate.SyncProgress(sql.FieldNotIn(FieldUpdateTime, vs...))
}

// UpdateTimeGT applies the GT predicate on the "update_time" field.
func UpdateTimeGT(v time.Time) predicate.SyncProgress {
	return predicate.SyncProgress(sql.FieldGT(FieldUpdateTime, v))
}

// UpdateTimeGTE applies the GTE predicate on the "update_time" field.
func UpdateTimeGTE(v time.Time) predicate.SyncProgress {
	return predicate.SyncProgress(sql.FieldGTE(FieldUpdateTime, v))
}

// UpdateTimeLT applies the LT predicate on the "update_time" field.
func UpdateTimeLT(v time.Time) predicate.SyncProgress {
	return predicate.SyncProgress(sql.FieldLT(FieldUpdateTime, v))
}

// UpdateTimeLTE applies the LTE predicate on the "update_time" field.
func UpdateTimeLTE(v time.Time) predicate.SyncProgress {
	return predicate.SyncProgress(sql.FieldLTE(FieldUpdateTime, v))
}

// ExchangeEQ applies the EQ predicate on the "exchange" field.
func ExchangeEQ(v string) predicate.SyncProgress {
	return predicate.SyncProgress(sql.FieldEQ(FieldExchange, v))
}

// ExchangeNEQ applies the NEQ predicate on the "exchange" field.
func ExchangeNEQ(v string) predicate.SyncProgress {
	return predicate.SyncProgress(sql.FieldNEQ(FieldExchange, v))
}

// ExchangeIn applies the In predicate on the "exchange" field.
func ExchangeIn(vs ...string) predicate.SyncProgress {
	return predicate.SyncProgress(sql.FieldIn(FieldExchange, vs...))
}

// ExchangeNotIn applies the NotIn predicate on the "exchange" field.
func ExchangeNotIn(vs ...string) predicate.SyncProgress {
	return predicate.SyncProgress(sql.FieldNotIn(FieldExchange, vs...))
}

// ExchangeGT applies the GT predicate on the "exchange" field.
func ExchangeGT(v string) predicate.SyncProgress {
	return predicate.SyncProgress(sql.FieldGT(FieldExchange, v))
}

// ExchangeGTE applies the GTE predicate on the "exchange" field.
func ExchangeGTE(v string) predicate.SyncProgress {
	return predicate.SyncProgress(sql.FieldGTE(FieldExchange, v))
}

// ExchangeLT applies the LT predicate on the "exchange" field.
func ExchangeLT(v string) predicate.SyncProgress {
	return predicate.SyncProgress(sql.FieldLT(FieldExchange, v))
}

// ExchangeLTE applies the LTE predicate on the "exchange" field.
func ExchangeLTE(v string) predicate.SyncProgress {
	return predicate.SyncProgress(sql.FieldLTE(FieldExchange, v))
}

// ExchangeContains applies the Contains predicate on the "exchange" field.
func ExchangeContains(v string) predicate.SyncProgress {
	return predicate.SyncProgress(sql.FieldContains(FieldExchange, v))
}

// ExchangeHasPrefix applies the HasPrefix predicate on the "exchange" field.
func ExchangeHasPrefix(v string) predicate.SyncProgress {
	return predicate.SyncProgress(sql.FieldHasPrefix(FieldExchange, v))
}

// ExchangeHasSuffix applies the HasSuffix predicate on the "exchange" field.
func ExchangeHasSuffix(v string) predicate.SyncProgress {
	return predicate.SyncProgress(sql.FieldHasSuffix(FieldExchange, v))
}

// ExchangeEqualFold applies the EqualFold predicate on the "exchange" field.
func ExchangeEqualFold(v string) predicate.SyncProgress {
	return predicate.SyncProgress(sql.FieldEqualFold(FieldExchange, v))
}

// ExchangeContainsFold applies the ContainsFold predicate on the "exchange" field.
func ExchangeContainsFold(v string) predicate.SyncProgress {
	return predicate.SyncProgress(sql.FieldContainsFold(FieldExchange, v))
}

// AccountEQ applies the EQ predicate on the "account" field.
func AccountEQ(v string) predicate.SyncProgress {
	return predicate.SyncProgress(sql.FieldEQ(FieldAccount, v))
}

// AccountNEQ applies the NEQ predicate on the "account" field.
func AccountNEQ(v string) predicate.SyncProgress {
	return predicate.SyncProgress(sql.FieldNEQ(FieldAccount, v))
}

// AccountIn applies the In predicate on the "account" field.
func AccountIn(vs ...string) predicate.SyncProgress {
	return predicate.SyncProgress(sql.FieldIn(FieldAccount, vs...))
}

// AccountNotIn applies the NotIn predicate on the "account" field.
func AccountNotIn(vs ...string) predicate.SyncProgress {
	return predicate.SyncProgress(sql.FieldNotIn(FieldAccount, vs...))
}

// AccountGT applies the GT predicate on the "account" field.
func AccountGT(v string) predicate.SyncProgress {
	return predicate.SyncProgress(sql.FieldGT(FieldAccount, v))
}

// AccountGTE applies the GTE predicate on the "account" field.
func AccountGTE(v string) predicate.SyncProgress {
	return predicate.SyncProgress(sql.FieldGTE(FieldAccount, v))
}

// AccountLT applies the LT predicate on the "account" field.
func AccountLT(v string) predicate.SyncProgress {
	return predicate.SyncProgress(sql.FieldLT(FieldAccount, v))
}

// AccountLTE applies the LTE predicate on the "account" field.
func AccountLTE(v string) predicate.SyncProgress {
	return predicate.SyncProgress(sql.FieldLTE(FieldAccount, v))
}

// AccountContains applies the Contains predicate on the "account" field.
func AccountContains(v string) predicate.SyncProgress {
	return predicate.SyncProgress(sql.FieldContains(FieldAccount, v))
}

// AccountHasPrefix applies the HasPrefix predicate on the "account" field.
func AccountHasPrefix(v string) predicate.SyncProgress {
	return predicate.SyncProgress(sql.FieldHasPrefix(FieldAccount, v))
}

// AccountHasSuffix applies the HasSuffix predicate on the "account" field.
func AccountHasSuffix(v string) predicate.SyncProgress {
	return predicate.SyncProgress(sql.FieldHasSuffix(FieldAccount, v))
}

// AccountEqualFold applies the EqualFold predicate on the "account" field.
func AccountEqualFold(v string) predicate.SyncProgress {
	return predicate.SyncProgress(sql.FieldEqualFold(FieldAccount, v))
}

// AccountContainsFold applies the ContainsFold predicate on the "account" field.
func AccountContainsFold(v string) predicate.SyncProgress {
	return predicate.SyncProgress(sql.FieldContainsFold(FieldAccount, v))
}

// TimestampEQ applies the EQ predicate on the "timestamp" field.
func TimestampEQ(v int64) predicate.SyncProgress {
	return predicate.SyncProgress(sql.FieldEQ(FieldTimestamp, v))
}

// TimestampNEQ applies the NEQ predicate on the "timestamp" field.
func TimestampNEQ(v int64) predicate.SyncProgress {
	return predicate.SyncProgress(sql.FieldNEQ(FieldTimestamp, v))
}

// TimestampIn applies the In predicate on the "timestamp" field.
func TimestampIn(vs ...int64) predicate.SyncProgress {
	return predicate.SyncProgress(sql.FieldIn(FieldTimestamp, vs...))
}

// TimestampNotIn applies the NotIn predicate on the "timestamp" field.
func TimestampNotIn(vs ...int64) predicate.SyncProgress {
	return predicate.SyncProgress(sql.FieldNotIn(FieldTimestamp, vs...))
}

// TimestampGT applies the GT predicate on the "timestamp" field.
func TimestampGT(v int64) predicate.SyncProgress {
	return predicate.SyncProgress(sql.FieldGT(FieldTimestamp, v))
}

// TimestampGTE applies the GTE predicate on the "timestamp" field.
func TimestampGTE(v int64) predicate.SyncProgress {
	return predicate.SyncProgress(sql.FieldGTE(FieldTimestamp, v))
}

// TimestampLT applies the LT predicate on the "timestamp" field.
func TimestampLT(v int64) predicate.SyncProgress {
	return predicate.SyncProgress(sql.FieldLT(FieldTimestamp, v))
}

// TimestampLTE applies the LTE predicate on the "timestamp" field.
func TimestampLTE(v int64) predicate.SyncProgress {
	return predicate.SyncProgress(sql.FieldLTE(FieldTimestamp, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SyncProgress) predicate.SyncProgress {
	return predicate.SyncProgress(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SyncProgress) predicate.SyncProgress {
	return predicate.SyncProgress(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SyncProgress) predicate.SyncProgress {
	return predicate.SyncProgress(sql.NotPredicates(p))
}
