// Code generated by ent, DO NOT EDIT.

package order

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the order type in the database.
	Label = "order"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreateTime holds the string denoting the create_time field in the database.
	FieldCreateTime = "create_time"
	// FieldUpdateTime holds the string denoting the update_time field in the database.
	FieldUpdateTime = "update_time"
	// FieldExchange holds the string denoting the exchange field in the database.
	FieldExchange = "exchange"
	// FieldAccount holds the string denoting the account field in the database.
	FieldAccount = "account"
	// FieldSymbol holds the string denoting the symbol field in the database.
	FieldSymbol = "symbol"
	// FieldOrderID holds the string denoting the order_id field in the database.
	FieldOrderID = "order_id"
	// FieldClientOrderID holds the string denoting the client_order_id field in the database.
	FieldClientOrderID = "client_order_id"
	// FieldSide holds the string denoting the side field in the database.
	FieldSide = "side"
	// FieldPrice holds the string denoting the price field in the database.
	FieldPrice = "price"
	// FieldBaseAmount holds the string denoting the baseamount field in the database.
	FieldBaseAmount = "base_amount"
	// FieldFilledBaseAmount holds the string denoting the filledbaseamount field in the database.
	FieldFilledBaseAmount = "filled_base_amount"
	// FieldFilledQuoteAmount holds the string denoting the filledquoteamount field in the database.
	FieldFilledQuoteAmount = "filled_quote_amount"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldTimestamp holds the string denoting the timestamp field in the database.
	FieldTimestamp = "timestamp"
	// Table holds the table name of the order in the database.
	Table = "orders"
)

// Columns holds all SQL columns for order fields.
var Columns = []string{
	FieldID,
	FieldCreateTime,
	FieldUpdateTime,
	FieldExchange,
	FieldAccount,
	FieldSymbol,
	FieldOrderID,
	FieldClientOrderID,
	FieldSide,
	FieldPrice,
	FieldBaseAmount,
	FieldFilledBaseAmount,
	FieldFilledQuoteAmount,
	FieldStatus,
	FieldTimestamp,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreateTime holds the default value on creation for the "create_time" field.
	DefaultCreateTime func() time.Time
	// DefaultUpdateTime holds the default value on creation for the "update_time" field.
	DefaultUpdateTime func() time.Time
	// UpdateDefaultUpdateTime holds the default value on update for the "update_time" field.
	UpdateDefaultUpdateTime func() time.Time
)

// Status defines the type for the "status" enum field.
type Status string

// Status values.
const (
	StatusInProgress Status = "in-progress"
	StatusPending    Status = "pending"
	StatusOpen       Status = "open"
	StatusFilled     Status = "filled"
	StatusCanceled   Status = "canceled"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusInProgress, StatusPending, StatusOpen, StatusFilled, StatusCanceled:
		return nil
	default:
		return fmt.Errorf("order: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the Order queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreateTime orders the results by the create_time field.
func ByCreateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreateTime, opts...).ToFunc()
}

// ByUpdateTime orders the results by the update_time field.
func ByUpdateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdateTime, opts...).ToFunc()
}

// ByExchange orders the results by the exchange field.
func ByExchange(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExchange, opts...).ToFunc()
}

// ByAccount orders the results by the account field.
func ByAccount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccount, opts...).ToFunc()
}

// BySymbol orders the results by the symbol field.
func BySymbol(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSymbol, opts...).ToFunc()
}

// ByOrderID orders the results by the order_id field.
func ByOrderID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOrderID, opts...).ToFunc()
}

// ByClientOrderID orders the results by the client_order_id field.
func ByClientOrderID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldClientOrderID, opts...).ToFunc()
}

// BySide orders the results by the side field.
func BySide(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSide, opts...).ToFunc()
}

// ByPrice orders the results by the price field.
func ByPrice(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPrice, opts...).ToFunc()
}

// ByBaseAmount orders the results by the baseAmount field.
func ByBaseAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBaseAmount, opts...).ToFunc()
}

// ByFilledBaseAmount orders the results by the filledBaseAmount field.
func ByFilledBaseAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFilledBaseAmount, opts...).ToFunc()
}

// ByFilledQuoteAmount orders the results by the filledQuoteAmount field.
func ByFilledQuoteAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFilledQuoteAmount, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByTimestamp orders the results by the timestamp field.
func ByTimestamp(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTimestamp, opts...).ToFunc()
}
