// Code generated by ent, DO NOT EDIT.

package order

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/fachebot/omni-grid-bot/internal/ent/predicate"
	"github.com/shopspring/decimal"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Order {
	return predicate.Order(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Order {
	return predicate.Order(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Order {
	return predicate.Order(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Order {
	return predicate.Order(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Order {
	return predicate.Order(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Order {
	return predicate.Order(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Order {
	return predicate.Order(sql.FieldLTE(FieldID, id))
}

// CreateTime applies equality check predicate on the "create_time" field. It's identical to CreateTimeEQ.
func CreateTime(v time.Time) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldCreateTime, v))
}

// UpdateTime applies equality check predicate on the "update_time" field. It's identical to UpdateTimeEQ.
func UpdateTime(v time.Time) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldUpdateTime, v))
}

// Exchange applies equality check predicate on the "exchange" field. It's identical to ExchangeEQ.
func Exchange(v string) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldExchange, v))
}

// Account applies equality check predicate on the "account" field. It's identical to AccountEQ.
func Account(v string) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldAccount, v))
}

// Symbol applies equality check predicate on the "symbol" field. It's identical to SymbolEQ.
func Symbol(v string) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldSymbol, v))
}

// OrderId applies equality check predicate on the "orderId" field. It's identical to OrderIdEQ.
func OrderId(v string) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldOrderId, v))
}

// ClientOrderId applies equality check predicate on the "clientOrderId" field. It's identical to ClientOrderIdEQ.
func ClientOrderId(v string) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldClientOrderId, v))
}

// Price applies equality check predicate on the "price" field. It's identical to PriceEQ.
func Price(v decimal.Decimal) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldPrice, v))
}

// BaseAmount applies equality check predicate on the "baseAmount" field. It's identical to BaseAmountEQ.
func BaseAmount(v decimal.Decimal) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldBaseAmount, v))
}

// FilledBaseAmount applies equality check predicate on the "filledBaseAmount" field. It's identical to FilledBaseAmountEQ.
func FilledBaseAmount(v decimal.Decimal) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldFilledBaseAmount, v))
}

// FilledQuoteAmount applies equality check predicate on the "filledQuoteAmount" field. It's identical to FilledQuoteAmountEQ.
func FilledQuoteAmount(v decimal.Decimal) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldFilledQuoteAmount, v))
}

// Timestamp applies equality check predicate on the "timestamp" field. It's identical to TimestampEQ.
func Timestamp(v int64) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldTimestamp, v))
}

// CreateTimeEQ applies the EQ predicate on the "create_time" field.
func CreateTimeEQ(v time.Time) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldCreateTime, v))
}

// CreateTimeNEQ applies the NEQ predicate on the "create_time" field.
func CreateTimeNEQ(v time.Time) predicate.Order {
	return predicate.Order(sql.FieldNEQ(FieldCreateTime, v))
}

// CreateTimeIn applies the In predicate on the "create_time" field.
func CreateTimeIn(vs ...time.Time) predicate.Order {
	return predicate.Order(sql.FieldIn(FieldCreateTime, vs...))
}

// CreateTimeNotIn applies the NotIn predicate on the "create_time" field.
func CreateTimeNotIn(vs ...time.Time) predicate.Order {
	return predicate.Order(sql.FieldNotIn(FieldCreateTime, vs...))
}

// CreateTimeGT applies the GT predicate on the "create_time" field.
func CreateTimeGT(v time.Time) predicate.Order {
	return predicate.Order(sql.FieldGT(FieldCreateTime, v))
}

// CreateTimeGTE applies the GTE predicate on the "create_time" field.
func CreateTimeGTE(v time.Time) predicate.Order {
	return predicate.Order(sql.FieldGTE(FieldCreateTime, v))
}

// CreateTimeLT applies the LT predicate on the "create_time" field.
func CreateTimeLT(v time.Time) predicate.Order {
	return predicate.Order(sql.FieldLT(FieldCreateTime, v))
}

// CreateTimeLTE applies the LTE predicate on the "create_time" field.
func CreateTimeLTE(v time.Time) predicate.Order {
	return predicate.Order(sql.FieldLTE(FieldCreateTime, v))
}

// UpdateTimeEQ applies the EQ predicate on the "update_time" field.
func UpdateTimeEQ(v time.Time) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldUpdateTime, v))
}

// UpdateTimeNEQ applies the NEQ predicate on the "update_time" field.
func UpdateTimeNEQ(v time.Time) predicate.Order {
	return predicate.Order(sql.FieldNEQ(FieldUpdateTime, v))
}

// UpdateTimeIn applies the In predicate on the "update_time" field.
func UpdateTimeIn(vs ...time.Time) predicate.Order {
	return predicate.Order(sql.FieldIn(FieldUpdateTime, vs...))
}

// UpdateTimeNotIn applies the NotIn predicate on the "update_time" field.
func UpdateTimeNotIn(vs ...time.Time) predicate.Order {
	return predicate.Order(sql.FieldNotIn(FieldUpdateTime, vs...))
}

// UpdateTimeGT applies the GT predicate on the "update_time" field.
func UpdateTimeGT(v time.Time) predicate.Order {
	return predicate.Order(sql.FieldGT(FieldUpdateTime, v))
}

// UpdateTimeGTE applies the GTE predicate on the "update_time" field.
func UpdateTimeGTE(v time.Time) predicate.Order {
	return predicate.Order(sql.FieldGTE(FieldUpdateTime, v))
}

// UpdateTimeLT applies the LT predicate on the "update_time" field.
func UpdateTimeLT(v time.Time) predicate.Order {
	return predicate.Order(sql.FieldLT(FieldUpdateTime, v))
}

// UpdateTimeLTE applies the LTE predicate on the "update_time" field.
func UpdateTimeLTE(v time.Time) predicate.Order {
	return predicate.Order(sql.FieldLTE(FieldUpdateTime, v))
}

// ExchangeEQ applies the EQ predicate on the "exchange" field.
func ExchangeEQ(v string) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldExchange, v))
}

// ExchangeNEQ applies the NEQ predicate on the "exchange" field.
func ExchangeNEQ(v string) predicate.Order {
	return predicate.Order(sql.FieldNEQ(FieldExchange, v))
}

// ExchangeIn applies the In predicate on the "exchange" field.
func ExchangeIn(vs ...string) predicate.Order {
	return predicate.Order(sql.FieldIn(FieldExchange, vs...))
}

// ExchangeNotIn applies the NotIn predicate on the "exchange" field.
func ExchangeNotIn(vs ...string) predicate.Order {
	return predicate.Order(sql.FieldNotIn(FieldExchange, vs...))
}

// ExchangeGT applies the GT predicate on the "exchange" field.
func ExchangeGT(v string) predicate.Order {
	return predicate.Order(sql.FieldGT(FieldExchange, v))
}

// ExchangeGTE applies the GTE predicate on the "exchange" field.
func ExchangeGTE(v string) predicate.Order {
	return predicate.Order(sql.FieldGTE(FieldExchange, v))
}

// ExchangeLT applies the LT predicate on the "exchange" field.
func ExchangeLT(v string) predicate.Order {
	return predicate.Order(sql.FieldLT(FieldExchange, v))
}

// ExchangeLTE applies the LTE predicate on the "exchange" field.
func ExchangeLTE(v string) predicate.Order {
	return predicate.Order(sql.FieldLTE(FieldExchange, v))
}

// ExchangeContains applies the Contains predicate on the "exchange" field.
func ExchangeContains(v string) predicate.Order {
	return predicate.Order(sql.FieldContains(FieldExchange, v))
}

// ExchangeHasPrefix applies the HasPrefix predicate on the "exchange" field.
func ExchangeHasPrefix(v string) predicate.Order {
	return predicate.Order(sql.FieldHasPrefix(FieldExchange, v))
}

// ExchangeHasSuffix applies the HasSuffix predicate on the "exchange" field.
func ExchangeHasSuffix(v string) predicate.Order {
	return predicate.Order(sql.FieldHasSuffix(FieldExchange, v))
}

// ExchangeEqualFold applies the EqualFold predicate on the "exchange" field.
func ExchangeEqualFold(v string) predicate.Order {
	return predicate.Order(sql.FieldEqualFold(FieldExchange, v))
}

// ExchangeContainsFold applies the ContainsFold predicate on the "exchange" field.
func ExchangeContainsFold(v string) predicate.Order {
	return predicate.Order(sql.FieldContainsFold(FieldExchange, v))
}

// AccountEQ applies the EQ predicate on the "account" field.
func AccountEQ(v string) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldAccount, v))
}

// AccountNEQ applies the NEQ predicate on the "account" field.
func AccountNEQ(v string) predicate.Order {
	return predicate.Order(sql.FieldNEQ(FieldAccount, v))
}

// AccountIn applies the In predicate on the "account" field.
func AccountIn(vs ...string) predicate.Order {
	return predicate.Order(sql.FieldIn(FieldAccount, vs...))
}

// AccountNotIn applies the NotIn predicate on the "account" field.
func AccountNotIn(vs ...string) predicate.Order {
	return predicate.Order(sql.FieldNotIn(FieldAccount, vs...))
}

// AccountGT applies the GT predicate on the "account" field.
func AccountGT(v string) predicate.Order {
	return predicate.Order(sql.FieldGT(FieldAccount, v))
}

// AccountGTE applies the GTE predicate on the "account" field.
func AccountGTE(v string) predicate.Order {
	return predicate.Order(sql.FieldGTE(FieldAccount, v))
}

// AccountLT applies the LT predicate on the "account" field.
func AccountLT(v string) predicate.Order {
	return predicate.Order(sql.FieldLT(FieldAccount, v))
}

// AccountLTE applies the LTE predicate on the "account" field.
func AccountLTE(v string) predicate.Order {
	return predicate.Order(sql.FieldLTE(FieldAccount, v))
}

// AccountContains applies the Contains predicate on the "account" field.
func AccountContains(v string) predicate.Order {
	return predicate.Order(sql.FieldContains(FieldAccount, v))
}

// AccountHasPrefix applies the HasPrefix predicate on the "account" field.
func AccountHasPrefix(v string) predicate.Order {
	return predicate.Order(sql.FieldHasPrefix(FieldAccount, v))
}

// AccountHasSuffix applies the HasSuffix predicate on the "account" field.
func AccountHasSuffix(v string) predicate.Order {
	return predicate.Order(sql.FieldHasSuffix(FieldAccount, v))
}

// AccountEqualFold applies the EqualFold predicate on the "account" field.
func AccountEqualFold(v string) predicate.Order {
	return predicate.Order(sql.FieldEqualFold(FieldAccount, v))
}

// AccountContainsFold applies the ContainsFold predicate on the "account" field.
func AccountContainsFold(v string) predicate.Order {
	return predicate.Order(sql.FieldContainsFold(FieldAccount, v))
}

// SymbolEQ applies the EQ predicate on the "symbol" field.
func SymbolEQ(v string) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldSymbol, v))
}

// SymbolNEQ applies the NEQ predicate on the "symbol" field.
func SymbolNEQ(v string) predicate.Order {
	return predicate.Order(sql.FieldNEQ(FieldSymbol, v))
}

// SymbolIn applies the In predicate on the "symbol" field.
func SymbolIn(vs ...string) predicate.Order {
	return predicate.Order(sql.FieldIn(FieldSymbol, vs...))
}

// SymbolNotIn applies the NotIn predicate on the "symbol" field.
func SymbolNotIn(vs ...string) predicate.Order {
	return predicate.Order(sql.FieldNotIn(FieldSymbol, vs...))
}

// SymbolGT applies the GT predicate on the "symbol" field.
func SymbolGT(v string) predicate.Order {
	return predicate.Order(sql.FieldGT(FieldSymbol, v))
}

// SymbolGTE applies the GTE predicate on the "symbol" field.
func SymbolGTE(v string) predicate.Order {
	return predicate.Order(sql.FieldGTE(FieldSymbol, v))
}

// SymbolLT applies the LT predicate on the "symbol" field.
func SymbolLT(v string) predicate.Order {
	return predicate.Order(sql.FieldLT(FieldSymbol, v))
}

// SymbolLTE applies the LTE predicate on the "symbol" field.
func SymbolLTE(v string) predicate.Order {
	return predicate.Order(sql.FieldLTE(FieldSymbol, v))
}

// SymbolContains applies the Contains predicate on the "symbol" field.
func SymbolContains(v string) predicate.Order {
	return predicate.Order(sql.FieldContains(FieldSymbol, v))
}

// SymbolHasPrefix applies the HasPrefix predicate on the "symbol" field.
func SymbolHasPrefix(v string) predicate.Order {
	return predicate.Order(sql.FieldHasPrefix(FieldSymbol, v))
}

// SymbolHasSuffix applies the HasSuffix predicate on the "symbol" field.
func SymbolHasSuffix(v string) predicate.Order {
	return predicate.Order(sql.FieldHasSuffix(FieldSymbol, v))
}

// SymbolEqualFold applies the EqualFold predicate on the "symbol" field.
func SymbolEqualFold(v string) predicate.Order {
	return predicate.Order(sql.FieldEqualFold(FieldSymbol, v))
}

// SymbolContainsFold applies the ContainsFold predicate on the "symbol" field.
func SymbolContainsFold(v string) predicate.Order {
	return predicate.Order(sql.FieldContainsFold(FieldSymbol, v))
}

// OrderIdEQ applies the EQ predicate on the "orderId" field.
func OrderIdEQ(v string) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldOrderId, v))
}

// OrderIdNEQ applies the NEQ predicate on the "orderId" field.
func OrderIdNEQ(v string) predicate.Order {
	return predicate.Order(sql.FieldNEQ(FieldOrderId, v))
}

// OrderIdIn applies the In predicate on the "orderId" field.
func OrderIdIn(vs ...string) predicate.Order {
	return predicate.Order(sql.FieldIn(FieldOrderId, vs...))
}

// OrderIdNotIn applies the NotIn predicate on the "orderId" field.
func OrderIdNotIn(vs ...string) predicate.Order {
	return predicate.Order(sql.FieldNotIn(FieldOrderId, vs...))
}

// OrderIdGT applies the GT predicate on the "orderId" field.
func OrderIdGT(v string) predicate.Order {
	return predicate.Order(sql.FieldGT(FieldOrderId, v))
}

// OrderIdGTE applies the GTE predicate on the "orderId" field.
func OrderIdGTE(v string) predicate.Order {
	return predicate.Order(sql.FieldGTE(FieldOrderId, v))
}

// OrderIdLT applies the LT predicate on the "orderId" field.
func OrderIdLT(v string) predicate.Order {
	return predicate.Order(sql.FieldLT(FieldOrderId, v))
}

// OrderIdLTE applies the LTE predicate on the "orderId" field.
func OrderIdLTE(v string) predicate.Order {
	return predicate.Order(sql.FieldLTE(FieldOrderId, v))
}

// OrderIdContains applies the Contains predicate on the "orderId" field.
func OrderIdContains(v string) predicate.Order {
	return predicate.Order(sql.FieldContains(FieldOrderId, v))
}

// OrderIdHasPrefix applies the HasPrefix predicate on the "orderId" field.
func OrderIdHasPrefix(v string) predicate.Order {
	return predicate.Order(sql.FieldHasPrefix(FieldOrderId, v))
}

// OrderIdHasSuffix applies the HasSuffix predicate on the "orderId" field.
func OrderIdHasSuffix(v string) predicate.Order {
	return predicate.Order(sql.FieldHasSuffix(FieldOrderId, v))
}

// OrderIdEqualFold applies the EqualFold predicate on the "orderId" field.
func OrderIdEqualFold(v string) predicate.Order {
	return predicate.Order(sql.FieldEqualFold(FieldOrderId, v))
}

// OrderIdContainsFold applies the ContainsFold predicate on the "orderId" field.
func OrderIdContainsFold(v string) predicate.Order {
	return predicate.Order(sql.FieldContainsFold(FieldOrderId, v))
}

// ClientOrderIdEQ applies the EQ predicate on the "clientOrderId" field.
func ClientOrderIdEQ(v string) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldClientOrderId, v))
}

// ClientOrderIdNEQ applies the NEQ predicate on the "clientOrderId" field.
func ClientOrderIdNEQ(v string) predicate.Order {
	return predicate.Order(sql.FieldNEQ(FieldClientOrderId, v))
}

// ClientOrderIdIn applies the In predicate on the "clientOrderId" field.
func ClientOrderIdIn(vs ...string) predicate.Order {
	return predicate.Order(sql.FieldIn(FieldClientOrderId, vs...))
}

// ClientOrderIdNotIn applies the NotIn predicate on the "clientOrderId" field.
func ClientOrderIdNotIn(vs ...string) predicate.Order {
	return predicate.Order(sql.FieldNotIn(FieldClientOrderId, vs...))
}

// ClientOrderIdGT applies the GT predicate on the "clientOrderId" field.
func ClientOrderIdGT(v string) predicate.Order {
	return predicate.Order(sql.FieldGT(FieldClientOrderId, v))
}

// ClientOrderIdGTE applies the GTE predicate on the "clientOrderId" field.
func ClientOrderIdGTE(v string) predicate.Order {
	return predicate.Order(sql.FieldGTE(FieldClientOrderId, v))
}

// ClientOrderIdLT applies the LT predicate on the "clientOrderId" field.
func ClientOrderIdLT(v string) predicate.Order {
	return predicate.Order(sql.FieldLT(FieldClientOrderId, v))
}

// ClientOrderIdLTE applies the LTE predicate on the "clientOrderId" field.
func ClientOrderIdLTE(v string) predicate.Order {
	return predicate.Order(sql.FieldLTE(FieldClientOrderId, v))
}

// ClientOrderIdContains applies the Contains predicate on the "clientOrderId" field.
func ClientOrderIdContains(v string) predicate.Order {
	return predicate.Order(sql.FieldContains(FieldClientOrderId, v))
}

// ClientOrderIdHasPrefix applies the HasPrefix predicate on the "clientOrderId" field.
func ClientOrderIdHasPrefix(v string) predicate.Order {
	return predicate.Order(sql.FieldHasPrefix(FieldClientOrderId, v))
}

// ClientOrderIdHasSuffix applies the HasSuffix predicate on the "clientOrderId" field.
func ClientOrderIdHasSuffix(v string) predicate.Order {
	return predicate.Order(sql.FieldHasSuffix(FieldClientOrderId, v))
}

// ClientOrderIdEqualFold applies the EqualFold predicate on the "clientOrderId" field.
func ClientOrderIdEqualFold(v string) predicate.Order {
	return predicate.Order(sql.FieldEqualFold(FieldClientOrderId, v))
}

// ClientOrderIdContainsFold applies the ContainsFold predicate on the "clientOrderId" field.
func ClientOrderIdContainsFold(v string) predicate.Order {
	return predicate.Order(sql.FieldContainsFold(FieldClientOrderId, v))
}

// SideEQ applies the EQ predicate on the "side" field.
func SideEQ(v Side) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldSide, v))
}

// SideNEQ applies the NEQ predicate on the "side" field.
func SideNEQ(v Side) predicate.Order {
	return predicate.Order(sql.FieldNEQ(FieldSide, v))
}

// SideIn applies the In predicate on the "side" field.
func SideIn(vs ...Side) predicate.Order {
	return predicate.Order(sql.FieldIn(FieldSide, vs...))
}

// SideNotIn applies the NotIn predicate on the "side" field.
func SideNotIn(vs ...Side) predicate.Order {
	return predicate.Order(sql.FieldNotIn(FieldSide, vs...))
}

// PriceEQ applies the EQ predicate on the "price" field.
func PriceEQ(v decimal.Decimal) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldPrice, v))
}

// PriceNEQ applies the NEQ predicate on the "price" field.
func PriceNEQ(v decimal.Decimal) predicate.Order {
	return predicate.Order(sql.FieldNEQ(FieldPrice, v))
}

// PriceIn applies the In predicate on the "price" field.
func PriceIn(vs ...decimal.Decimal) predicate.Order {
	return predicate.Order(sql.FieldIn(FieldPrice, vs...))
}

// PriceNotIn applies the NotIn predicate on the "price" field.
func PriceNotIn(vs ...decimal.Decimal) predicate.Order {
	return predicate.Order(sql.FieldNotIn(FieldPrice, vs...))
}

// PriceGT applies the GT predicate on the "price" field.
func PriceGT(v decimal.Decimal) predicate.Order {
	return predicate.Order(sql.FieldGT(FieldPrice, v))
}

// PriceGTE applies the GTE predicate on the "price" field.
func PriceGTE(v decimal.Decimal) predicate.Order {
	return predicate.Order(sql.FieldGTE(FieldPrice, v))
}

// PriceLT applies the LT predicate on the "price" field.
func PriceLT(v decimal.Decimal) predicate.Order {
	return predicate.Order(sql.FieldLT(FieldPrice, v))
}

// PriceLTE applies the LTE predicate on the "price" field.
func PriceLTE(v decimal.Decimal) predicate.Order {
	return predicate.Order(sql.FieldLTE(FieldPrice, v))
}

// PriceContains applies the Contains predicate on the "price" field.
func PriceContains(v decimal.Decimal) predicate.Order {
	vc := v.String()
	return predicate.Order(sql.FieldContains(FieldPrice, vc))
}

// PriceHasPrefix applies the HasPrefix predicate on the "price" field.
func PriceHasPrefix(v decimal.Decimal) predicate.Order {
	vc := v.String()
	return predicate.Order(sql.FieldHasPrefix(FieldPrice, vc))
}

// PriceHasSuffix applies the HasSuffix predicate on the "price" field.
func PriceHasSuffix(v decimal.Decimal) predicate.Order {
	vc := v.String()
	return predicate.Order(sql.FieldHasSuffix(FieldPrice, vc))
}

// PriceEqualFold applies the EqualFold predicate on the "price" field.
func PriceEqualFold(v decimal.Decimal) predicate.Order {
	vc := v.String()
	return predicate.Order(sql.FieldEqualFold(FieldPrice, vc))
}

// PriceContainsFold applies the ContainsFold predicate on the "price" field.
func PriceContainsFold(v decimal.Decimal) predicate.Order {
	vc := v.String()
	return predicate.Order(sql.FieldContainsFold(FieldPrice, vc))
}

// BaseAmountEQ applies the EQ predicate on the "baseAmount" field.
func BaseAmountEQ(v decimal.Decimal) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldBaseAmount, v))
}

// BaseAmountNEQ applies the NEQ predicate on the "baseAmount" field.
func BaseAmountNEQ(v decimal.Decimal) predicate.Order {
	return predicate.Order(sql.FieldNEQ(FieldBaseAmount, v))
}

// BaseAmountIn applies the In predicate on the "baseAmount" field.
func BaseAmountIn(vs ...decimal.Decimal) predicate.Order {
	return predicate.Order(sql.FieldIn(FieldBaseAmount, vs...))
}

// BaseAmountNotIn applies the NotIn predicate on the "baseAmount" field.
func BaseAmountNotIn(vs ...decimal.Decimal) predicate.Order {
	return predicate.Order(sql.FieldNotIn(FieldBaseAmount, vs...))
}

// BaseAmountGT applies the GT predicate on the "baseAmount" field.
func BaseAmountGT(v decimal.Decimal) predicate.Order {
	return predicate.Order(sql.FieldGT(FieldBaseAmount, v))
}

// BaseAmountGTE applies the GTE predicate on the "baseAmount" field.
func BaseAmountGTE(v decimal.Decimal) predicate.Order {
	return predicate.Order(sql.FieldGTE(FieldBaseAmount, v))
}

// BaseAmountLT applies the LT predicate on the "baseAmount" field.
func BaseAmountLT(v decimal.Decimal) predicate.Order {
	return predicate.Order(sql.FieldLT(FieldBaseAmount, v))
}

// BaseAmountLTE applies the LTE predicate on the "baseAmount" field.
func BaseAmountLTE(v decimal.Decimal) predicate.Order {
	return predicate.Order(sql.FieldLTE(FieldBaseAmount, v))
}

// BaseAmountContains applies the Contains predicate on the "baseAmount" field.
func BaseAmountContains(v decimal.Decimal) predicate.Order {
	vc := v.String()
	return predicate.Order(sql.FieldContains(FieldBaseAmount, vc))
}

// BaseAmountHasPrefix applies the HasPrefix predicate on the "baseAmount" field.
func BaseAmountHasPrefix(v decimal.Decimal) predicate.Order {
	vc := v.String()
	return predicate.Order(sql.FieldHasPrefix(FieldBaseAmount, vc))
}

// BaseAmountHasSuffix applies the HasSuffix predicate on the "baseAmount" field.
func BaseAmountHasSuffix(v decimal.Decimal) predicate.Order {
	vc := v.String()
	return predicate.Order(sql.FieldHasSuffix(FieldBaseAmount, vc))
}

// BaseAmountEqualFold applies the EqualFold predicate on the "baseAmount" field.
func BaseAmountEqualFold(v decimal.Decimal) predicate.Order {
	vc := v.String()
	return predicate.Order(sql.FieldEqualFold(FieldBaseAmount, vc))
}

// BaseAmountContainsFold applies the ContainsFold predicate on the "baseAmount" field.
func BaseAmountContainsFold(v decimal.Decimal) predicate.Order {
	vc := v.String()
	return predicate.Order(sql.FieldContainsFold(FieldBaseAmount, vc))
}

// FilledBaseAmountEQ applies the EQ predicate on the "filledBaseAmount" field.
func FilledBaseAmountEQ(v decimal.Decimal) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldFilledBaseAmount, v))
}

// FilledBaseAmountNEQ applies the NEQ predicate on the "filledBaseAmount" field.
func FilledBaseAmountNEQ(v decimal.Decimal) predicate.Order {
	return predicate.Order(sql.FieldNEQ(FieldFilledBaseAmount, v))
}

// FilledBaseAmountIn applies the In predicate on the "filledBaseAmount" field.
func FilledBaseAmountIn(vs ...decimal.Decimal) predicate.Order {
	return predicate.Order(sql.FieldIn(FieldFilledBaseAmount, vs...))
}

// FilledBaseAmountNotIn applies the NotIn predicate on the "filledBaseAmount" field.
func FilledBaseAmountNotIn(vs ...decimal.Decimal) predicate.Order {
	return predicate.Order(sql.FieldNotIn(FieldFilledBaseAmount, vs...))
}

// FilledBaseAmountGT applies the GT predicate on the "filledBaseAmount" field.
func FilledBaseAmountGT(v decimal.Decimal) predicate.Order {
	return predicate.Order(sql.FieldGT(FieldFilledBaseAmount, v))
}

// FilledBaseAmountGTE applies the GTE predicate on the "filledBaseAmount" field.
func FilledBaseAmountGTE(v decimal.Decimal) predicate.Order {
	return predicate.Order(sql.FieldGTE(FieldFilledBaseAmount, v))
}

// FilledBaseAmountLT applies the LT predicate on the "filledBaseAmount" field.
func FilledBaseAmountLT(v decimal.Decimal) predicate.Order {
	return predicate.Order(sql.FieldLT(FieldFilledBaseAmount, v))
}

// FilledBaseAmountLTE applies the LTE predicate on the "filledBaseAmount" field.
func FilledBaseAmountLTE(v decimal.Decimal) predicate.Order {
	return predicate.Order(sql.FieldLTE(FieldFilledBaseAmount, v))
}

// FilledBaseAmountContains applies the Contains predicate on the "filledBaseAmount" field.
func FilledBaseAmountContains(v decimal.Decimal) predicate.Order {
	vc := v.String()
	return predicate.Order(sql.FieldContains(FieldFilledBaseAmount, vc))
}

// FilledBaseAmountHasPrefix applies the HasPrefix predicate on the "filledBaseAmount" field.
func FilledBaseAmountHasPrefix(v decimal.Decimal) predicate.Order {
	vc := v.String()
	return predicate.Order(sql.FieldHasPrefix(FieldFilledBaseAmount, vc))
}

// FilledBaseAmountHasSuffix applies the HasSuffix predicate on the "filledBaseAmount" field.
func FilledBaseAmountHasSuffix(v decimal.Decimal) predicate.Order {
	vc := v.String()
	return predicate.Order(sql.FieldHasSuffix(FieldFilledBaseAmount, vc))
}

// FilledBaseAmountEqualFold applies the EqualFold predicate on the "filledBaseAmount" field.
func FilledBaseAmountEqualFold(v decimal.Decimal) predicate.Order {
	vc := v.String()
	return predicate.Order(sql.FieldEqualFold(FieldFilledBaseAmount, vc))
}

// FilledBaseAmountContainsFold applies the ContainsFold predicate on the "filledBaseAmount" field.
func FilledBaseAmountContainsFold(v decimal.Decimal) predicate.Order {
	vc := v.String()
	return predicate.Order(sql.FieldContainsFold(FieldFilledBaseAmount, vc))
}

// FilledQuoteAmountEQ applies the EQ predicate on the "filledQuoteAmount" field.
func FilledQuoteAmountEQ(v decimal.Decimal) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldFilledQuoteAmount, v))
}

// FilledQuoteAmountNEQ applies the NEQ predicate on the "filledQuoteAmount" field.
func FilledQuoteAmountNEQ(v decimal.Decimal) predicate.Order {
	return predicate.Order(sql.FieldNEQ(FieldFilledQuoteAmount, v))
}

// FilledQuoteAmountIn applies the In predicate on the "filledQuoteAmount" field.
func FilledQuoteAmountIn(vs ...decimal.Decimal) predicate.Order {
	return predicate.Order(sql.FieldIn(FieldFilledQuoteAmount, vs...))
}

// FilledQuoteAmountNotIn applies the NotIn predicate on the "filledQuoteAmount" field.
func FilledQuoteAmountNotIn(vs ...decimal.Decimal) predicate.Order {
	return predicate.Order(sql.FieldNotIn(FieldFilledQuoteAmount, vs...))
}

// FilledQuoteAmountGT applies the GT predicate on the "filledQuoteAmount" field.
func FilledQuoteAmountGT(v decimal.Decimal) predicate.Order {
	return predicate.Order(sql.FieldGT(FieldFilledQuoteAmount, v))
}

// FilledQuoteAmountGTE applies the GTE predicate on the "filledQuoteAmount" field.
func FilledQuoteAmountGTE(v decimal.Decimal) predicate.Order {
	return predicate.Order(sql.FieldGTE(FieldFilledQuoteAmount, v))
}

// FilledQuoteAmountLT applies the LT predicate on the "filledQuoteAmount" field.
func FilledQuoteAmountLT(v decimal.Decimal) predicate.Order {
	return predicate.Order(sql.FieldLT(FieldFilledQuoteAmount, v))
}

// FilledQuoteAmountLTE applies the LTE predicate on the "filledQuoteAmount" field.
func FilledQuoteAmountLTE(v decimal.Decimal) predicate.Order {
	return predicate.Order(sql.FieldLTE(FieldFilledQuoteAmount, v))
}

// FilledQuoteAmountContains applies the Contains predicate on the "filledQuoteAmount" field.
func FilledQuoteAmountContains(v decimal.Decimal) predicate.Order {
	vc := v.String()
	return predicate.Order(sql.FieldContains(FieldFilledQuoteAmount, vc))
}

// FilledQuoteAmountHasPrefix applies the HasPrefix predicate on the "filledQuoteAmount" field.
func FilledQuoteAmountHasPrefix(v decimal.Decimal) predicate.Order {
	vc := v.String()
	return predicate.Order(sql.FieldHasPrefix(FieldFilledQuoteAmount, vc))
}

// FilledQuoteAmountHasSuffix applies the HasSuffix predicate on the "filledQuoteAmount" field.
func FilledQuoteAmountHasSuffix(v decimal.Decimal) predicate.Order {
	vc := v.String()
	return predicate.Order(sql.FieldHasSuffix(FieldFilledQuoteAmount, vc))
}

// FilledQuoteAmountEqualFold applies the EqualFold predicate on the "filledQuoteAmount" field.
func FilledQuoteAmountEqualFold(v decimal.Decimal) predicate.Order {
	vc := v.String()
	return predicate.Order(sql.FieldEqualFold(FieldFilledQuoteAmount, vc))
}

// FilledQuoteAmountContainsFold applies the ContainsFold predicate on the "filledQuoteAmount" field.
func FilledQuoteAmountContainsFold(v decimal.Decimal) predicate.Order {
	vc := v.String()
	return predicate.Order(sql.FieldContainsFold(FieldFilledQuoteAmount, vc))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.Order {
	return predicate.Order(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.Order {
	return predicate.Order(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.Order {
	return predicate.Order(sql.FieldNotIn(FieldStatus, vs...))
}

// TimestampEQ applies the EQ predicate on the "timestamp" field.
func TimestampEQ(v int64) predicate.Order {
	return predicate.Order(sql.FieldEQ(FieldTimestamp, v))
}

// TimestampNEQ applies the NEQ predicate on the "timestamp" field.
func TimestampNEQ(v int64) predicate.Order {
	return predicate.Order(sql.FieldNEQ(FieldTimestamp, v))
}

// TimestampIn applies the In predicate on the "timestamp" field.
func TimestampIn(vs ...int64) predicate.Order {
	return predicate.Order(sql.FieldIn(FieldTimestamp, vs...))
}

// TimestampNotIn applies the NotIn predicate on the "timestamp" field.
func TimestampNotIn(vs ...int64) predicate.Order {
	return predicate.Order(sql.FieldNotIn(FieldTimestamp, vs...))
}

// TimestampGT applies the GT predicate on the "timestamp" field.
func TimestampGT(v int64) predicate.Order {
	return predicate.Order(sql.FieldGT(FieldTimestamp, v))
}

// TimestampGTE applies the GTE predicate on the "timestamp" field.
func TimestampGTE(v int64) predicate.Order {
	return predicate.Order(sql.FieldGTE(FieldTimestamp, v))
}

// TimestampLT applies the LT predicate on the "timestamp" field.
func TimestampLT(v int64) predicate.Order {
	return predicate.Order(sql.FieldLT(FieldTimestamp, v))
}

// TimestampLTE applies the LTE predicate on the "timestamp" field.
func TimestampLTE(v int64) predicate.Order {
	return predicate.Order(sql.FieldLTE(FieldTimestamp, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Order) predicate.Order {
	return predicate.Order(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Order) predicate.Order {
	return predicate.Order(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Order) predicate.Order {
	return predicate.Order(sql.NotPredicates(p))
}
